/**
 * Frame TypeScript Runtime Library
 * 
 * Provides Frame-semantic implementations for TypeScript/JavaScript
 * that differ from Python behavior, enabling consistent Frame execution
 * across target languages.
 * 
 * Generated by Frame Transpiler v0.86.13
 */

const ORDERED_DICT_STORE = new WeakMap<any, { store: Record<string, any>; order: string[] }>();
const COUNTER_STORE = new WeakMap<any, Map<string, number>>();
const CHAINMAP_STORE = new WeakMap<any, Array<Record<string, any>>>();

export class FrameRuntime {
    /**
     * Deep equality comparison for Frame semantics
     * Handles Sets, Maps, Arrays, Objects with proper content comparison
     * Falls back to === for primitives
     */
    static equals(left: any, right: any): boolean {
        // Handle null/undefined cases
        if (left === null || left === undefined || right === null || right === undefined) {
            return left === right;
        }

        // Handle primitive types - use strict equality
        if (typeof left !== 'object' || typeof right !== 'object') {
            return left === right;
        }

        // Handle Set comparison
        if (left instanceof Set && right instanceof Set) {
            if (left.size !== right.size) return false;
            for (const item of Array.from(left.values())) {
                if (!right.has(item)) return false;
            }
            return true;
        }

        // Handle Map comparison  
        if (left instanceof Map && right instanceof Map) {
            if (left.size !== right.size) return false;
            for (const [key, value] of Array.from(left.entries())) {
                if (!right.has(key) || !this.equals(right.get(key), value)) {
                    return false;
                }
            }
            return true;
        }

        // Handle Array comparison
        if (Array.isArray(left) && Array.isArray(right)) {
            if (left.length !== right.length) return false;
            for (let i = 0; i < left.length; i++) {
                if (!this.equals(left[i], right[i])) return false;
            }
            return true;
        }

        // Handle Object comparison (plain objects)
        if (left.constructor === Object && right.constructor === Object) {
            const leftKeys = Object.keys(left);
            const rightKeys = Object.keys(right);
            if (leftKeys.length !== rightKeys.length) return false;
            
            for (const key of leftKeys) {
                if (!(key in right) || !this.equals(left[key], right[key])) {
                    return false;
                }
            }
            return true;
        }

        // For all other objects, fall back to reference equality
        return left === right;
    }

    /**
     * Inequality comparison - negation of equals
     */
    static notEquals(left: any, right: any): boolean {
        return !this.equals(left, right);
    }

    /**
     * Create a Set from array items
     */
    static createSet(items: any[] = []): Set<any> {
        return new Set(items);
    }

    /**
     * Create a Map (dictionary) from key-value pairs
     */
    static createDict(pairs: [any, any][] = []): Map<any, any> {
        return new Map(pairs);
    }

    /**
     * Create an Array (list) from items
     */
    static createList(items: any[] = []): any[] {
        return [...items];
    }

    /**
     * Get type name of an object (Python-like type() function)
     */
    static getType(obj: any): string {
        if (obj === null) return 'NoneType';
        if (obj === undefined) return 'undefined';
        
        if (typeof obj === 'boolean') return 'bool';
        if (typeof obj === 'number') {
            return Number.isInteger(obj) ? 'int' : 'float';
        }
        if (typeof obj === 'string') return 'str';
        if (typeof obj === 'function') return 'function';
        
        if (Array.isArray(obj)) return 'list';
        if (obj instanceof Set) return 'set';
        if (obj instanceof Map) return 'dict';
        if (obj instanceof Date) return 'datetime';
        
        // For classes, try to get constructor name
        if (obj.constructor && obj.constructor.name) {
            return obj.constructor.name;
        }
        
        return 'object';
    }

    /**
     * Check if object is instance of type (Python-like isinstance)
     */
    static isinstance(obj: any, type: string): boolean {
        return this.getType(obj) === type;
    }

    /**
     * Python-like range function with multiple signatures
     */
    static range(start: number, stop?: number, step?: number): number[] {
        // range(stop) - start from 0
        if (stop === undefined) {
            stop = start;
            start = 0;
        }
        
        // Default step
        if (step === undefined) {
            step = 1;
        }
        
        // Validate step
        if (step === 0) {
            throw new Error('range() step argument must not be zero');
        }
        
        const result: number[] = [];
        
        if (step > 0) {
            for (let i = start; i < stop; i += step) {
                result.push(i);
            }
        } else {
            for (let i = start; i > stop; i += step) {
                result.push(i);
            }
        }
        
        return result;
    }

    /**
     * Get length of collections (Python-like len() function)
     */
    static len(obj: any): number {
        if (obj === null || obj === undefined) {
            throw new Error("object of type 'NoneType' has no len()");
        }
        
        if (typeof obj === 'string') return obj.length;
        if (Array.isArray(obj)) return obj.length;
        if (obj instanceof Set) return obj.size;
        if (obj instanceof Map) return obj.size;
        
        // Try .length property
        if ('length' in obj && typeof obj.length === 'number') {
            return obj.length;
        }
        
        // Try .size property
        if ('size' in obj && typeof obj.size === 'number') {
            return obj.size;
        }
        
        throw new Error(`object of type '${this.getType(obj)}' has no len()`);
    }

    /**
     * Convert iterable inputs to arrays for comprehension handling
     */
    static iterable(iterable: any): any[] {
        if (iterable === null || iterable === undefined) {
            return [];
        }

        if (Array.isArray(iterable)) {
            return iterable;
        }

        if (typeof iterable === 'string') {
            return Array.from(iterable);
        }

        if (iterable instanceof Set || iterable instanceof Map) {
            return Array.from(iterable);
        }

        if (typeof iterable[Symbol.iterator] === 'function') {
            return Array.from(iterable);
        }

        if (typeof iterable === 'object') {
            return Object.keys(iterable);
        }

        return [];
    }

    static jsonLoads(text: any): any {
        if (typeof text !== "string") {
            return text;
        }
        return JSON.parse(text);
    }

    static jsonDumps(value: any, replacer?: any, space?: any): string {
        return JSON.stringify(value, replacer, space);
    }

    static literalEval(text: any): any {
        if (typeof text !== "string") {
            return text;
        }

        let normalized = text.trim();
        // Replace Python-style literals with JSON equivalents
        normalized = normalized
            .replace(/\bTrue\b/g, "true")
            .replace(/\btrue\b/g, "true")
            .replace(/\bFalse\b/g, "false")
            .replace(/\bfalse\b/g, "false")
            .replace(/\bNone\b/g, "null");

        // Replace single quotes with double quotes for JSON parsing
        normalized = normalized.replace(/'/g, '"');

        // Convert simple tuple notation to arrays
        normalized = normalized.replace(/\(([^()]+)\)/g, '[$1]');

        try {
            return JSON.parse(normalized);
        } catch {
            throw new Error(`Failed to literal_eval: ${text}`);
        }
    }

    static sum(iterable: any, start: any = 0): any {
        let total = start;
        for (const value of FrameRuntime.iterable(iterable)) {
            total += value;
        }
        return total;
    }

    static any(iterable: any): boolean {
        for (const value of FrameRuntime.iterable(iterable)) {
            if (value) {
                return true;
            }
        }
        return false;
    }

    static all(iterable: any): boolean {
        for (const value of FrameRuntime.iterable(iterable)) {
            if (!value) {
                return false;
            }
        }
        return true;
    }
}

/**
 * Frame String Operations
 * Python-like string methods for TypeScript
 */
export class FrameString {
    private static patched = false;

    private static ensurePatched(): void {
        if (FrameString.patched) {
            return;
        }
        FrameString.patched = true;
        const proto = String.prototype as any;

        if (!proto.rfind) {
            proto.rfind = function (search: any, start?: any, end?: any) {
                return FrameString.rfind(String(this), search, start, end);
            };
        }
        if (!proto.upper) {
            proto.upper = function () {
                return FrameString.upper(String(this));
            };
        }
        if (!proto.lower) {
            proto.lower = function () {
                return FrameString.lower(String(this));
            };
        }
        if (!proto.find) {
            proto.find = function (search: any, start?: any, end?: any) {
                return FrameString.find(String(this), search, start, end);
            };
        }
        if (!proto.rindex) {
            proto.rindex = function (search: any, start?: any, end?: any) {
                const idx = FrameString.rfind(String(this), search, start, end);
                if (idx === -1) {
                    throw new Error("ValueError: substring not found");
                }
                return idx;
            };
        }
        if (!proto.index) {
            proto.index = function (search: any, start?: any, end?: any) {
                return FrameString.index(String(this), search, start, end);
            };
        }
        if (!proto.count) {
            proto.count = function (sub: any, start?: any, end?: any) {
                return FrameString.count(String(this), sub, start, end);
            };
        }
        if (!proto.startswith) {
            proto.startswith = function (prefix: any) {
                return FrameString.startswith(String(this), String(prefix));
            };
        }
        if (!proto.endswith) {
            proto.endswith = function (suffix: any) {
                return FrameString.endswith(String(this), String(suffix));
            };
        }
        if (!proto.splitlines) {
            proto.splitlines = function () {
                return FrameString.splitlines(String(this));
            };
        }
        if (!proto.partition) {
            proto.partition = function (sep: any) {
                return FrameString.partition(String(this), sep);
            };
        }
        if (!proto.rpartition) {
            proto.rpartition = function (sep: any) {
                return FrameString.rpartition(String(this), sep);
            };
        }
        if (!proto.rsplit) {
            proto.rsplit = function (sep?: any, maxsplit?: any) {
                return FrameString.rsplit(String(this), sep, maxsplit);
            };
        }
        if (!proto.center) {
            proto.center = function (width: any, fill?: any) {
                return FrameString.center(String(this), width, fill);
            };
        }
        if (!proto.ljust) {
            proto.ljust = function (width: any, fill?: any) {
                return FrameString.ljust(String(this), width, fill);
            };
        }
        if (!proto.rjust) {
            proto.rjust = function (width: any, fill?: any) {
                return FrameString.rjust(String(this), width, fill);
            };
        }
        if (!proto.zfill) {
            proto.zfill = function (width: any) {
                return FrameString.zfill(String(this), width);
            };
        }
        if (!proto.format) {
            proto.format = function (...values: any[]) {
                return FrameString.format(String(this), values);
            };
        }
        if (!proto.format_map) {
            proto.format_map = function (mapping: any) {
                return FrameString.formatMap(String(this), mapping);
            };
        }
        if (!proto.encode) {
            proto.encode = function (encoding?: any) {
                return FrameString.encode(String(this), encoding);
            };
        }
        if (!proto.expandtabs) {
            proto.expandtabs = function (tabsize?: any) {
                return FrameString.expandTabs(String(this), tabsize);
            };
        }
        if (!proto.strip) {
            proto.strip = function (chars?: any) {
                return FrameString.strip(String(this), chars);
            };
        }
        if (!proto.lstrip) {
            proto.lstrip = function (chars?: any) {
                return FrameString.lstrip(String(this), chars);
            };
        }
        if (!proto.rstrip) {
            proto.rstrip = function (chars?: any) {
                return FrameString.rstrip(String(this), chars);
            };
        }
        if (!proto.join) {
            proto.join = function (iterable: any) {
                return FrameString.join(String(this), iterable);
            };
        }
        if (!proto.title) {
            proto.title = function () {
                return FrameString.title(String(this));
            };
        }
        if (!proto.capitalize) {
            proto.capitalize = function () {
                return FrameString.capitalize(String(this));
            };
        }
        if (!proto.swapcase) {
            proto.swapcase = function () {
                return FrameString.swapcase(String(this));
            };
        }
        if (!proto.isdigit) {
            proto.isdigit = function () {
                return FrameString.isdigit(String(this));
            };
        }
        if (!proto.isalpha) {
            proto.isalpha = function () {
                return FrameString.isalpha(String(this));
            };
        }
        if (!proto.isalnum) {
            proto.isalnum = function () {
                return FrameString.isalnum(String(this));
            };
        }
        if (!proto.isspace) {
            proto.isspace = function () {
                return FrameString.isspace(String(this));
            };
        }
        if (!proto.islower) {
            proto.islower = function () {
                return FrameString.islower(String(this));
            };
        }
        if (!proto.isupper) {
            proto.isupper = function () {
                return FrameString.isupper(String(this));
            };
        }
        if (!proto.istitle) {
            proto.istitle = function () {
                return FrameString.istitle(String(this));
            };
        }
        if (!proto.isidentifier) {
            proto.isidentifier = function () {
                return FrameString.isidentifier(String(this));
            };
        }
    }

    static install(): void {
        FrameString.ensurePatched();
    }

    /**
     * String formatting (simplified version of Python .format())
     */
    static format(template: string, ...args: any[]): string {
        const values = args.length === 1 && Array.isArray(args[0]) ? args[0] : args;
        let result = template;
        for (const value of values) {
            result = result.replace(/\{[^{}]*\}/, String(value));
        }
        return result;
    }

    /**
     * Check if string starts with prefix
     */
    static startswith(str: string, prefix: string): boolean {
        return str.startsWith(prefix);
    }

    /**
     * Check if string ends with suffix
     */
    static endswith(str: string, suffix: string): boolean {
        return str.endsWith(suffix);
    }

    /**
     * Join array items with separator
     */
    static join(separator: string, items: any[]): string {
        return FrameRuntime.iterable(items).map(String).join(separator);
    }

    /**
     * Split string by separator
     */
    static split(str: string, separator?: string): string[] {
        if (separator === undefined) {
            // Python default: split on whitespace
            return str.trim().split(/\s+/).filter(s => s.length > 0);
        }
        return str.split(separator);
    }

    static rfind(str: string, search: string, start?: number, end?: number): number {
        let slice = str;
        if (start !== undefined || end !== undefined) {
            const s = start ?? 0;
            const e = end ?? str.length;
            slice = str.slice(s, e);
        }
        const index = slice.lastIndexOf(search);
        if (index === -1) {
            return -1;
        }
        return (start ?? 0) + index;
    }

    static find(str: string, search: string, start?: number, end?: number): number {
        let slice = str;
        if (start !== undefined || end !== undefined) {
            const s = start ?? 0;
            const e = end ?? str.length;
            slice = str.slice(s, e);
            const idx = slice.indexOf(search);
            if (idx === -1) {
                return -1;
            }
            return s + idx;
        }
        return str.indexOf(search);
    }

    static rindex(str: string, search: string, start?: number, end?: number): number {
        const idx = FrameString.rfind(str, search, start, end);
        if (idx === -1) {
            throw new Error("ValueError: substring not found");
        }
        return idx;
    }

    static index(str: string, search: string, start?: number, end?: number): number {
        let slice = str;
        if (start !== undefined || end !== undefined) {
            const s = start ?? 0;
            const e = end ?? str.length;
            slice = str.slice(s, e);
            const idx = slice.indexOf(search);
            if (idx === -1) {
                throw new Error("ValueError: substring not found");
            }
            return s + idx;
        }
        const idx = str.indexOf(search);
        if (idx === -1) {
            throw new Error("ValueError: substring not found");
        }
        return idx;
    }

    static count(str: string, sub: any, start?: number, end?: number): number {
        const subStr = String(sub);
        if (subStr.length === 0) {
            return 0;
        }
        let s = start ?? 0;
        let e = end ?? str.length;
        if (s < 0) {
            s = 0;
        }
        if (e > str.length) {
            e = str.length;
        }
        let count = 0;
        let pos = s;
        while (pos <= e - subStr.length) {
            const found = str.indexOf(subStr, pos);
            if (found === -1 || found >= e) {
                break;
            }
            count += 1;
            pos = found + subStr.length;
        }
        return count;
    }

    static splitlines(str: string): string[] {
        if (str.length === 0) {
            return [];
        }
        return str.split(/\r?\n|\r/);
    }

    static partition(str: string, sep: string): [string, string, string] {
        const idx = str.indexOf(sep);
        if (idx === -1) {
            return [str, '', ''];
        }
        return [str.slice(0, idx), sep, str.slice(idx + sep.length)];
    }

    static rpartition(str: string, sep: string): [string, string, string] {
        const idx = str.lastIndexOf(sep);
        if (idx === -1) {
            return ['', '', str];
        }
        return [str.slice(0, idx), sep, str.slice(idx + sep.length)];
    }

    static rsplit(str: string, sep?: string, maxsplit?: number): string[] {
        const splits = sep === undefined || sep === null
            ? str.trim().split(/\s+/)
            : str.split(sep);
        if (maxsplit === undefined || maxsplit <= 0) {
            return splits;
        }
        const result: string[] = [];
        let remaining = splits.slice();
        while (remaining.length > 0 && result.length < maxsplit) {
            result.unshift(remaining.pop() as string);
        }
        if (remaining.length > 0) {
            result.unshift(remaining.join(sep ?? ' '));
        }
        return result;
    }

    static center(str: string, width: number, fill: string = ' '): string {
        const pad = Math.max(0, width - str.length);
        const left = Math.floor(pad / 2);
        const right = pad - left;
        const filler = fill[0] ?? ' ';
        return filler.repeat(left) + str + filler.repeat(right);
    }

    static ljust(str: string, width: number, fill: string = ' '): string {
        const pad = Math.max(0, width - str.length);
        const filler = fill[0] ?? ' ';
        return str + filler.repeat(pad);
    }

    static rjust(str: string, width: number, fill: string = ' '): string {
        const pad = Math.max(0, width - str.length);
        const filler = fill[0] ?? ' ';
        return filler.repeat(pad) + str;
    }

    static zfill(str: string, width: number): string {
        const sign = str.startsWith('+') || str.startsWith('-') ? str[0] : '';
        const digits = sign ? str.slice(1) : str;
        const pad = Math.max(0, width - digits.length - (sign ? 1 : 0));
        return sign + '0'.repeat(pad) + digits;
    }

    static title(str: string): string {
        return str.replace(/([^\w]|^)([\w])/g, (_match, prefix, char) => prefix + String(char).toUpperCase())
                  .replace(/([^\w]|^)([\w]+)/g, (match) => {
                      const first = match.slice(0, 1);
                      return first.toUpperCase() + match.slice(1).toLowerCase();
                  });
    }

    static capitalize(str: string): string {
        if (str.length === 0) {
            return str;
        }
        return str[0].toUpperCase() + str.slice(1).toLowerCase();
    }

    static swapcase(str: string): string {
        return Array.from(str).map(ch => {
            if (ch >= 'a' && ch <= 'z') {
                return ch.toUpperCase();
            }
            if (ch >= 'A' && ch <= 'Z') {
                return ch.toLowerCase();
            }
            return ch;
        }).join('');
    }

    static isdigit(str: string): boolean {
        return str.length > 0 && /^[0-9]+$/.test(str);
    }

    static isalpha(str: string): boolean {
        return str.length > 0 && /^[A-Za-z]+$/.test(str);
    }

    static isalnum(str: string): boolean {
        return str.length > 0 && /^[A-Za-z0-9]+$/.test(str);
    }

    static isspace(str: string): boolean {
        return str.length > 0 && /^\s+$/.test(str);
    }

    static islower(str: string): boolean {
        const letters = str.match(/[A-Za-z]/g);
        if (!letters) {
            return false;
        }
        return letters.every(ch => ch === ch.toLowerCase());
    }

    static isupper(str: string): boolean {
        const letters = str.match(/[A-Za-z]/g);
        if (!letters) {
            return false;
        }
        return letters.every(ch => ch === ch.toUpperCase());
    }

    static istitle(str: string): boolean {
        if (str.length === 0) {
            return false;
        }
        const words = str.split(/\s+/);
        return words.every(word => word.length === 0 || (word[0] === word[0].toUpperCase() && word.slice(1) === word.slice(1).toLowerCase()));
    }

    static isidentifier(str: string): boolean {
        return /^[A-Za-z_][A-Za-z0-9_]*$/.test(str);
    }

    static formatMap(template: string, mapping: Record<string, any>): string {
        return template.replace(/\{([^{}]+)\}/g, (_match, key) => {
            if (mapping && Object.prototype.hasOwnProperty.call(mapping, key)) {
                return String(mapping[key]);
            }
            return `{${key}}`;
        });
    }

    static encode(str: string, encoding: string = 'utf-8'): any {
        if (typeof TextEncoder !== 'undefined' && encoding.toLowerCase() === 'utf-8') {
            return Array.from(new TextEncoder().encode(str));
        }
        // Fallback: return array of char codes
        return Array.from(str).map(ch => ch.charCodeAt(0));
    }

    static expandTabs(str: string, tabsize: number = 8): string {
        return str.replace(/\t/g, () => ' '.repeat(tabsize));
    }

    /**
     * Strip whitespace or specified characters
     */
    static strip(str: string, chars?: string): string {
        if (chars === undefined) {
            return str.trim();
        }

        // Escape special regex characters
        const escaped = chars.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
        const regex = new RegExp(`^[${escaped}]+|[${escaped}]+$`, 'g');
        return str.replace(regex, '');
    }

    static lstrip(str: string, chars?: string): string {
        if (chars === undefined) {
            return str.replace(/^\s+/, '');
        }
        const escaped = chars.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
        const regex = new RegExp(`^[${escaped}]+`, 'g');
        return str.replace(regex, '');
    }

    static rstrip(str: string, chars?: string): string {
        if (chars === undefined) {
            return str.replace(/\s+$/, '');
        }
        const escaped = chars.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
        const regex = new RegExp(`[${escaped}]+$`, 'g');
        return str.replace(regex, '');
    }

    /**
     * Convert to uppercase
     */
    static upper(str: string): string {
        return str.toUpperCase();
    }

    /**
     * Convert to lowercase
     */
    static lower(str: string): string {
        return str.toLowerCase();
    }

    /**
     * Multiply string (Python-like string * number)
     */
    static multiply(str: string, count: number): string {
        if (count <= 0) return '';
        return str.repeat(count);
    }
}

/**
 * Frame Collection Operations
 * Advanced collection methods for TypeScript
 */
export class FrameCollections {
    static defaultdict(factory: () => any): any {
        const resolvedFactory = factory ?? (() => undefined);
        const target: Record<string, any> = {};

        return new Proxy(target, {
            get: (storage, prop, receiver) => {
                if (prop === 'toJSON') {
                    return () => ({ ...storage });
                }
                if (prop === 'keys') {
                    return () => Object.keys(storage);
                }
                if (typeof prop === 'string') {
                    if (!Object.prototype.hasOwnProperty.call(storage, prop)) {
                        storage[prop] = resolvedFactory();
                    }
                    return storage[prop];
                }
                return Reflect.get(storage, prop, receiver);
            },
            set: (storage, prop, value) => {
                if (typeof prop === 'string') {
                    storage[prop] = value;
                    return true;
                }
                return false;
            },
            has: (storage, prop) => {
                if (typeof prop === 'string') {
                    return Object.prototype.hasOwnProperty.call(storage, prop);
                }
                return false;
            },
            ownKeys: (storage) => Reflect.ownKeys(storage),
            getOwnPropertyDescriptor: (storage, prop) => {
                if (typeof prop === 'string' && Object.prototype.hasOwnProperty.call(storage, prop)) {
                    return {
                        configurable: true,
                        enumerable: true,
                        value: storage[prop],
                        writable: true,
                    };
                }
                return undefined;
            }
        });
    }

    /**
     * Create dictionary from keys with default value
     */
    static dictFromKeys(keys: any[], defaultValue: any = null): Map<any, any> {
        const result = new Map();
        for (const key of keys) {
            result.set(key, defaultValue);
        }
        return result;
    }

    /**
     * Update dictionary with another dictionary
     */
    static dictUpdate(target: Map<any, any>, source: Map<any, any>): void {
        source.forEach((value, key) => {
            target.set(key, value);
        });
    }

    /**
     * Get value or set default if key doesn't exist
     */
    static dictSetDefault(dict: Map<any, any>, key: any, defaultValue: any): any {
        if (dict.has(key)) {
            return dict.get(key);
        }
        dict.set(key, defaultValue);
        return defaultValue;
    }

    /**
     * Set union operation
     */
    static setUnion(a: Set<any>, b: Set<any>): Set<any> {
        const result = new Set<any>();
        a.forEach(value => result.add(value));
        b.forEach(value => result.add(value));
        return result;
    }

    /**
     * Set intersection operation
     */
    static setIntersection(a: Set<any>, b: Set<any>): Set<any> {
        const result = new Set<any>();
        a.forEach(value => {
            if (b.has(value)) {
                result.add(value);
            }
        });
        return result;
    }

    /**
     * Set difference operation
     */
    static setDifference(a: Set<any>, b: Set<any>): Set<any> {
        const result = new Set<any>();
        a.forEach(value => {
            if (!b.has(value)) {
                result.add(value);
            }
        });
        return result;
    }

    /**
     * Extend array with another array (in-place)
     */
    static listExtend(target: any[], source: any): void {
        const items = FrameRuntime.iterable(source);
        target.push(...items);
    }

    /**
     * Insert item at specific index
     */
    static listInsert(list: any[], index: number, item: any): void {
        if (!Array.isArray(list)) {
            throw new Error("insert() requires a list");
        }
        const length = list.length;
        let position = Math.trunc(Number(index));
        if (!Number.isFinite(position)) {
            throw new Error("insert() index must be an integer");
        }
        if (position < 0) {
            position = Math.max(0, length + position);
        }
        if (position > length) {
            position = length;
        }
        list.splice(position, 0, item);
    }

    /**
     * Remove first occurrence of item
     */
    static listRemove(list: any[], item: any): boolean {
        if (!Array.isArray(list)) {
            throw new Error("remove() requires a list");
        }
        const index = list.findIndex(entry => FrameRuntime.equals(entry, item));
        if (index === -1) {
            throw new Error("ValueError: list.remove(x): x not in list");
        }
        list.splice(index, 1);
        return true;
    }

    static listClear(list: any[]): void {
        if (!Array.isArray(list)) {
            throw new Error("clear() requires a list");
        }
        list.splice(0, list.length);
    }

    static listPop(list: any[], index?: any): any {
        if (!Array.isArray(list)) {
            throw new Error("pop() requires a list");
        }
        if (list.length === 0) {
            throw new Error("IndexError: pop from empty list");
        }
        if (index === undefined) {
            return list.pop();
        }
        let position = Math.trunc(Number(index));
        if (!Number.isFinite(position)) {
            throw new Error("TypeError: slice indices must be integers or None");
        }
        if (position < 0) {
            position = list.length + position;
        }
        if (position < 0 || position >= list.length) {
            throw new Error("IndexError: pop index out of range");
        }
        const [value] = list.splice(position, 1);
        return value;
    }

    static listCount(list: any, item: any): number {
        if (typeof list === 'string') {
            return FrameString.count(list, item, 0, list.length);
        }
        const iterable = FrameRuntime.iterable(list);
        return iterable.reduce(
            (total: number, entry: any) =>
                FrameRuntime.equals(entry, item) ? total + 1 : total,
            0
        );
    }

    static listCopy(list: any[]): any[] {
        if (!Array.isArray(list)) {
            throw new Error("copy() requires a list");
        }
        return list.slice();
    }

    /**
     * Check if item is in collection (Python 'in' operator)
     */
    static contains(collection: any, item: any): boolean {
        if (typeof collection === 'string') {
            return collection.includes(item);
        }
        if (Array.isArray(collection)) {
            return collection.includes(item);
        }
        if (collection instanceof Set) {
            return collection.has(item);
        }
        if (collection instanceof Map) {
            return collection.has(item);
        }
        if (typeof collection === 'object' && collection !== null) {
            return item in collection;
        }
        return false;
    }
}

export class OrderedDict {
    constructor(initial?: any) {
        const data = { store: {} as Record<string, any>, order: [] as string[] };

        const ensureOrder = (key: string) => {
            if (!Object.prototype.hasOwnProperty.call(data.store, key)) {
                data.order.push(key);
            }
        };

        if (initial) {
            if (Array.isArray(initial)) {
                for (const [key, value] of initial) {
                    ensureOrder(key);
                    data.store[key] = value;
                }
            } else if (typeof initial === "object") {
                for (const key of Object.keys(initial)) {
                    ensureOrder(key);
                    data.store[key] = initial[key];
                }
            }
        }

        const proxy = new Proxy(data.store, {
            get: (target, prop, receiver) => {
                if (prop === "keys") {
                    return () => data.order.slice();
                }
                if (prop === "move_to_end") {
                    return (key: string, last: boolean = true) => {
                        const idx = data.order.indexOf(key);
                        if (idx === -1) {
                            return receiver;
                        }
                        data.order.splice(idx, 1);
                        if (last) {
                            data.order.push(key);
                        } else {
                            data.order.unshift(key);
                        }
                        return receiver;
                    };
                }
                if (prop === "toJSON") {
                    return () => {
                        const obj: Record<string, any> = {};
                        for (const key of data.order) {
                            obj[key] = target[key];
                        }
                        return obj;
                    };
                }
                if (typeof prop === "string") {
                    return target[prop];
                }
                return Reflect.get(target, prop, receiver);
            },
            set: (target, prop, value, receiver) => {
                if (typeof prop === "string") {
                    if (!Object.prototype.hasOwnProperty.call(target, prop)) {
                        data.order.push(prop);
                    }
                    target[prop] = value;
                    return true;
                }
                return Reflect.set(target, prop, value, receiver);
            },
            deleteProperty: (target, prop) => {
                if (typeof prop === "string") {
                    if (Object.prototype.hasOwnProperty.call(target, prop)) {
                        delete target[prop];
                        const idx = data.order.indexOf(prop);
                        if (idx >= 0) {
                            data.order.splice(idx, 1);
                        }
                    }
                    return true;
                }
                return false;
            },
            ownKeys: () => data.order.slice(),
            getOwnPropertyDescriptor: (target, prop) => {
                if (typeof prop === "string" && Object.prototype.hasOwnProperty.call(target, prop)) {
                    return {
                        configurable: true,
                        enumerable: true,
                        value: target[prop],
                        writable: true,
                    };
                }
                return undefined;
            }
        });

        ORDERED_DICT_STORE.set(proxy, data);
        return proxy as any;
    }
}

export class Counter {
    constructor(iterable?: any) {
        const store = new Map<string, number>();

        const addValue = (value: any, amount: number = 1) => {
            const key = FrameDict.normalizeKey(value);
            store.set(key, (store.get(key) ?? 0) + amount);
        };

        if (iterable !== undefined) {
            for (const value of FrameRuntime.iterable(iterable)) {
                addValue(value);
            }
        }

        const proxy = new Proxy({}, {
            get: (_target, prop, receiver) => {
                if (prop === "__store__") {
                    return store;
                }
                if (prop === "most_common") {
                    return (n?: any) => {
                        const limit = n === undefined ? store.size : Number(n);
                        return Array.from(store.entries())
                            .sort((a, b) => b[1] - a[1])
                            .slice(0, limit)
                            .map(([key, value]) => [key, value]);
                    };
                }
                if (prop === "update") {
                    return (iterable: any) => {
                        for (const value of FrameRuntime.iterable(iterable)) {
                            addValue(value);
                        }
                        return receiver;
                    };
                }
                if (prop === "toJSON") {
                    return () => {
                        const obj: Record<string, number> = {};
                        store.forEach((value, key) => {
                            obj[key] = value;
                        });
                        return obj;
                    };
                }
                if (typeof prop === "string") {
                    return store.get(prop) ?? 0;
                }
                return Reflect.get({}, prop, receiver);
            },
            set: (_target, prop, value) => {
                if (typeof prop === "string") {
                    store.set(prop, Number(value));
                    return true;
                }
                return false;
            },
            ownKeys: () => Array.from(store.keys()),
            getOwnPropertyDescriptor: (_target, prop) => {
                if (typeof prop === "string" && store.has(prop)) {
                    return {
                        configurable: true,
                        enumerable: true,
                        value: store.get(prop),
                        writable: true,
                    };
                }
                return undefined;
            }
        });

        COUNTER_STORE.set(proxy, store);
        return proxy as any;
    }

    static add(left: any, right: any): any {
        const result = new Counter();
        const targetStore = COUNTER_STORE.get(result) as Map<string, number>;

        const apply = (source: any) => {
            const store = COUNTER_STORE.get(source);
            if (store instanceof Map) {
                store.forEach((value, key) => {
                    targetStore.set(key, (targetStore.get(key) ?? 0) + value);
                });
            } else if (source && typeof source === "object") {
                for (const key of Object.keys(source)) {
                    const numeric = Number((source as any)[key]);
                    targetStore.set(key, (targetStore.get(key) ?? 0) + numeric);
                }
            }
        };

        apply(left);
        apply(right);
        return result;
    }

    static update(counter: any, iterable: any): any {
        const store = COUNTER_STORE.get(counter);
        if (!(store instanceof Map)) {
            return counter;
        }
        for (const value of FrameRuntime.iterable(iterable)) {
            const key = FrameDict.normalizeKey(value);
            store.set(key, (store.get(key) ?? 0) + 1);
        }
        return counter;
    }

    static mostCommon(counter: any, n?: any): any[] {
        const store = COUNTER_STORE.get(counter);
        if (!(store instanceof Map)) {
            return [];
        }
        const limit = n === undefined ? store.size : Number(n);
        return Array.from(store.entries())
            .sort((a, b) => b[1] - a[1])
            .slice(0, limit)
            .map(([key, value]) => [key, value]);
    }
}

export class ChainMap {
    constructor(...maps: any[]) {
        const chain = maps.map((map) => (map ? map : {}));

        const proxy = new Proxy({}, {
            get: (_target, prop, receiver) => {
                if (prop === "maps") {
                    return chain;
                }
                if (prop === "new_child") {
                    return (map: any = {}) => new ChainMap(map, ...chain);
                }
                if (typeof prop === "string") {
                    for (const mapping of chain) {
                        if (Object.prototype.hasOwnProperty.call(mapping, prop)) {
                            return mapping[prop];
                        }
                    }
                    return undefined;
                }
                return Reflect.get({}, prop, receiver);
            },
            set: (_target, prop, value) => {
                if (typeof prop === "string") {
                    chain[0][prop] = value;
                    return true;
                }
                return false;
            },
            has: (_target, prop) => {
                if (typeof prop === "string") {
                    return chain.some(mapping => Object.prototype.hasOwnProperty.call(mapping, prop));
                }
                return false;
            },
            ownKeys: () => {
                const keys = new Set<string>();
                for (const mapping of chain) {
                    for (const key of Object.keys(mapping)) {
                        keys.add(key);
                    }
                }
                return Array.from(keys);
            },
            getOwnPropertyDescriptor: (_target, prop) => {
                if (typeof prop === "string") {
                    return {
                        configurable: true,
                        enumerable: true,
                        value: chain[0][prop],
                        writable: true,
                    };
                }
                return undefined;
            }
        });

        CHAINMAP_STORE.set(proxy, chain);
        return proxy as any;
    }
}

FrameString.install();

export class FrameMath {
    private static toArray(value: any): any[] {
        if (Array.isArray(value)) {
            return value;
        }
        if (value instanceof Set) {
            return Array.from(value);
        }
        if (value instanceof Map) {
            return Array.from(value.values());
        }
        if (value && typeof value[Symbol.iterator] === "function") {
            return Array.from(value as Iterable<any>);
        }
        return [value];
    }

    static get pi(): number {
        return Math.PI;
    }

    static round(value: any, ndigits?: any): number {
        const num = Number(value);
        if (!Number.isFinite(num)) {
            throw new Error("round() argument must be a finite number");
        }

        if (ndigits === undefined) {
            return Math.round(num);
        }

        const digits = Number(ndigits);
        if (!Number.isFinite(digits)) {
            throw new Error("round() precision must be a finite integer");
        }

        const factor = Math.pow(10, digits);
        return Math.round(num * factor + Number.EPSILON) / factor;
    }

    static min(first: any, ...rest: any[]): any {
        const values = rest.length === 0 ? this.toArray(first) : [first, ...rest];
        if (values.length === 0) {
            throw new Error("min() arg is an empty sequence");
        }
        return values.reduce((best, value) => (best <= value ? best : value));
    }

    static max(first: any, ...rest: any[]): any {
        const values = rest.length === 0 ? this.toArray(first) : [first, ...rest];
        if (values.length === 0) {
            throw new Error("max() arg is an empty sequence");
        }
        return values.reduce((best, value) => (best >= value ? best : value));
    }
}

export class FrameDict {
    static normalizeKey(key: any): string {
        if (key === null) {
            return "null";
        }
        if (key === undefined) {
            return "undefined";
        }
        if (typeof key === "object") {
            try {
                const custom = key.toString();
                if (typeof custom === "string" && custom !== "[object Object]") {
                    return custom;
                }
            } catch {
                // Fall through to String conversion
            }
        }
        return String(key);
    }

    private static assignEntries(target: any, entries: any): any {
        if (!entries) {
            return target;
        }

        if (entries instanceof Map) {
            entries.forEach((value, key) => {
                target[FrameDict.normalizeKey(key)] = value;
            });
            return FrameDict.ensureMethods(target);
        }

        if (Array.isArray(entries) || typeof entries[Symbol.iterator] === "function") {
            for (const entry of Array.from(entries as Iterable<any>)) {
                if (!Array.isArray(entry)) {
                    throw new Error("dict() expected iterable of key/value pairs");
                }
                const [key, value] = entry;
                target[FrameDict.normalizeKey(key)] = value;
            }
            return FrameDict.ensureMethods(target);
        }

        if (typeof entries === "object") {
            for (const [key, value] of Object.entries(entries)) {
                target[FrameDict.normalizeKey(key)] = value;
            }
            return FrameDict.ensureMethods(target);
        }

        throw new Error("Unsupported dictionary source");
    }

    private static ensureMethods(dict: any): any {
        if (dict && typeof dict === 'object') {
            if (typeof dict.keys !== 'function') {
                Object.defineProperty(dict, 'keys', {
                    value: () => Object.keys(dict),
                    enumerable: false,
                });
            }
            if (typeof dict.values !== 'function') {
                Object.defineProperty(dict, 'values', {
                    value: () => Object.keys(dict).map(key => dict[key]),
                    enumerable: false,
                });
            }
            if (typeof dict.items !== 'function') {
                Object.defineProperty(dict, 'items', {
                    value: () => Object.keys(dict).map(key => [key, dict[key]]),
                    enumerable: false,
                });
            }
        }
        return dict;
    }

    private static isDictLike(value: any): value is Record<string, any> {
        return (
            value !== null &&
            typeof value === "object" &&
            !Array.isArray(value) &&
            !(value instanceof Date) &&
            !(value instanceof Set) &&
            !(value instanceof Map)
        );
    }

    static get(dict: any, key: any, defaultValue: any = undefined): any {
        if (!dict) {
            return defaultValue;
        }
        const normalizedKey = FrameDict.normalizeKey(key);
        if (Object.prototype.hasOwnProperty.call(dict, normalizedKey)) {
            const value = dict[normalizedKey];
            return value === undefined ? defaultValue : value;
        }
        return defaultValue;
    }

    static setdefault(dict: any, key: any, defaultValue: any = null): any {
        if (!dict) {
            throw new Error("setdefault() requires a dictionary");
        }
        const normalizedKey = FrameDict.normalizeKey(key);
        if (!Object.prototype.hasOwnProperty.call(dict, normalizedKey)) {
            dict[normalizedKey] = defaultValue;
            return defaultValue;
        }
        return dict[normalizedKey];
    }

    static update(target: any, ...sources: any[]): any {
        if (!target) {
            return target;
        }
        for (const source of sources) {
            if (!source) {
                continue;
            }
            FrameDict.assignEntries(target, source);
        }
        return target;
    }

    static fromKeys(keys: any, value: any = null): any {
        const result: any = {};
        if (!keys) {
            return FrameDict.ensureMethods(result);
        }
        for (const key of FrameRuntime.iterable(keys)) {
            result[FrameDict.normalizeKey(key)] = value;
        }
        return FrameDict.ensureMethods(result);
    }

    static fromEntries(entries: any): any {
        const result: any = {};
        return FrameDict.assignEntries(result, entries);
    }

    static union(...dicts: any[]): any {
        const result: any = {};
        for (const dict of dicts) {
            FrameDict.update(result, dict);
        }
        return result;
    }

    static unionDynamic(left: any, right: any): any {
        if (typeof left === "number" && typeof right === "number") {
            return left | right;
        }

        if (typeof left === "bigint" && typeof right === "bigint") {
            return left | right;
        }

        if (left instanceof Map && right instanceof Map) {
            const result = new Map(left);
            right.forEach((value, key) => {
                result.set(key, value);
            });
            return result;
        }

        if (FrameDict.isDictLike(left) || FrameDict.isDictLike(right)) {
            const result: any = {};
            if (FrameDict.isDictLike(left)) {
                FrameDict.assignEntries(result, left);
            }
            if (FrameDict.isDictLike(right)) {
                FrameDict.assignEntries(result, right);
            }
            return result;
        }

        throw new Error("Unsupported operands for dictionary union");
    }
}
