/**
 * Frame TypeScript Runtime Library
 * 
 * Provides Frame-semantic implementations for TypeScript/JavaScript
 * that differ from Python behavior, enabling consistent Frame execution
 * across target languages.
 * 
 * Generated by Frame Transpiler v0.86.13
 */

export class FrameRuntime {
    /**
     * Deep equality comparison for Frame semantics
     * Handles Sets, Maps, Arrays, Objects with proper content comparison
     * Falls back to === for primitives
     */
    static equals(left: any, right: any): boolean {
        // Handle null/undefined cases
        if (left === null || left === undefined || right === null || right === undefined) {
            return left === right;
        }

        // Handle primitive types - use strict equality
        if (typeof left !== 'object' || typeof right !== 'object') {
            return left === right;
        }

        // Handle Set comparison
        if (left instanceof Set && right instanceof Set) {
            if (left.size !== right.size) return false;
            for (const item of left) {
                if (!right.has(item)) return false;
            }
            return true;
        }

        // Handle Map comparison  
        if (left instanceof Map && right instanceof Map) {
            if (left.size !== right.size) return false;
            for (const [key, value] of left) {
                if (!right.has(key) || !this.equals(right.get(key), value)) {
                    return false;
                }
            }
            return true;
        }

        // Handle Array comparison
        if (Array.isArray(left) && Array.isArray(right)) {
            if (left.length !== right.length) return false;
            for (let i = 0; i < left.length; i++) {
                if (!this.equals(left[i], right[i])) return false;
            }
            return true;
        }

        // Handle Object comparison (plain objects)
        if (left.constructor === Object && right.constructor === Object) {
            const leftKeys = Object.keys(left);
            const rightKeys = Object.keys(right);
            if (leftKeys.length !== rightKeys.length) return false;
            
            for (const key of leftKeys) {
                if (!(key in right) || !this.equals(left[key], right[key])) {
                    return false;
                }
            }
            return true;
        }

        // For all other objects, fall back to reference equality
        return left === right;
    }

    /**
     * Inequality comparison - negation of equals
     */
    static notEquals(left: any, right: any): boolean {
        return !this.equals(left, right);
    }

    /**
     * Create a Set from array items
     */
    static createSet(items: any[] = []): Set<any> {
        return new Set(items);
    }

    /**
     * Create a Map (dictionary) from key-value pairs
     */
    static createDict(pairs: [any, any][] = []): Map<any, any> {
        return new Map(pairs);
    }

    /**
     * Create an Array (list) from items
     */
    static createList(items: any[] = []): any[] {
        return [...items];
    }

    /**
     * Get type name of an object (Python-like type() function)
     */
    static getType(obj: any): string {
        if (obj === null) return 'NoneType';
        if (obj === undefined) return 'undefined';
        
        if (typeof obj === 'boolean') return 'bool';
        if (typeof obj === 'number') {
            return Number.isInteger(obj) ? 'int' : 'float';
        }
        if (typeof obj === 'string') return 'str';
        if (typeof obj === 'function') return 'function';
        
        if (Array.isArray(obj)) return 'list';
        if (obj instanceof Set) return 'set';
        if (obj instanceof Map) return 'dict';
        if (obj instanceof Date) return 'datetime';
        
        // For classes, try to get constructor name
        if (obj.constructor && obj.constructor.name) {
            return obj.constructor.name;
        }
        
        return 'object';
    }

    /**
     * Check if object is instance of type (Python-like isinstance)
     */
    static isinstance(obj: any, type: string): boolean {
        return this.getType(obj) === type;
    }

    /**
     * Python-like range function with multiple signatures
     */
    static range(start: number, stop?: number, step?: number): number[] {
        // range(stop) - start from 0
        if (stop === undefined) {
            stop = start;
            start = 0;
        }
        
        // Default step
        if (step === undefined) {
            step = 1;
        }
        
        // Validate step
        if (step === 0) {
            throw new Error('range() step argument must not be zero');
        }
        
        const result: number[] = [];
        
        if (step > 0) {
            for (let i = start; i < stop; i += step) {
                result.push(i);
            }
        } else {
            for (let i = start; i > stop; i += step) {
                result.push(i);
            }
        }
        
        return result;
    }

    /**
     * Get length of collections (Python-like len() function)
     */
    static len(obj: any): number {
        if (obj === null || obj === undefined) {
            throw new Error("object of type 'NoneType' has no len()");
        }
        
        if (typeof obj === 'string') return obj.length;
        if (Array.isArray(obj)) return obj.length;
        if (obj instanceof Set) return obj.size;
        if (obj instanceof Map) return obj.size;
        
        // Try .length property
        if ('length' in obj && typeof obj.length === 'number') {
            return obj.length;
        }
        
        // Try .size property
        if ('size' in obj && typeof obj.size === 'number') {
            return obj.size;
        }
        
        throw new Error(`object of type '${this.getType(obj)}' has no len()`);
    }
}

/**
 * Frame String Operations
 * Python-like string methods for TypeScript
 */
export class FrameString {
    /**
     * String formatting (simplified version of Python .format())
     */
    static format(template: string, ...args: any[]): string {
        let result = template;
        for (let i = 0; i < args.length; i++) {
            result = result.replace(new RegExp(`\\{${i}\\}`, 'g'), String(args[i]));
        }
        return result;
    }

    /**
     * Check if string starts with prefix
     */
    static startswith(str: string, prefix: string): boolean {
        return str.startsWith(prefix);
    }

    /**
     * Check if string ends with suffix
     */
    static endswith(str: string, suffix: string): boolean {
        return str.endsWith(suffix);
    }

    /**
     * Join array items with separator
     */
    static join(separator: string, items: any[]): string {
        return items.map(String).join(separator);
    }

    /**
     * Split string by separator
     */
    static split(str: string, separator?: string): string[] {
        if (separator === undefined) {
            // Python default: split on whitespace
            return str.trim().split(/\s+/).filter(s => s.length > 0);
        }
        return str.split(separator);
    }

    /**
     * Strip whitespace or specified characters
     */
    static strip(str: string, chars?: string): string {
        if (chars === undefined) {
            return str.trim();
        }
        
        // Escape special regex characters
        const escaped = chars.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
        const regex = new RegExp(`^[${escaped}]+|[${escaped}]+$`, 'g');
        return str.replace(regex, '');
    }

    /**
     * Convert to uppercase
     */
    static upper(str: string): string {
        return str.toUpperCase();
    }

    /**
     * Convert to lowercase
     */
    static lower(str: string): string {
        return str.toLowerCase();
    }

    /**
     * Multiply string (Python-like string * number)
     */
    static multiply(str: string, count: number): string {
        if (count <= 0) return '';
        return str.repeat(count);
    }
}

/**
 * Frame Collection Operations
 * Advanced collection methods for TypeScript
 */
export class FrameCollections {
    /**
     * Create dictionary from keys with default value
     */
    static dictFromKeys(keys: any[], defaultValue: any = null): Map<any, any> {
        const result = new Map();
        for (const key of keys) {
            result.set(key, defaultValue);
        }
        return result;
    }

    /**
     * Update dictionary with another dictionary
     */
    static dictUpdate(target: Map<any, any>, source: Map<any, any>): void {
        for (const [key, value] of source) {
            target.set(key, value);
        }
    }

    /**
     * Get value or set default if key doesn't exist
     */
    static dictSetDefault(dict: Map<any, any>, key: any, defaultValue: any): any {
        if (dict.has(key)) {
            return dict.get(key);
        }
        dict.set(key, defaultValue);
        return defaultValue;
    }

    /**
     * Set union operation
     */
    static setUnion(a: Set<any>, b: Set<any>): Set<any> {
        return new Set([...a, ...b]);
    }

    /**
     * Set intersection operation
     */
    static setIntersection(a: Set<any>, b: Set<any>): Set<any> {
        return new Set([...a].filter(x => b.has(x)));
    }

    /**
     * Set difference operation
     */
    static setDifference(a: Set<any>, b: Set<any>): Set<any> {
        return new Set([...a].filter(x => !b.has(x)));
    }

    /**
     * Extend array with another array (in-place)
     */
    static listExtend(target: any[], source: any[]): void {
        target.push(...source);
    }

    /**
     * Insert item at specific index
     */
    static listInsert(list: any[], index: number, item: any): void {
        list.splice(index, 0, item);
    }

    /**
     * Remove first occurrence of item
     */
    static listRemove(list: any[], item: any): boolean {
        const index = list.indexOf(item);
        if (index !== -1) {
            list.splice(index, 1);
            return true;
        }
        return false;
    }

    /**
     * Check if item is in collection (Python 'in' operator)
     */
    static contains(collection: any, item: any): boolean {
        if (typeof collection === 'string') {
            return collection.includes(item);
        }
        if (Array.isArray(collection)) {
            return collection.includes(item);
        }
        if (collection instanceof Set) {
            return collection.has(item);
        }
        if (collection instanceof Map) {
            return collection.has(item);
        }
        if (typeof collection === 'object' && collection !== null) {
            return item in collection;
        }
        return false;
    }
}

export class FrameMath {
    private static toArray(value: any): any[] {
        if (Array.isArray(value)) {
            return value;
        }
        if (value instanceof Set) {
            return Array.from(value);
        }
        if (value instanceof Map) {
            return Array.from(value.values());
        }
        if (value && typeof value[Symbol.iterator] === "function") {
            return Array.from(value as Iterable<any>);
        }
        return [value];
    }

    static get pi(): number {
        return Math.PI;
    }

    static round(value: any, ndigits?: any): number {
        const num = Number(value);
        if (!Number.isFinite(num)) {
            throw new Error("round() argument must be a finite number");
        }

        if (ndigits === undefined) {
            return Math.round(num);
        }

        const digits = Number(ndigits);
        if (!Number.isFinite(digits)) {
            throw new Error("round() precision must be a finite integer");
        }

        const factor = Math.pow(10, digits);
        return Math.round(num * factor + Number.EPSILON) / factor;
    }

    static min(first: any, ...rest: any[]): any {
        const values = rest.length === 0 ? this.toArray(first) : [first, ...rest];
        if (values.length === 0) {
            throw new Error("min() arg is an empty sequence");
        }
        return values.reduce((best, value) => (best <= value ? best : value));
    }

    static max(first: any, ...rest: any[]): any {
        const values = rest.length === 0 ? this.toArray(first) : [first, ...rest];
        if (values.length === 0) {
            throw new Error("max() arg is an empty sequence");
        }
        return values.reduce((best, value) => (best >= value ? best : value));
    }
}
