// {{language_name}} Visitor for Frame Language Transpiler
// Generates {{language_name}} code from Frame AST using visitor pattern
// Auto-generated by Frame Transpiler Visitor Generator v{{version}}

{{#imports}}
{{.}}
{{/imports}}

use crate::frame_c::ast::*;
use crate::frame_c::code_builder::CodeBuilder;
use crate::frame_c::config::FrameConfig;
use crate::frame_c::scanner::{Token};
use crate::frame_c::symbol_table::{SymbolConfig, Arcanum};
use crate::frame_c::visitors::AstVisitor;

use std::collections::{HashMap, HashSet};

{{#if has_config}}
#[derive(Debug, Clone)]
pub struct {{config_name}} {
    {{#config_fields}}
    pub {{name}}: {{type}},
    {{/config_fields}}
}

impl Default for {{config_name}} {
    fn default() -> Self {
        Self {
            {{#config_defaults}}
            {{name}}: {{value}},
            {{/config_defaults}}
        }
    }
}
{{/if}}

pub struct {{visitor_name}} {
    // Core configuration
    config: FrameConfig,
    {{#if has_language_config}}
    {{language_snake}}_config: {{config_name}},
    {{/if}}
    
    // Code generation
    builder: CodeBuilder,
    
    // Symbol tracking
    symbol_config: SymbolConfig,
    arcanum: Vec<Arcanum>,
    
    // Current context
    current_state_name_opt: Option<String>,
    current_state_parent_opt: Option<String>,
    current_event_ret_type: String,
    current_class_name_opt: Option<String>,
    
    // System metadata
    system_name: String,
    system_has_async_runtime: bool,
    interface_methods: HashMap<String, InterfaceMethodSignature>,
    domain_variables: HashMap<String, String>, // name -> type
    current_handler_params: HashMap<String, String>, // param -> type
    current_state_params: HashMap<String, String>,
    action_signatures: HashMap<String, ActionSignature>,
    operation_signatures: HashMap<String, OperationSignature>,
    
    // State tracking
    states: Vec<String>,
    state_events: HashMap<String, Vec<String>>, // state -> event names
    
    // Type tracking
    declared_types: HashSet<String>,
    imported_types: HashSet<String>,
    
    // Generation flags
    is_generating_interface_method: bool,
    is_generating_action: bool,
    is_generating_operation: bool,
    
    // Comments (for future use)
    _comments: Vec<Token>,
}

#[derive(Debug, Clone)]
struct InterfaceMethodSignature {
    name: String,
    parameters: Vec<(String, String)>, // (name, type)
    return_type: Option<String>,
}

#[derive(Debug, Clone)]
struct ActionSignature {
    name: String,
    parameters: Vec<(String, String)>,
}

#[derive(Debug, Clone)]
struct OperationSignature {
    name: String,
    parameters: Vec<(String, String)>,
    return_type: Option<String>,
}

impl {{visitor_name}} {
    pub fn new(
        arcanum: Vec<Arcanum>,
        symbol_config: SymbolConfig,
        config: FrameConfig,
        comments: Vec<Token>,
    ) -> Self {
        Self {
            config,
            {{#if has_language_config}}
            {{language_snake}}_config: {{config_name}}::default(),
            {{/if}}
            builder: CodeBuilder::new("{{indent}}"),
            symbol_config,
            arcanum,
            current_state_name_opt: None,
            current_state_parent_opt: None,
            current_event_ret_type: String::new(),
            current_class_name_opt: None,
            system_name: String::new(),
            system_has_async_runtime: false,
            interface_methods: HashMap::new(),
            domain_variables: HashMap::new(),
            current_handler_params: HashMap::new(),
            current_state_params: HashMap::new(),
            action_signatures: HashMap::new(),
            operation_signatures: HashMap::new(),
            states: Vec::new(),
            state_events: HashMap::new(),
            declared_types: HashSet::new(),
            imported_types: HashSet::new(),
            is_generating_interface_method: false,
            is_generating_action: false,
            is_generating_operation: false,
            _comments: comments,
        }
    }
    
    {{#if has_thread_safe}}
    /// Create a new {{language_name}} visitor with thread-safe configuration
    pub fn new_thread_safe(
        arcanum: Vec<Arcanum>,
        symbol_config: SymbolConfig,
        config: FrameConfig,
        comments: Vec<Token>,
    ) -> Self {
        let mut visitor = Self::new(arcanum, symbol_config, config, comments);
        {{#thread_safe_config}}
        visitor.{{language_snake}}_config.{{field}} = {{value}};
        {{/thread_safe_config}}
        visitor
    }
    {{/if}}
    
    pub fn run(mut self, frame_module: &FrameModule) -> String {
        // Visit the module and generate {{language_name}} code
        for system in &frame_module.systems {
            system.accept(&mut self);
        }
        
        self.builder.build().0  // CodeBuilder returns (String, Vec<SourceMapping>), we want just the String
    }
    
    // Frame type to {{language_name}} type mapping
    fn frame_type_to_{{language_snake}}(&self, frame_type: &str) -> String {
        match frame_type {
            {{#type_mappings}}
            "{{frame_type}}" => "{{target_type}}".to_string(),
            {{/type_mappings}}
            _ => {
                {{#generic_type_handling}}
                {{.}}
                {{/generic_type_handling}}
            }
        }
    }
    
    // Generate {{language_name}} imports and dependencies
    fn generate_imports(&mut self) {
        {{#base_imports}}
        self.builder.writeln("{{.}}");
        {{/base_imports}}
        
        {{#if has_conditional_imports}}
        {{#conditional_imports}}
        if {{condition}} {
            {{#imports}}
            self.builder.writeln("{{.}}");
            {{/imports}}
        }
        {{/conditional_imports}}
        {{/if}}
        
        self.builder.writeln("");
    }
    
    {{#helper_methods}}
    {{.}}
    {{/helper_methods}}
}

impl AstVisitor for {{visitor_name}} {
    fn visit_system_node(&mut self, node: &SystemNode) {
        self.system_name = node.name.clone();
        self.current_class_name_opt = Some(node.name.clone());
        
        // Generate file header and imports
        self.generate_imports();
        
        // First pass: collect metadata
        if let Some(domain) = &node.domain_block_node_opt {
            self.collect_domain_variables(domain);
        }
        
        if let Some(machine) = &node.machine_block_node_opt {
            // Collect states
            for state_rcref in &machine.states {
                let state_node = state_rcref.borrow();
                self.states.push(state_node.name.clone());
            }
        }
        
        // Generate type definitions
        {{#type_generation_calls}}
        self.{{method_name}}();
        {{/type_generation_calls}}
        
        // Generate implementation
        {{#system_generation}}
        {{.}}
        {{/system_generation}}
        
        // Visit blocks in order
        if let Some(interface) = &node.interface_block_node_opt {
            self.visit_interface_block_node(interface);
        }
        
        if let Some(machine) = &node.machine_block_node_opt {
            self.visit_machine_block_node(machine);
        }
        
        if let Some(actions) = &node.actions_block_node_opt {
            self.visit_actions_block_node(actions);
        }
        
        if let Some(operations) = &node.operations_block_node_opt {
            self.visit_operations_block_node(operations);
        }
        
        {{#system_generation_end}}
        {{.}}
        {{/system_generation_end}}
    }
    
    {{#visitor_methods}}
    {{.}}
    {{/visitor_methods}}
}