[package]
name = "frame_build"
version = "0.11.7"
authors = ["Eric Walkingshaw <eric.walkingshaw@savant.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
framec = { path = "../framec" }
walkdir = "2.3"
