# Generated by Frame Transpiler v0.66
# Multi-module Frame program

#Emitted from framec_v0.76.1

# Frame runtime classes
class FrameEvent:
    def __init__(self, message, parameters):
        self._message = message
        self._parameters = parameters

class FrameCompartment:
    def __init__(self, state, forward_event=None, exit_args=None, enter_args=None, parent_compartment=None, state_vars=None, state_args=None):
        self.state = state
        self.forward_event = forward_event
        self.exit_args = exit_args
        self.enter_args = enter_args
        self.parent_compartment = parent_compartment
        self.state_vars = state_vars or {}
        self.state_args = state_args or {}

# Module: /Users/marktruluck/projects/frame_transpiler/framec_tests/python/src/positive_tests/multifile/complex_app/./test_multifile_formatters.frm
#==================================================


def formatNumber(value):
    return str(round(value * 100) / 100.0)

def parseNumber(text):
    return float(text)

def formatCurrency(amount):
    return "$" + formatNumber(amount)

def formatPercentage(value):
    return str(round(value * 100)) + "%"
# Module: /Users/marktruluck/projects/frame_transpiler/framec_tests/python/src/positive_tests/multifile/complex_app/./test_multifile_strings.frm
#==================================================


class StringModule:
    @staticmethod
    def createGreeting(name):
        return "Hello, " + name + "! Welcome to Frame v0.57"
    
    @staticmethod
    def reverseString(text):
        result = ""
        i = len(text) - 1
        while i >= 0:
            result = result + text[i]
            i = i - 1
        return result
    
    @staticmethod
    def uppercase(text):
        return text.upper()
    
    @staticmethod
    def lowercase(text):
        return text.lower()
# Module: /Users/marktruluck/projects/frame_transpiler/framec_tests/python/src/positive_tests/multifile/complex_app/./test_multifile_math.frm
#==================================================


class MathModule:
    @staticmethod
    def add(a,b):
        return a + b
    
    @staticmethod
    def multiply(a,b):
        return a * b
    
    @staticmethod
    def power(base,exponent):
        result = 1
        counter = 0
        while counter < exponent:
            result = result * base
            counter = counter + 1
        return result
    
    @staticmethod
    def subtract(a,b):
        return a - b
    
    @staticmethod
    def divide(a,b):
        if b == 0:
            return 0
        return a / b
# Module: /Users/marktruluck/projects/frame_transpiler/framec_tests/python/src/positive_tests/multifile/complex_app/test_multifile_complex.frm
#==================================================

def main():
    calc = ComplexCalculator()
    sum = calc.calculate("add",10,5)
    print("10 + 5 = " + calc.formatResult(sum))
    product = calc.calculate("multiply",7,8)
    print("7 * 8 = " + calc.formatResult(product))
    power = calc.calculate("power",2,8)
    print("2 ^ 8 = " + calc.formatResult(power))
    greeting = StringModule.createGreeting("Frame")
    print(greeting)
    reversed = StringModule.reverseString("Hello")
    print("Reversed: " + reversed)
    formatted = formatNumber(3.14159)
    print("Formatted PI: " + formatted)
    parsed = parseNumber("42.5")
    print("Parsed: " + str(parsed))
    return
class ComplexCalculator:
    
    def __init__(self):
        # Create and initialize start state compartment
        self.__compartment = FrameCompartment('__complexcalculator_state_Ready', None, None, None, None, {}, {})
        self.__next_compartment = None
        self.return_stack = [None]
        
        # Send system start event
        frame_event = FrameEvent("$>", None)
        self.__kernel(frame_event)
    # ==================== Interface Block ================== #
    
    def calculate(self,operation,a,b):
        parameters = {}
        parameters["operation"] = operation
        parameters["a"] = a
        parameters["b"] = b
        self.return_stack.append(None)
        __e = FrameEvent("calculate",parameters)
        self.__kernel(__e)
        return self.return_stack.pop(-1)
    
    def formatResult(self,value):
        parameters = {}
        parameters["value"] = value
        self.return_stack.append(None)
        __e = FrameEvent("formatResult",parameters)
        self.__kernel(__e)
        return self.return_stack.pop(-1)
    
    # ===================== Machine Block =================== #
    
    def __handle_ready_calculate(self, __e, compartment):
        if __e._parameters["operation"] == "add":
            self.return_stack[-1] = MathModule.add(__e._parameters["a"],__e._parameters["b"])
        elif __e._parameters["operation"] == "multiply":
            self.return_stack[-1] = MathModule.multiply(__e._parameters["a"],__e._parameters["b"])
        elif __e._parameters["operation"] == "power":
            self.return_stack[-1] = MathModule.power(__e._parameters["a"],__e._parameters["b"])
        else:
            self.return_stack[-1] = 0
        return
    
    def __handle_ready_formatResult(self, __e, compartment):
        self.return_stack[-1] = formatNumber(__e._parameters["value"])
        return
    
    # ----------------------------------------
    # $Ready
    
    def __complexcalculator_state_Ready(self, __e, compartment):
        if __e._message == "calculate":
            return self.__handle_ready_calculate(__e, compartment)
        elif __e._message == "formatResult":
            return self.__handle_ready_formatResult(__e, compartment)
        
    # ===================== State Dispatchers =================== #
    
    def _sReady(self, __e):
        return self.__complexcalculator_state_Ready(__e, None)
    
    # ==================== System Runtime =================== #
    
    def __kernel(self, __e):
        # send event to current state
        self.__router(__e)
        
        # loop until no transitions occur
        while self.__next_compartment != None:
            next_compartment = self.__next_compartment
            self.__next_compartment = None
            
            # exit current state
            self.__router(FrameEvent("<$", self.__compartment.exit_args))
            # change state
            self.__compartment = next_compartment
            
            if next_compartment.forward_event is None:
                # send normal enter event
                self.__router(FrameEvent("$>", self.__compartment.enter_args))
            else:
                # forwarded event
                if next_compartment.forward_event._message == "$>":
                    self.__router(next_compartment.forward_event)
                else:
                    self.__router(FrameEvent("$>", self.__compartment.enter_args))
                    self.__router(next_compartment.forward_event)
                next_compartment.forward_event = None
    
    def __router(self, __e, compartment=None):
        target_compartment = compartment or self.__compartment
        if target_compartment.state == '__complexcalculator_state_Ready':
            self.__complexcalculator_state_Ready(__e, target_compartment)
    
    def __transition(self, next_compartment):
        self.__next_compartment = next_compartment

if __name__ == '__main__':
    main()
# Module initialization


# End of multi-file Frame program

