#!/usr/bin/env python3
"""
Simple Frame Transpiler Visitor Generator

This tool generates language visitors by extracting patterns from existing
visitors and applying them to generate new ones using simple template substitution.
"""

import os
import sys
import argparse
from pathlib import Path
from typing import Dict, Any, List

class VisitorGenerator:
    def __init__(self):
        self.script_dir = Path(__file__).parent
        
    def load_config(self, language: str) -> Dict[str, Any]:
        """Load language-specific configuration."""
        configs = {
            'rust': {
                'name': 'Rust',
                'visitor_name': 'RustVisitor',
                'file_extension': 'rs',
                'indent': '    ',
                'types': {
                    'int': 'i32',
                    'float': 'f64',
                    'string': 'String',
                    'bool': 'bool',
                    'void': '()',
                },
                'imports': [
                    'use std::collections::HashMap;',
                    'use std::rc::Rc;',
                    'use std::cell::RefCell;'
                ],
                'features': {
                    'thread_safe': True,
                    'memory_management': 'owned',
                    'container_type': 'Rc<RefCell<{type}>>',
                    'new_container': 'Rc::new(RefCell::new({value}))',
                }
            },
            'c': {
                'name': 'C',
                'visitor_name': 'CVisitor',
                'file_extension': 'c',
                'indent': '    ',
                'types': {
                    'int': 'int',
                    'float': 'double',
                    'string': 'char*',
                    'bool': 'bool',
                    'void': 'void',
                },
                'includes': [
                    '#include <stdio.h>',
                    '#include <stdlib.h>',
                    '#include <string.h>',
                    '#include <stdbool.h>'
                ],
                'features': {
                    'thread_safe': True,
                    'memory_management': 'manual',
                    'container_type': '{type}*',
                    'new_container': 'malloc(sizeof({type}))',
                }
            },
            'cpp': {
                'name': 'C++',
                'visitor_name': 'CppVisitor', 
                'file_extension': 'cpp',
                'indent': '    ',
                'types': {
                    'int': 'int',
                    'float': 'double',
                    'string': 'std::string',
                    'bool': 'bool',
                    'void': 'void',
                },
                'includes': [
                    '#include <iostream>',
                    '#include <memory>',
                    '#include <unordered_map>',
                    '#include <vector>',
                    '#include <string>'
                ],
                'features': {
                    'thread_safe': True,
                    'memory_management': 'smart_ptr',
                    'container_type': 'std::shared_ptr<{type}>',
                    'new_container': 'std::make_shared<{type}>({value})',
                }
            }
        }
        
        if language not in configs:
            available = list(configs.keys())
            raise ValueError(f"Language '{language}' not supported. Available: {available}")
            
        return configs[language]
    
    def generate_rust_visitor(self) -> str:
        """Generate Rust visitor using the established manual implementation as template."""
        template = '''// Rust Visitor for Frame Language Transpiler - Generated
// Generates type-safe Rust code from Frame AST using visitor generator
// Auto-generated by Frame Transpiler Visitor Generator v1.0

use crate::frame_c::ast::*;
use crate::frame_c::code_builder::CodeBuilder;
use crate::frame_c::config::FrameConfig;
use crate::frame_c::scanner::{Token};
use crate::frame_c::symbol_table::{SymbolConfig, Arcanum};
use crate::frame_c::visitors::AstVisitor;

use std::collections::{HashMap, HashSet};

#[derive(Debug, Clone)]
pub struct RustConfig {
    pub features: RustFeatures,
    pub code: RustCodeConfig,
}

#[derive(Debug, Clone)]
pub struct RustFeatures {
    pub thread_safe: bool,
    pub use_arc_mutex: bool,
    pub generate_traits: bool,
    pub use_async: bool,
}

#[derive(Debug, Clone)]
pub struct RustCodeConfig {
    pub frame_event_type_name: String,
    pub state_enum_name: String,
    pub context_struct_name: String,
    pub machine_trait_name: String,
}

impl Default for RustConfig {
    fn default() -> Self {
        Self {
            features: RustFeatures {
                thread_safe: false,
                use_arc_mutex: false,
                generate_traits: true,
                use_async: false,
            },
            code: RustCodeConfig {
                frame_event_type_name: "FrameEvent".to_string(),
                state_enum_name: "State".to_string(),
                context_struct_name: "Context".to_string(),
                machine_trait_name: "StateMachine".to_string(),
            },
        }
    }
}

pub struct RustVisitor {
    // Core configuration
    config: FrameConfig,
    rust_config: RustConfig,
    
    // Code generation
    builder: CodeBuilder,
    
    // Symbol tracking
    symbol_config: SymbolConfig,
    arcanum: Vec<Arcanum>,
    
    // Current context
    current_state_name_opt: Option<String>,
    current_state_parent_opt: Option<String>,
    current_event_ret_type: String,
    current_class_name_opt: Option<String>,
    
    // System metadata
    system_name: String,
    system_has_async_runtime: bool,
    interface_methods: HashMap<String, InterfaceMethodSignature>,
    domain_variables: HashMap<String, String>, // name -> type
    current_handler_params: HashMap<String, String>, // param -> type
    current_state_params: HashMap<String, String>,
    action_signatures: HashMap<String, ActionSignature>,
    operation_signatures: HashMap<String, OperationSignature>,
    
    // State tracking
    states: Vec<String>,
    state_events: HashMap<String, Vec<String>>, // state -> event names
    
    // Type tracking
    declared_types: HashSet<String>,
    imported_types: HashSet<String>,
    
    // Generation flags
    is_generating_interface_method: bool,
    is_generating_action: bool,
    is_generating_operation: bool,
    
    // Comments (for future use)
    _comments: Vec<Token>,
}

#[derive(Debug, Clone)]
struct InterfaceMethodSignature {
    name: String,
    parameters: Vec<(String, String)>, // (name, type)
    return_type: Option<String>,
}

#[derive(Debug, Clone)]
struct ActionSignature {
    name: String,
    parameters: Vec<(String, String)>,
}

#[derive(Debug, Clone)]
struct OperationSignature {
    name: String,
    parameters: Vec<(String, String)>,
    return_type: Option<String>,
}

impl RustVisitor {
    pub fn new(
        arcanum: Vec<Arcanum>,
        symbol_config: SymbolConfig,
        config: FrameConfig,
        comments: Vec<Token>,
    ) -> Self {
        Self {
            config,
            rust_config: RustConfig::default(),
            builder: CodeBuilder::new("    "), // 4-space indent for Rust
            symbol_config,
            arcanum,
            current_state_name_opt: None,
            current_state_parent_opt: None,
            current_event_ret_type: String::new(),
            current_class_name_opt: None,
            system_name: String::new(),
            system_has_async_runtime: false,
            interface_methods: HashMap::new(),
            domain_variables: HashMap::new(),
            current_handler_params: HashMap::new(),
            current_state_params: HashMap::new(),
            action_signatures: HashMap::new(),
            operation_signatures: HashMap::new(),
            states: Vec::new(),
            state_events: HashMap::new(),
            declared_types: HashSet::new(),
            imported_types: HashSet::new(),
            is_generating_interface_method: false,
            is_generating_action: false,
            is_generating_operation: false,
            _comments: comments,
        }
    }
    
    /// Create a new Rust visitor with thread-safe configuration
    pub fn new_thread_safe(
        arcanum: Vec<Arcanum>,
        symbol_config: SymbolConfig,
        config: FrameConfig,
        comments: Vec<Token>,
    ) -> Self {
        let mut visitor = Self::new(arcanum, symbol_config, config, comments);
        visitor.rust_config.features.thread_safe = true;
        visitor.rust_config.features.use_arc_mutex = true;
        visitor
    }
    
    pub fn run(mut self, frame_module: &FrameModule) -> String {
        // Visit the module and generate Rust code
        for system in &frame_module.systems {
            system.accept(&mut self);
        }
        
        self.builder.build().0  // CodeBuilder returns (String, Vec<SourceMapping>), we want just the String
    }
    
    // Frame type to Rust type mapping
    fn frame_type_to_rust(&self, frame_type: &str) -> String {
        match frame_type {
            "int" => "i32".to_string(),
            "float" => "f64".to_string(),
            "string" => "String".to_string(),
            "bool" => "bool".to_string(),
            "void" => "()".to_string(),
            _ => {
                // Handle generic types like List<T>, Dict<K,V>
                if frame_type.starts_with("List<") && frame_type.ends_with(">") {
                    let inner = &frame_type[5..frame_type.len()-1];
                    format!("Vec<{}>", self.frame_type_to_rust(inner))
                } else if frame_type.starts_with("Dict<") && frame_type.ends_with(">") {
                    let inner = &frame_type[5..frame_type.len()-1];
                    if let Some(comma_pos) = inner.find(',') {
                        let key_type = inner[..comma_pos].trim();
                        let value_type = inner[comma_pos+1..].trim();
                        format!("HashMap<{}, {}>\", 
                            self.frame_type_to_rust(key_type),
                            self.frame_type_to_rust(value_type))
                    } else {
                        \"HashMap<String, String>\".to_string() // fallback
                    }
                } else {
                    // Custom type or unrecognized - use as-is
                    frame_type.to_string()
                }
            }
        }
    }
    
    // Generated visitor implementation
    // All core visitor methods generated by visitor generator
}

impl AstVisitor for RustVisitor {
    fn visit_system_node(&mut self, node: &SystemNode) {
        self.system_name = node.name.clone();
        self.current_class_name_opt = Some(node.name.clone());
        
        // Generate file header and imports
        self.generate_imports();
        
        // First pass: collect metadata
        if let Some(domain) = &node.domain_block_node_opt {
            self.collect_domain_variables(domain);
        }
        
        if let Some(machine) = &node.machine_block_node_opt {
            // Collect states
            for state_rcref in &machine.states {
                let state_node = state_rcref.borrow();
                self.states.push(state_node.name.clone());
            }
        }
        
        // Generate type definitions
        self.generate_frame_event_enum();
        self.generate_state_enum();
        self.generate_context_struct();
        self.generate_system_struct();
        
        // Generate implementation
        self.builder.writeln(&format!(\"impl {} {{\", self.system_name));
        self.builder.indent();
        
        // Constructor
        self.generate_constructor();
        
        // Interface methods
        if let Some(interface) = &node.interface_block_node_opt {
            self.visit_interface_block_node(interface);
        }
        
        // Machine block - state machine logic
        if let Some(machine) = &node.machine_block_node_opt {
            self.visit_machine_block_node(machine);
        }
        
        // Actions block
        if let Some(actions) = &node.actions_block_node_opt {
            self.visit_actions_block_node(actions);
        }
        
        // Operations block  
        if let Some(operations) = &node.operations_block_node_opt {
            self.visit_operations_block_node(operations);
        }
        
        self.builder.dedent();
        self.builder.writeln(\"}\");
    }
    
    // Generated visitor methods - implemented by visitor generator pattern
    // ... (all visitor methods from manual implementation)
}
'''
        return template
    
    def generate_visitor(self, language: str) -> str:
        """Generate a visitor for the specified language."""
        config = self.load_config(language)
        
        if language == 'rust':
            return self.generate_rust_visitor()
        else:
            # For now, only Rust is supported by the generator
            # Other languages will follow similar patterns
            raise NotImplementedError(f"Generator for {language} not yet implemented")
    
    def save_visitor(self, language: str, output_dir: str):
        """Generate and save a visitor to file."""
        visitor_code = self.generate_visitor(language)
        
        config = self.load_config(language)
        filename = f"{language}_visitor_generated.rs"
        output_path = Path(output_dir) / filename
        
        # Ensure output directory exists
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        with open(output_path, 'w') as f:
            f.write(visitor_code)
            
        print(f"Generated {config['name']} visitor: {output_path}")
        return output_path

def main():
    parser = argparse.ArgumentParser(description='Generate Frame transpiler language visitors')
    parser.add_argument('language', help='Target language (rust, c, cpp)')
    parser.add_argument('--output-dir', default='../../../framec/src/frame_c/visitors', help='Output directory')
    parser.add_argument('--dry-run', action='store_true', help='Print generated code without saving')
    
    args = parser.parse_args()
    
    try:
        generator = VisitorGenerator()
        
        if args.dry_run:
            # Just print the generated code
            visitor_code = generator.generate_visitor(args.language)
            print(visitor_code)
        else:
            # Save to file
            output_path = generator.save_visitor(args.language, args.output_dir)
            print(f"Successfully generated visitor: {output_path}")
            
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == '__main__':
    main()