// Module linker for Frame v0.57
// Combines multiple compiled modules into final output

use std::collections::HashMap;
use super::errors::{ModuleResult};
use super::compiler::CompiledModule;

/// Module linker that combines compiled modules
pub struct ModuleLinker {
    /// Modules in dependency order
    modules: Vec<CompiledModule>,
    
    /// Linking strategy to use
    strategy: LinkingStrategy,
    
    /// Symbol resolution table
    symbol_table: HashMap<String, String>,
}

/// Strategy for linking modules together
#[derive(Debug, Clone)]
pub enum LinkingStrategy {
    /// Simple concatenation in dependency order
    Concatenation,
    
    /// Future: Smart linking with dead code elimination
    Optimized {
        dead_code_elimination: bool,
        inline_small_functions: bool,
        bundle_modules: bool,
    },
}

/// Result of the linking process
#[derive(Debug)]
pub struct LinkResult {
    /// Final generated code
    pub code: String,
    
    /// Linking statistics
    pub stats: LinkStats,
    
    /// Any warnings generated during linking
    pub warnings: Vec<String>,
}

/// Statistics about the linking process
#[derive(Debug)]
pub struct LinkStats {
    pub modules_linked: usize,
    pub total_lines: usize,
    pub total_functions: usize,
    pub total_systems: usize,
    pub total_classes: usize,
}

impl ModuleLinker {
    /// Create a new module linker with specified strategy
    pub fn new(strategy: LinkingStrategy) -> Self {
        Self {
            modules: Vec::new(),
            strategy,
            symbol_table: HashMap::new(),
        }
    }
    
    /// Add a compiled module to the linker
    pub fn add_module(&mut self, module: CompiledModule) {
        self.modules.push(module);
    }
    
    /// Link all modules together
    pub fn link(&mut self, modules: Vec<CompiledModule>) -> ModuleResult<String> {
        // Add all modules
        for module in modules {
            self.add_module(module);
        }
        
        // Perform linking based on strategy
        match &self.strategy {
            LinkingStrategy::Concatenation => self.link_concatenation(),
            LinkingStrategy::Optimized { .. } => self.link_optimized(),
        }
    }
    
    /// Simple concatenation linking
    fn link_concatenation(&mut self) -> ModuleResult<String> {
        use crate::frame_c::visitors::python_visitor::PythonVisitor;
        use crate::frame_c::config::FrameConfig;
        
        let mut output = String::new();
        let mut warnings: Vec<String> = Vec::new();
        
        // Add header comments
        output.push_str("# Generated by Frame Transpiler v0.57\n");
        output.push_str("# Multi-module Frame program\n\n");
        
        // Generate code for each module using PythonVisitor
        let config = FrameConfig::default();
        let framec_version = "Emitted from framec_v0.57.0";
        
        // Collect all generated code first
        let mut module_codes = Vec::new();
        
        // We need to move modules out to get ownership of Arcanum
        let modules = std::mem::take(&mut self.modules);
        for module in modules {
            // Create a visitor for this module
            let mut visitor = PythonVisitor::new(
                module.symbols,  // Move the Arcanum
                false, // generate_state_stack
                false, // generate_change_state
                framec_version,
                Vec::new(), // comments
                config.clone(),
            );
            
            // Generate code for this module
            visitor.run_v2(&module.ast);
            let module_code = visitor.get_code();
            
            module_codes.push((module.file_path.clone(), module_code));
        }
        
        // First module gets the full output with runtime
        if let Some((path, code)) = module_codes.first() {
            output.push_str(&format!("# Module: {}\n", path.display()));
            output.push_str(&format!("#{}\n\n", "=".repeat(50)));
            output.push_str(code);
        }
        
        // Subsequent modules: extract just their unique code
        for (path, code) in module_codes.iter().skip(1) {
            output.push_str(&format!("\n\n# Module: {}\n", path.display()));
            output.push_str(&format!("#{}\n\n", "=".repeat(50)));
            
            // For now, just append the generated code
            // TODO: Smart merging to avoid duplicate runtime classes
            output.push_str(code);
        }
        
        // Add footer
        output.push_str("\n\n# End of multi-file Frame program\n");
        
        Ok(output)
    }
    
    /// Optimized linking with dead code elimination (future)
    fn link_optimized(&mut self) -> ModuleResult<String> {
        // For now, fall back to concatenation
        // TODO: Implement proper optimization passes
        self.link_concatenation()
    }
    
    /// Generate common imports needed by all modules
    fn generate_common_imports(&self) -> String {
        let mut imports = String::new();
        
        // Standard imports for Frame runtime
        imports.push_str("# Frame runtime imports\n");
        imports.push_str("from enum import Enum\n");
        imports.push_str("import json\n");
        imports.push_str("import sys\n");
        
        // Add any Frame-specific runtime classes
        imports.push_str("\n# Frame runtime classes\n");
        imports.push_str(self.generate_frame_runtime().as_str());
        
        imports.push_str("\n");
        imports
    }
    
    /// Generate Frame runtime helper classes
    fn generate_frame_runtime(&self) -> String {
        r#"
class FrameEvent:
    def __init__(self, message, parameters):
        self._message = message
        self._parameters = parameters
        self._return = None

class FrameCompartment:
    def __init__(self, state):
        self._state = state
        self._state_args = {}
        self._state_vars = {}
        self.parent_compartment = None

"#.to_string()
    }
    
    /// Build global symbol resolution table
    fn build_symbol_table(&mut self) -> ModuleResult<()> {
        self.symbol_table.clear();
        
        for module in &self.modules {
            // Access the Arcanum symbols directly (no borrow needed)
            // Arcanum is not RefCell wrapped in CompiledModule
            
            // Add module prefix to all symbols
            let module_path_str = module.file_path.to_string_lossy();
            let _module_prefix = self.get_module_prefix(&module_path_str);
            
            // TODO: Extract symbols from module and add to global table
            // This will be implemented when we have proper symbol extraction
        }
        
        Ok(())
    }
    
    /// Get a unique prefix for a module
    fn get_module_prefix(&self, module_path: &str) -> String {
        // Convert path to a valid Python identifier
        module_path
            .replace("/", "_")
            .replace("\\", "_")
            .replace(".", "_")
            .replace("::", "_")
    }
    
    /// Detect and report symbol conflicts
    fn check_symbol_conflicts(&self) -> ModuleResult<Vec<String>> {
        let mut conflicts = Vec::new();
        let symbol_sources: HashMap<String, Vec<String>> = HashMap::new();
        
        // Collect all exported symbols from each module
        for _module in &self.modules {
            // Access symbols directly from Arcanum (no borrow needed)
            // TODO: Extract actual symbols and check for conflicts
            // This will be implemented when we have proper symbol extraction
        }
        
        // Find conflicts (symbols defined in multiple modules)
        for (symbol, sources) in symbol_sources {
            if sources.len() > 1 {
                conflicts.push(format!(
                    "Symbol '{}' defined in multiple modules: {}",
                    symbol,
                    sources.join(", ")
                ));
            }
        }
        
        Ok(conflicts)
    }
    
    /// Get linking statistics
    pub fn get_stats(&self) -> LinkStats {
        let mut total_lines = 0;
        let mut total_functions = 0;
        let mut total_systems = 0;
        let mut total_classes = 0;
        
        for module in &self.modules {
            // TODO: Count lines when we have generated code
            // For now, estimate based on AST size
            total_lines += module.ast.functions.len() * 10; // Rough estimate
            
            // Count declarations in AST
            total_functions += module.ast.functions.len();
            total_systems += module.ast.systems.len();
            total_classes += module.ast.classes.len();
        }
        
        LinkStats {
            modules_linked: self.modules.len(),
            total_lines,
            total_functions,
            total_systems,
            total_classes,
        }
    }
    
    /// Clear all modules (useful for reuse)
    pub fn clear(&mut self) {
        self.modules.clear();
        self.symbol_table.clear();
    }
    
    /// Get module count
    pub fn module_count(&self) -> usize {
        self.modules.len()
    }
    
    /// Check if linker has any modules
    pub fn is_empty(&self) -> bool {
        self.modules.is_empty()
    }
}

impl Default for LinkingStrategy {
    fn default() -> Self {
        Self::Concatenation
    }
}