// Module linker for Frame v0.66
// Combines multiple compiled modules into final output

use super::compiler::CompiledModule;
use super::errors::{ModuleError, ModuleErrorKind, ModuleResult};
use crate::frame_c::visitors::TargetLanguage;
use std::collections::{HashMap, HashSet};
use std::fs;
use std::path::{Path, PathBuf};

/// Module linker that combines compiled modules
pub struct ModuleLinker {
    /// Modules in dependency order
    modules: Vec<CompiledModule>,

    /// Linking strategy to use
    strategy: LinkingStrategy,

    /// Target language for code generation
    target_language: TargetLanguage,

    /// Symbol resolution table
    symbol_table: HashMap<String, String>,
}

/// Strategy for linking modules together
#[derive(Debug, Clone)]
pub enum LinkingStrategy {
    /// Simple concatenation in dependency order
    Concatenation,

    /// Generate separate files for each module
    SeparateFiles {
        output_dir: std::path::PathBuf,
        create_package: bool, // Whether to create __init__.py
    },

    /// Future: Smart linking with dead code elimination
    Optimized {
        dead_code_elimination: bool,
        inline_small_functions: bool,
        bundle_modules: bool,
    },
}

/// Result of the linking process
#[derive(Debug)]
pub struct LinkResult {
    /// Final generated code
    pub code: String,

    /// Linking statistics
    pub stats: LinkStats,

    /// Any warnings generated during linking
    pub warnings: Vec<String>,
}

/// Statistics about the linking process
#[derive(Debug)]
pub struct LinkStats {
    pub modules_linked: usize,
    pub total_lines: usize,
    pub total_functions: usize,
    pub total_systems: usize,
    pub total_classes: usize,
}

impl ModuleLinker {
    /// Create a new module linker with specified strategy and target language
    pub fn new(strategy: LinkingStrategy, target_language: TargetLanguage) -> Self {
        Self {
            modules: Vec::new(),
            strategy,
            target_language,
            symbol_table: HashMap::new(),
        }
    }

    /// Add a compiled module to the linker
    pub fn add_module(&mut self, module: CompiledModule) {
        self.modules.push(module);
    }

    /// Link all modules together
    pub fn link(&mut self, modules: Vec<CompiledModule>) -> ModuleResult<String> {
        // Add all modules
        for module in modules {
            self.add_module(module);
        }

        // Perform linking based on strategy
        match self.strategy.clone() {
            LinkingStrategy::Concatenation => self.link_concatenation(),
            LinkingStrategy::SeparateFiles {
                output_dir,
                create_package,
            } => self.link_separate_files(&output_dir, create_package),
            LinkingStrategy::Optimized { .. } => self.link_optimized(),
        }
    }

    /// Simple concatenation linking with optimization
    fn link_concatenation(&mut self) -> ModuleResult<String> {
        use crate::frame_c::config::FrameConfig;

        let mut output = String::new();
        let mut _warnings: Vec<String> = Vec::new();

        // Add header comments based on target language
        match self.target_language {
            TargetLanguage::Python3 => {
                output.push_str("# Generated by Frame Transpiler v0.83\n");
                output.push_str("# Multi-module Frame program\n\n");
            }
            TargetLanguage::TypeScript => {
                output.push_str("// Generated by Frame Transpiler v0.83\n");
                output.push_str("// Multi-module Frame program\n\n");
            }
            _ => {
                // Default to language-neutral comments
                output.push_str("// Generated by Frame Transpiler v0.83\n");
                output.push_str("// Multi-module Frame program\n\n");
            }
        }

        // Generate code for each module using language-specific visitor
        let config = FrameConfig::default();
        let framec_version = "Emitted from framec_v0.83.3";

        // Collect all generated code first
        let mut module_codes = Vec::new();
        let mut all_imports = HashSet::new();

        // We need to move modules out to get ownership of Arcanum
        let modules = std::mem::take(&mut self.modules);
        for module in modules {
            // Generate code based on target language
            let module_code = match self.target_language {
                TargetLanguage::Python3 => {
                    use crate::frame_c::visitors::python_visitor::PythonVisitor;
                    let mut visitor = PythonVisitor::new(
                        module.symbols, // Move the Arcanum
                        false,          // generate_state_stack
                        false,          // generate_change_state
                        framec_version,
                        Vec::new(), // comments
                        config.clone(),
                    );
                    visitor.run_v2(&module.ast);
                    visitor.get_code()
                }
                TargetLanguage::TypeScript => {
                    use crate::frame_c::symbol_table::SymbolConfig;
                    use crate::frame_c::visitors::typescript_visitor::TypeScriptVisitor;

                    let arcanum_vec = vec![module.symbols];
                    let visitor =
                        TypeScriptVisitor::new_for_multifile(arcanum_vec, SymbolConfig::new());
                    visitor.run(&module.ast)
                }
                _ => {
                    return Err(ModuleError::new(
                        ModuleErrorKind::InvalidPath {
                            path: "target_language".to_string(),
                            reason: format!(
                                "Multi-file compilation not supported for target language: {:?}",
                                self.target_language
                            ),
                        },
                        String::new(),
                    ));
                }
            };

            // Extract imports from this module's code
            self.extract_imports(&module_code, &mut all_imports);

            module_codes.push((module.file_path.clone(), module_code));
        }

        // Extract the framec version from first module
        let framec_version = if let Some((_, first_code)) = module_codes.first() {
            match self.target_language {
                TargetLanguage::Python3 => {
                    if let Some(line) = first_code
                        .lines()
                        .find(|l| l.starts_with("#Emitted from framec"))
                    {
                        line.to_string()
                    } else {
                        "#Emitted from framec_v0.83.3".to_string()
                    }
                }
                TargetLanguage::TypeScript => {
                    if let Some(line) = first_code
                        .lines()
                        .find(|l| l.starts_with("// Emitted from framec"))
                    {
                        line.to_string()
                    } else {
                        "// Emitted from framec_v0.83.3".to_string()
                    }
                }
                _ => "// Emitted from framec_v0.83.3".to_string(),
            }
        } else {
            match self.target_language {
                TargetLanguage::Python3 => "#Emitted from framec_v0.83.3".to_string(),
                _ => "// Emitted from framec_v0.83.3".to_string(),
            }
        };

        // Add version comment
        output.push_str(&framec_version);
        output.push_str("\n\n");

        // Generate consolidated imports at the top
        if !all_imports.is_empty() {
            output.push_str(&self.generate_consolidated_imports(&all_imports));
            output.push_str("\n");
        }

        // Generate Frame runtime classes once
        output.push_str(&self.generate_single_runtime());
        output.push_str("\n");

        // Now add each module's unique code (without imports and runtime)
        for (index, (path, code)) in module_codes.iter().enumerate() {
            if index > 0 {
                output.push_str("\n");
            }
            match self.target_language {
                TargetLanguage::Python3 => {
                    output.push_str(&format!("# Module: {}\n", path.display()));
                    output.push_str(&format!("#{}\n\n", "=".repeat(50)));
                }
                TargetLanguage::TypeScript => {
                    output.push_str(&format!("// Module: {}\n", path.display()));
                    output.push_str(&format!("//{}\n\n", "=".repeat(50)));
                }
                _ => {
                    output.push_str(&format!("// Module: {}\n", path.display()));
                    output.push_str(&format!("//{}\n\n", "=".repeat(50)));
                }
            }

            // Filter out imports, runtime classes, and framec version comment
            let filtered_code = self.filter_module_code(code);
            output.push_str(&filtered_code);
        }

        // Add main execution guard if there's a main function (Python only)
        if self.target_language == TargetLanguage::Python3 && self.has_main_function(&module_codes)
        {
            output.push_str("\n# Module initialization\n");
            output.push_str("\n");
            // Look for any top-level function calls (but not if already in main guard)
            for (_, code) in &module_codes {
                if let Some(main_call) = self.extract_main_call(code) {
                    // Check if this is already inside a main guard
                    if !code.contains("if __name__ == '__main__':") {
                        output.push_str(&main_call);
                        output.push_str("\n\n");
                    }
                    break;
                }
            }
            // Only add main guard if we didn't find one already
            if !output.contains("if __name__ == '__main__':") {
                output.push_str("\nif __name__ == '__main__':\n");
                output.push_str("    main()\n");
            }
        }

        // Add footer based on target language
        match self.target_language {
            TargetLanguage::Python3 => {
                output.push_str("\n# End of multi-file Frame program\n");
            }
            TargetLanguage::TypeScript => {
                output.push_str("\n// End of multi-file Frame program\n");
            }
            _ => {
                output.push_str("\n// End of multi-file Frame program\n");
            }
        }

        Ok(output)
    }

    /// Extract import statements from module code based on target language
    fn extract_imports(&self, code: &str, imports: &mut HashSet<String>) {
        for line in code.lines() {
            let trimmed = line.trim();

            match self.target_language {
                TargetLanguage::Python3 => {
                    if trimmed.starts_with("import ") || trimmed.starts_with("from ") {
                        // Skip Frame import comments
                        if !trimmed.starts_with("# Frame import:") {
                            imports.insert(trimmed.to_string());
                        }
                    }
                }
                TargetLanguage::TypeScript => {
                    // Only extract import statements, not export class declarations
                    if trimmed.starts_with("import ") && !trimmed.starts_with("// Frame import:") {
                        imports.insert(trimmed.to_string());
                    }
                }
                _ => {
                    // Default to JavaScript-style imports
                    if trimmed.starts_with("import ") || trimmed.starts_with("export ") {
                        imports.insert(trimmed.to_string());
                    }
                }
            }
        }
    }

    /// Generate consolidated import section based on target language
    fn generate_consolidated_imports(&self, imports: &HashSet<String>) -> String {
        let mut output = String::new();

        match self.target_language {
            TargetLanguage::Python3 => {
                output.push_str("# Consolidated imports\n");
            }
            TargetLanguage::TypeScript => {
                output.push_str("// Consolidated imports\n");
            }
            _ => {
                output.push_str("// Consolidated imports\n");
            }
        }

        // Sort imports for consistent output
        let mut sorted_imports: Vec<String> = imports.iter().cloned().collect();
        sorted_imports.sort();

        for import in sorted_imports {
            output.push_str(&import);
            output.push('\n');
        }

        output
    }

    /// Generate Frame runtime classes once based on target language
    fn generate_single_runtime(&self) -> String {
        let mut output = String::new();

        match self.target_language {
            TargetLanguage::Python3 => {
                output.push_str("# Frame runtime classes\n");
                output.push_str("class FrameEvent:\n");
                output.push_str("    def __init__(self, message, parameters):\n");
                output.push_str("        self._message = message\n");
                output.push_str("        self._parameters = parameters\n");
                output.push_str("\n");
                output.push_str("class FrameCompartment:\n");
                output.push_str("    def __init__(self, state, forward_event=None, exit_args=None, enter_args=None, parent_compartment=None, state_vars=None, state_args=None):\n");
                output.push_str("        self.state = state\n");
                output.push_str("        self.forward_event = forward_event\n");
                output.push_str("        self.exit_args = exit_args\n");
                output.push_str("        self.enter_args = enter_args\n");
                output.push_str("        self.parent_compartment = parent_compartment\n");
                output.push_str("        self.state_vars = state_vars or {}\n");
                output.push_str("        self.state_args = state_args or {}\n");
            }
            TargetLanguage::TypeScript => {
                // Generate Frame runtime classes once for multifile TypeScript
                output.push_str("// Frame runtime classes (embedded for standalone compilation)\n");
                output.push_str("interface FrameEventParameters { [key: string]: any; }\n");
                output.push_str("class FrameEvent {\n");
                output.push_str("    constructor(public message: string, public parameters: FrameEventParameters | null) {}\n");
                output.push_str("}\n\n");
                output.push_str("class FrameCompartment {\n");
                output.push_str("    constructor(\n");
                output.push_str("        public state: string,\n");
                output.push_str("        public enterArgs?: any,\n");
                output.push_str("        public exitArgs?: any,\n");
                output.push_str("        public stateArgs?: any,\n");
                output.push_str("        public stateVars?: any,\n");
                output.push_str("        public enterArgsCollection?: any,\n");
                output.push_str("        public exitArgsCollection?: any,\n");
                output.push_str("        public forwardEvent?: FrameEvent | null\n");
                output.push_str("    ) {\n");
                output.push_str("        this.forwardEvent = forwardEvent || null;\n");
                output.push_str("        this.stateArgs = stateArgs || {};\n");
                output.push_str("        this.stateVars = stateVars || {};\n");
                output.push_str("    }\n");
                output.push_str("}\n\n");
                output.push_str(
                    "// External function declarations (provided by runtime environment)\n",
                );
                output.push_str("declare var Promise: PromiseConstructor;\n");
                output.push_str("declare function createAsyncServer(handler: (socket: any) => void): Promise<any>;\n");
                output.push_str("declare class NetworkServer { }\n");
                output.push_str("declare class JsonParser { static parse(data: any): any; }\n");
            }
            _ => {
                output.push_str("// Frame runtime classes\n");
                // Add default runtime for other languages if needed
            }
        }

        output
    }

    /// Filter module code to remove imports, runtime classes, and version comments based on target language
    fn filter_module_code(&self, code: &str) -> String {
        let mut output = Vec::new();
        let mut in_frame_event = false;
        let mut in_frame_compartment = false;
        let mut skip_next_blank = false;

        for line in code.lines() {
            let trimmed = line.trim();

            // Skip version comment based on target language
            let should_skip_version = match self.target_language {
                TargetLanguage::Python3 => trimmed.starts_with("#Emitted from framec"),
                TargetLanguage::TypeScript => trimmed.starts_with("// Emitted from framec"),
                _ => {
                    trimmed.starts_with("// Emitted from framec")
                        || trimmed.starts_with("#Emitted from framec")
                }
            };

            if should_skip_version {
                skip_next_blank = true;
                continue;
            }

            // Skip Frame import comments (must check before regular imports)
            let has_frame_import_comment = match self.target_language {
                TargetLanguage::Python3 => line.contains("# Frame import"),
                TargetLanguage::TypeScript => line.contains("// Frame import"),
                _ => line.contains("// Frame import") || line.contains("# Frame import"),
            };

            if has_frame_import_comment {
                skip_next_blank = true;
                continue;
            }

            // Skip import statements based on target language
            let should_skip_import = match self.target_language {
                TargetLanguage::Python3 => {
                    trimmed.starts_with("import ") || trimmed.starts_with("from ")
                }
                TargetLanguage::TypeScript => {
                    // Only filter import statements, not export class declarations
                    trimmed.starts_with("import ")
                }
                _ => {
                    trimmed.starts_with("import ")
                        || trimmed.starts_with("export ")
                        || trimmed.starts_with("from ")
                }
            };

            if should_skip_import {
                skip_next_blank = true;
                continue;
            }

            // Check if we're entering a FrameEvent class definition (Python)
            if self.target_language == TargetLanguage::Python3
                && line.starts_with("class FrameEvent:")
            {
                in_frame_event = true;
                skip_next_blank = true;
                continue;
            }

            // Check if we're entering a FrameCompartment class definition (Python)
            if self.target_language == TargetLanguage::Python3
                && line.starts_with("class FrameCompartment:")
            {
                in_frame_compartment = true;
                skip_next_blank = true;
                continue;
            }

            // If we're in a runtime class, check for end (Python only)
            if in_frame_event || in_frame_compartment {
                // Count indentation to track class body
                if !line.is_empty() && !line.starts_with(' ') && !line.starts_with('\t') {
                    // We've exited the class
                    in_frame_event = false;
                    in_frame_compartment = false;
                    skip_next_blank = false;
                    // Process this line normally
                    output.push(line);
                } else {
                    // Skip lines that are part of the runtime class
                    continue;
                }
            } else if skip_next_blank && line.trim().is_empty() {
                skip_next_blank = false;
                continue;
            } else {
                // Keep all other lines
                output.push(line);
                skip_next_blank = false;
            }
        }

        // Clean up multiple consecutive blank lines
        let mut result = Vec::new();
        let mut prev_blank = false;
        for line in output {
            if line.trim().is_empty() {
                if !prev_blank {
                    result.push(line);
                }
                prev_blank = true;
            } else {
                result.push(line);
                prev_blank = false;
            }
        }

        result.join("\n")
    }

    /// Check if any module has a main function
    fn has_main_function(&self, module_codes: &[(std::path::PathBuf, String)]) -> bool {
        for (_, code) in module_codes {
            if code.contains("def main():") || code.contains("def main(") {
                return true;
            }
        }
        false
    }

    /// Extract the main() call from module code
    fn extract_main_call(&self, code: &str) -> Option<String> {
        for line in code.lines() {
            let trimmed = line.trim();
            // Look for standalone main() call at module level
            if trimmed == "main()" || trimmed.starts_with("main(") {
                // Check if it's not inside a function or class
                if !line.starts_with(' ') && !line.starts_with('\t') {
                    return Some(line.to_string());
                }
            }
        }
        None
    }

    /// Generate separate Python files for each module
    fn link_separate_files(
        &mut self,
        output_dir: &Path,
        create_package: bool,
    ) -> ModuleResult<String> {
        use crate::frame_c::config::FrameConfig;
        use crate::frame_c::visitors::python_visitor::PythonVisitor;

        // Create output directory if it doesn't exist
        fs::create_dir_all(output_dir).map_err(|e| {
            ModuleError::new(
                ModuleErrorKind::IOError {
                    path: output_dir.to_path_buf(),
                    error: e.to_string(),
                },
                format!(
                    "Failed to create output directory: {}",
                    output_dir.display()
                ),
            )
        })?;

        let config = FrameConfig::default();
        let framec_version = "Emitted from framec_v0.76.1";

        // Process each module and generate its Python file
        let modules = std::mem::take(&mut self.modules);
        let mut generated_files = Vec::new();
        let mut module_map = HashMap::new(); // Map Frame paths to Python module names

        for module in modules {
            // Generate Python module name from Frame file path
            let py_module_name = self.frame_path_to_python_module(&module.file_path);
            module_map.insert(module.file_path.clone(), py_module_name.clone());

            // Create a visitor for this module
            let mut visitor = PythonVisitor::new(
                module.symbols,
                false, // generate_state_stack
                false, // generate_change_state
                framec_version,
                Vec::new(), // comments
                config.clone(),
            );

            // Generate code for this module
            visitor.run_v2(&module.ast);
            let mut module_code = visitor.get_code();

            // Add Python imports for Frame imports
            let python_imports =
                self.generate_python_imports(&module.ast, &module_map, &module.file_path);
            if !python_imports.is_empty() {
                // Insert imports after the version comment
                let lines: Vec<&str> = module_code.lines().collect();
                let mut output = String::new();

                // Keep the version comment
                if let Some(version_line) = lines.first() {
                    if version_line.starts_with("#Emitted") {
                        output.push_str(version_line);
                        output.push_str("\n\n");
                    }
                }

                // Add Python imports for Frame modules
                output.push_str("# Frame module imports\n");
                output.push_str(&python_imports);
                output.push_str("\n");

                // Add the rest of the code (skipping version comment if present)
                let start_idx = if lines.first().map_or(false, |l| l.starts_with("#Emitted")) {
                    1
                } else {
                    0
                };
                for line in &lines[start_idx..] {
                    output.push_str(line);
                    output.push('\n');
                }

                module_code = output;
            }

            // Write to file
            let py_file_name = format!("{}.py", py_module_name);
            let py_file_path = output_dir.join(&py_file_name);

            fs::write(&py_file_path, module_code).map_err(|e| {
                ModuleError::new(
                    ModuleErrorKind::IOError {
                        path: py_file_path.clone(),
                        error: e.to_string(),
                    },
                    format!("Failed to write Python file: {}", py_file_path.display()),
                )
            })?;

            generated_files.push(py_file_path);
        }

        // Create __init__.py if requested
        if create_package {
            let init_path = output_dir.join("__init__.py");
            let init_content = "# Frame package\n# Auto-generated by Frame Transpiler v0.57\n";
            fs::write(&init_path, init_content).map_err(|e| {
                ModuleError::new(
                    ModuleErrorKind::IOError {
                        path: init_path.clone(),
                        error: e.to_string(),
                    },
                    format!("Failed to write __init__.py: {}", init_path.display()),
                )
            })?;
            generated_files.push(init_path);
        }

        // Return a summary of what was generated
        let mut summary = String::new();
        summary.push_str(&format!(
            "# Generated {} Python files in {}\n",
            generated_files.len(),
            output_dir.display()
        ));
        for file in &generated_files {
            summary.push_str(&format!("# - {}\n", file.display()));
        }

        Ok(summary)
    }

    /// Convert Frame file path to Python module name
    fn frame_path_to_python_module(&self, frame_path: &Path) -> String {
        // Get the file stem (filename without extension)
        frame_path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or("module")
            .to_string()
    }

    /// Generate Python import statements for Frame imports
    fn generate_python_imports(
        &self,
        ast: &crate::frame_c::ast::FrameModule,
        module_map: &HashMap<PathBuf, String>,
        current_path: &Path,
    ) -> String {
        use crate::frame_c::ast::ImportType;

        let mut imports = Vec::new();

        for import_node in &ast.imports {
            match &import_node.import_type {
                ImportType::FrameModule {
                    module_name,
                    file_path,
                } => {
                    // Calculate the Python module name for the imported Frame file
                    let import_path = current_path
                        .parent()
                        .unwrap_or(Path::new("."))
                        .join(file_path.trim_start_matches("./"));

                    if let Some(py_module) = module_map.get(&import_path) {
                        imports.push(format!("from {} import {}", py_module, module_name));
                    } else {
                        // Fall back to deriving from file path
                        let py_module = self.frame_path_to_python_module(&import_path);
                        imports.push(format!("from {} import {}", py_module, module_name));
                    }
                }
                ImportType::FrameModuleAliased {
                    module_name,
                    file_path,
                    alias,
                } => {
                    let import_path = current_path
                        .parent()
                        .unwrap_or(Path::new("."))
                        .join(file_path.trim_start_matches("./"));

                    if let Some(py_module) = module_map.get(&import_path) {
                        imports.push(format!(
                            "from {} import {} as {}",
                            py_module, module_name, alias
                        ));
                    } else {
                        let py_module = self.frame_path_to_python_module(&import_path);
                        imports.push(format!(
                            "from {} import {} as {}",
                            py_module, module_name, alias
                        ));
                    }
                }
                ImportType::FrameSelective { items, file_path } => {
                    let import_path = current_path
                        .parent()
                        .unwrap_or(Path::new("."))
                        .join(file_path.trim_start_matches("./"));

                    if let Some(py_module) = module_map.get(&import_path) {
                        let items_str = items.join(", ");
                        imports.push(format!("from {} import {}", py_module, items_str));
                    } else {
                        let py_module = self.frame_path_to_python_module(&import_path);
                        let items_str = items.join(", ");
                        imports.push(format!("from {} import {}", py_module, items_str));
                    }
                }
                _ => {
                    // Skip Python imports, they're already handled
                }
            }
        }

        imports.join("\n")
    }

    /// Optimized linking with dead code elimination (future)
    fn link_optimized(&mut self) -> ModuleResult<String> {
        // For now, fall back to concatenation
        // TODO: Implement proper optimization passes
        self.link_concatenation()
    }

    /// Generate common imports needed by all modules
    fn _generate_common_imports(&self) -> String {
        let mut imports = String::new();

        // Standard imports for Frame runtime
        imports.push_str("# Frame runtime imports\n");
        imports.push_str("from enum import Enum\n");
        imports.push_str("import json\n");
        imports.push_str("import sys\n");

        // Add any Frame-specific runtime classes
        imports.push_str("\n# Frame runtime classes\n");
        imports.push_str(self._generate_frame_runtime().as_str());

        imports.push_str("\n");
        imports
    }

    /// Generate Frame runtime helper classes
    fn _generate_frame_runtime(&self) -> String {
        r#"
class FrameEvent:
    def __init__(self, message, parameters):
        self._message = message
        self._parameters = parameters
        self._return = None

class FrameCompartment:
    def __init__(self, state):
        self._state = state
        self._state_args = {}
        self._state_vars = {}
        self.parent_compartment = None

"#
        .to_string()
    }

    /// Build global symbol resolution table
    fn _build_symbol_table(&mut self) -> ModuleResult<()> {
        self.symbol_table.clear();

        for module in &self.modules {
            // Access the Arcanum symbols directly (no borrow needed)
            // Arcanum is not RefCell wrapped in CompiledModule

            // Add module prefix to all symbols
            let module_path_str = module.file_path.to_string_lossy();
            let _module_prefix = self._get_module_prefix(&module_path_str);

            // TODO: Extract symbols from module and add to global table
            // This will be implemented when we have proper symbol extraction
        }

        Ok(())
    }

    /// Get a unique prefix for a module
    fn _get_module_prefix(&self, module_path: &str) -> String {
        // Convert path to a valid Python identifier
        module_path
            .replace("/", "_")
            .replace("\\", "_")
            .replace(".", "_")
            .replace("::", "_")
    }

    /// Detect and report symbol conflicts
    fn _check_symbol_conflicts(&self) -> ModuleResult<Vec<String>> {
        let mut conflicts = Vec::new();
        let symbol_sources: HashMap<String, Vec<String>> = HashMap::new();

        // Collect all exported symbols from each module
        for _module in &self.modules {
            // Access symbols directly from Arcanum (no borrow needed)
            // TODO: Extract actual symbols and check for conflicts
            // This will be implemented when we have proper symbol extraction
        }

        // Find conflicts (symbols defined in multiple modules)
        for (symbol, sources) in symbol_sources {
            if sources.len() > 1 {
                conflicts.push(format!(
                    "Symbol '{}' defined in multiple modules: {}",
                    symbol,
                    sources.join(", ")
                ));
            }
        }

        Ok(conflicts)
    }

    /// Get linking statistics
    pub fn get_stats(&self) -> LinkStats {
        let mut total_lines = 0;
        let mut total_functions = 0;
        let mut total_systems = 0;
        let mut total_classes = 0;

        for module in &self.modules {
            // TODO: Count lines when we have generated code
            // For now, estimate based on AST size
            total_lines += module.ast.functions.len() * 10; // Rough estimate

            // Count declarations in AST
            total_functions += module.ast.functions.len();
            total_systems += module.ast.systems.len();
            total_classes += module.ast.classes.len();
        }

        LinkStats {
            modules_linked: self.modules.len(),
            total_lines,
            total_functions,
            total_systems,
            total_classes,
        }
    }

    /// Clear all modules (useful for reuse)
    pub fn clear(&mut self) {
        self.modules.clear();
        self.symbol_table.clear();
    }

    /// Get module count
    pub fn module_count(&self) -> usize {
        self.modules.len()
    }

    /// Check if linker has any modules
    pub fn is_empty(&self) -> bool {
        self.modules.is_empty()
    }
}

impl Default for LinkingStrategy {
    fn default() -> Self {
        Self::Concatenation
    }
}
