/**
 * Frame TypeScript Runtime Library
 *
 * Provides Frame-semantic implementations for TypeScript/JavaScript
 * that differ from Python behavior, enabling consistent Frame execution
 * across target languages.
 *
 * Generated by Frame Transpiler v0.86.13
 */

const FRAME_FS = require('fs');
const pathLib = require('path');
const net = require('net');

const ORDERED_DICT_STORE = new WeakMap<any, { store: Record<string, any>; order: string[] }>();
const COUNTER_STORE = new WeakMap<any, Map<string, number>>();
const CHAINMAP_STORE = new WeakMap<any, Array<Record<string, any>>>();

class FrameFile {
    constructor(private filePath: string, private mode: string) {
        if (this.mode.includes('w')) {
            FRAME_FS.writeFileSync(this.filePath, '');
        } else if (this.mode.includes('a')) {
            if (!FRAME_FS.existsSync(this.filePath)) {
                FRAME_FS.writeFileSync(this.filePath, '');
            }
        } else if (this.mode.includes('r')) {
            if (!FRAME_FS.existsSync(this.filePath)) {
                throw new Error(`File not found: ${this.filePath}`);
            }
        }
    }

    write(data: any): void {
        if (!(this.mode.includes('w') || this.mode.includes('a'))) {
            throw new Error(`File not open for writing: ${this.filePath}`);
        }
        const text = typeof data === 'string' ? data : String(data);
        FRAME_FS.appendFileSync(this.filePath, text);
    }

    read(): string {
        return FRAME_FS.readFileSync(this.filePath, 'utf8');
    }

    close(): void {
        // No-op for synchronous file handles
    }
}

class FrameEnviron {
    get(key: any, defaultValue: any = undefined): any {
        const value = process.env[String(key)];
        return value !== undefined ? value : defaultValue;
    }

    set(key: any, value: any): void {
        process.env[String(key)] = String(value);
    }

    keys(): string[] {
        return Object.keys(process.env);
    }

    values(): any[] {
        return Object.values(process.env);
    }

    items(): [string, string][] {
        return Object.entries(process.env) as [string, string][];
    }

    [Symbol.iterator](): IterableIterator<[string, string]> {
        return Object.entries(process.env)[Symbol.iterator]() as IterableIterator<[string, string]>;
    }

    toJSON(): Record<string, string> {
        return { ...process.env } as Record<string, string>;
    }
}

class FrameComplex {
    public readonly __complex__ = true;

    constructor(public real: number, public imag: number) {}

    toString(): string {
        return FrameRuntime.complexToString(this);
    }

    toJSON(): { real: number; imag: number } {
        return { real: this.real, imag: this.imag };
    }
}

function createPathProxy() {
    return new Proxy(pathLib as any, {
        get(target: any, prop: PropertyKey) {
            if (prop === 'exists') {
                return (p: any) => FRAME_FS.existsSync(p);
            }
            const value = target[prop];
            if (typeof value === 'function') {
                return value.bind(target);
            }
            return value;
        }
    });
}

function createJsonHelpers() {
    return {
        loads: (text: any) => (typeof text === 'string' ? JSON.parse(text) : text),
        dumps: (value: any, replacer?: any, indent?: any) => JSON.stringify(value, replacer, indent as any),
        load: (file: FrameFile) => JSON.parse(file.read()),
        dump: (value: any, file: FrameFile, indent?: any) => {
            const spacing = indent !== undefined ? indent : 0;
            const jsonText = JSON.stringify(value, null, spacing as any);
            file.write(jsonText + (spacing ? '\n' : ''));
        }
    };
}

export class FrameRuntime {
    private static readonly NotImplemented = Symbol('FrameRuntime.NotImplemented');
    private static readonly _os = FrameRuntime.createOs();
    private static readonly _json = createJsonHelpers();
    private static readonly signalHandlers: Map<string, (signal: any, frame?: any) => void> = new Map();
    private static readonly signalListeners: Map<string, () => void> = new Map();
    private static unsupportedBinary(op: string, left: any, right: any): never {
        const leftType = FrameRuntime.getType(left);
        const rightType = FrameRuntime.getType(right);
        throw new TypeError(`unsupported operand type(s) for ${op}: '${leftType}' and '${rightType}'`);
    }

    private static normalizeNumber(value: number): number {
        if (Number.isNaN(value)) {
            return NaN;
        }
        return Object.is(value, -0) ? 0 : value;
    }

    private static makeComplex(real: number, imag: number): FrameComplex {
        return new FrameComplex(
            FrameRuntime.normalizeNumber(real),
            FrameRuntime.normalizeNumber(imag)
        );
    }

    private static isComplex(value: any): value is FrameComplex {
        return value instanceof FrameComplex;
    }

    private static isComplexLike(value: any): boolean {
        if (FrameRuntime.isComplex(value)) {
            return true;
        }
        if (value && typeof value === 'object') {
            if (value.__complex__ === true && typeof value.real === 'number' && typeof value.imag === 'number') {
                return true;
            }
            if (typeof value.real === 'number' && typeof value.imag === 'number') {
                return true;
            }
        }
        if (typeof value === 'string') {
            return FrameRuntime.parseComplexString(value) !== null;
        }
        return false;
    }

    private static parseComplexString(value: string): FrameComplex | null {
        if (typeof value !== 'string') {
            return null;
        }

        const normalized = value.replace(/\s+/g, '').replace(/J$/g, 'j');
        if (!normalized.toLowerCase().includes('j')) {
            return null;
        }

        if (normalized === 'j' || normalized === '+j') {
            return FrameRuntime.makeComplex(0, 1);
        }
        if (normalized === '-j') {
            return FrameRuntime.makeComplex(0, -1);
        }

        const imagOnlyMatch = normalized.match(/^([+-]?(?:\d+(?:\.\d+)?|\.\d+))j$/i);
        if (imagOnlyMatch) {
            return FrameRuntime.makeComplex(0, parseFloat(imagOnlyMatch[1]));
        }

        const fullMatch = normalized.match(/^([+-]?(?:\d+(?:\.\d+)?|\.\d+))([+-](?:\d+(?:\.\d+)?|\.\d+))j$/i);
        if (fullMatch) {
            const realPart = parseFloat(fullMatch[1]);
            const imagPart = parseFloat(fullMatch[2]);
            if (!Number.isNaN(realPart) && !Number.isNaN(imagPart)) {
                return FrameRuntime.makeComplex(realPart, imagPart);
            }
        }

        return null;
    }

    private static ensureComplex(value: any): FrameComplex {
        if (FrameRuntime.isComplex(value)) {
            return value;
        }

        if (typeof value === 'string') {
            const parsed = FrameRuntime.parseComplexString(value);
            if (parsed) {
                return parsed;
            }
        }

        if (typeof value === 'number') {
            return FrameRuntime.makeComplex(value, 0);
        }

        if (typeof value === 'bigint') {
            return FrameRuntime.makeComplex(Number(value), 0);
        }

        if (value && typeof value === 'object') {
            if (value.__complex__ === true && typeof value.real === 'number' && typeof value.imag === 'number') {
                return FrameRuntime.makeComplex(value.real, value.imag);
            }
            if (typeof value.real === 'number' && typeof value.imag === 'number') {
                return FrameRuntime.makeComplex(value.real, value.imag);
            }
        }

        throw new TypeError(`Cannot interpret '${FrameRuntime.getType(value)}' as a complex number`);
    }

    private static formatNumber(value: number): string {
        const normalized = FrameRuntime.normalizeNumber(value);
        if (Number.isNaN(normalized)) {
            return 'nan';
        }
        if (!Number.isFinite(normalized)) {
            return normalized > 0 ? 'inf' : '-inf';
        }
        if (Number.isInteger(normalized)) {
            return normalized.toString();
        }
        return normalized.toString();
    }

    static complexToString(value: { real: number; imag: number }): string {
        const real = FrameRuntime.normalizeNumber(value.real);
        const imag = FrameRuntime.normalizeNumber(value.imag);

        if (real === 0 && imag !== 0) {
            const imagStr = FrameRuntime.formatNumber(imag);
            return imag > 0 ? `${imagStr}j` : `${imagStr}j`;
        }

        if (imag === 0) {
            return `${FrameRuntime.formatNumber(real)}+0j`;
        }

        const sign = imag >= 0 ? '+' : '-';
        const imagAbs = Math.abs(imag);
        return `${FrameRuntime.formatNumber(real)}${sign}${FrameRuntime.formatNumber(imagAbs)}j`;
    }

    static str(value: any): string {
        if (FrameRuntime.isComplexLike(value)) {
            const complex = FrameRuntime.ensureComplex(value);
            return FrameRuntime.complexToString(complex);
        }

        if (value && typeof value === 'object') {
            if (typeof value.__str__ === 'function') {
                try {
                    const result = value.__str__();
                    if (result !== undefined) {
                        return String(result);
                    }
                } catch (err) {
                    // Fall back to default behaviour
                }
            }

            try {
                return JSON.stringify(value);
            } catch (err) {
                return String(value);
            }
        }

        return String(value);
    }

    private static createOs() {
        return {
            path: createPathProxy(),
            environ: new FrameEnviron()
        };
    }

    static get os() {
        return this._os;
    }

    static get json() {
        return this._json;
    }

    static timeSeconds(): number {
        return Date.now() / 1000;
    }

    static sleep(seconds: number): void {
        const ms = Math.max(0, Number(seconds) * 1000);
        if (!Number.isFinite(ms) || ms <= 0) {
            return;
        }

        const end = Date.now() + ms;
        while (Date.now() < end) {
            // Busy-wait; sufficient for short test-oriented delays
        }
    }

    static registerSignal(signalName: string, handler: (signal: any, frame?: any) => void): void {
        if (!signalName || typeof handler !== 'function') {
            return;
        }

        const normalized = String(signalName);
        FrameRuntime.signalHandlers.set(normalized, handler);

        if (typeof process !== 'undefined' && typeof process.on === 'function') {
            if (!FrameRuntime.signalListeners.has(normalized)) {
                const listener = () => {
                    try {
                        const registered = FrameRuntime.signalHandlers.get(normalized);
                        if (registered) {
                            registered(normalized, null);
                        }
                    } catch (err) {
                        console.error('FrameRuntime signal handler error:', err);
                    }
                };
                FrameRuntime.signalListeners.set(normalized, listener);
                (process as any).on(normalized, listener);
            }
        }
    }

    static open(pathValue: any, mode: any = 'r'): FrameFile {
        const normalized = String(mode).replace('b', '');
        return new FrameFile(pathValue, normalized);
    }

    private static invokeDunder(target: any, method: string, arg: any): any {
        if (target === null || target === undefined) {
            return FrameRuntime.NotImplemented;
        }

        const fn = target[method];
        if (typeof fn === 'function') {
            const result = fn.call(target, arg);
            return result === undefined ? FrameRuntime.NotImplemented : result;
        }

        return FrameRuntime.NotImplemented;
    }

    static truthy(value: any): boolean {
        if (value === null || value === undefined) {
            return false;
        }

        if (typeof value === 'boolean') {
            return value;
        }

        if (typeof value === 'number') {
            return value !== 0;
        }

        if (FrameRuntime.isComplexLike(value)) {
            const complex = FrameRuntime.ensureComplex(value);
            return !(
                FrameRuntime.normalizeNumber(complex.real) === 0 &&
                FrameRuntime.normalizeNumber(complex.imag) === 0
            );
        }

        if (typeof value === 'string') {
            return value.length > 0;
        }

        if (Array.isArray(value)) {
            return value.length > 0;
        }

        if (value instanceof Set || value instanceof Map) {
            return value.size > 0;
        }

        if (typeof value === 'object') {
            if (typeof value.__bool__ === 'function') {
                const result = value.__bool__();
                return FrameRuntime.truthy(result);
            }

            if (typeof value.__len__ === 'function') {
                const length = value.__len__();
                return Number(length) !== 0;
            }

            if ('length' in value && typeof value.length === 'number') {
                return value.length > 0;
            }
        }

        return true;
    }

    static add(left: any, right: any): any {
        const direct = FrameRuntime.invokeDunder(left, '__add__', right);
        if (direct !== FrameRuntime.NotImplemented) {
            return direct;
        }

        const reflected = FrameRuntime.invokeDunder(right, '__radd__', left);
        if (reflected !== FrameRuntime.NotImplemented) {
            return reflected;
        }

        const leftComplexLike = FrameRuntime.isComplexLike(left);
        const rightComplexLike = FrameRuntime.isComplexLike(right);
        if ((leftComplexLike || rightComplexLike) && !(typeof left === 'string' && typeof right === 'string')) {
            const leftComplex = FrameRuntime.ensureComplex(left);
            const rightComplex = FrameRuntime.ensureComplex(right);
            return FrameRuntime.makeComplex(
                leftComplex.real + rightComplex.real,
                leftComplex.imag + rightComplex.imag
            );
        }

        if (typeof left === 'string' || typeof right === 'string') {
            return String(left) + String(right);
        }

        if (Array.isArray(left) && Array.isArray(right)) {
            return [...left, ...right];
        }

        const leftNum = Number(left);
        const rightNum = Number(right);
        if (!Number.isNaN(leftNum) && !Number.isNaN(rightNum)) {
            return leftNum + rightNum;
        }

        FrameRuntime.unsupportedBinary("+", left, right);
    }

    static subtract(left: any, right: any): any {
        const direct = FrameRuntime.invokeDunder(left, '__sub__', right);
        if (direct !== FrameRuntime.NotImplemented) {
            return direct;
        }

        const reflected = FrameRuntime.invokeDunder(right, '__rsub__', left);
        if (reflected !== FrameRuntime.NotImplemented) {
            return reflected;
        }

        const leftComplexLike = FrameRuntime.isComplexLike(left);
        const rightComplexLike = FrameRuntime.isComplexLike(right);
        if ((leftComplexLike || rightComplexLike) && !(typeof left === 'string' && typeof right === 'string')) {
            const leftComplex = FrameRuntime.ensureComplex(left);
            const rightComplex = FrameRuntime.ensureComplex(right);
            return FrameRuntime.makeComplex(
                leftComplex.real - rightComplex.real,
                leftComplex.imag - rightComplex.imag
            );
        }

        const leftNum = Number(left);
        const rightNum = Number(right);
        if (!Number.isNaN(leftNum) && !Number.isNaN(rightNum)) {
            return leftNum - rightNum;
        }

        FrameRuntime.unsupportedBinary("-", left, right);
    }

    static multiply(left: any, right: any): any {
        const direct = FrameRuntime.invokeDunder(left, '__mul__', right);
        if (direct !== FrameRuntime.NotImplemented) {
            return direct;
        }

        const reflected = FrameRuntime.invokeDunder(right, '__rmul__', left);
        if (reflected !== FrameRuntime.NotImplemented) {
            return reflected;
        }

        if ((FrameRuntime.isComplexLike(left) || FrameRuntime.isComplexLike(right)) &&
            !(typeof left === 'string' && typeof right === 'string')) {
            const leftComplex = FrameRuntime.ensureComplex(left);
            const rightComplex = FrameRuntime.ensureComplex(right);
            const realPart =
                leftComplex.real * rightComplex.real - leftComplex.imag * rightComplex.imag;
            const imagPart =
                leftComplex.real * rightComplex.imag + leftComplex.imag * rightComplex.real;
            return FrameRuntime.makeComplex(realPart, imagPart);
        }

        if (typeof left === 'string' && typeof right === 'number') {
            return left.repeat(right);
        }
        if (typeof right === 'string' && typeof left === 'number') {
            return right.repeat(left);
        }
        if (Array.isArray(left) && typeof right === 'number') {
            const count = Math.trunc(right);
            if (!Number.isFinite(count) || count <= 0) {
                return [];
            }
            const result: any[] = [];
            for (let i = 0; i < count; i++) {
                result.push(...left);
            }
            return result;
        }
        if (Array.isArray(right) && typeof left === 'number') {
            const count = Math.trunc(left);
            if (!Number.isFinite(count) || count <= 0) {
                return [];
            }
            const result: any[] = [];
                for (let i = 0; i < count; i++) {
                result.push(...right);
            }
            return result;
        }

        const leftNum = Number(left);
        const rightNum = Number(right);
        if (!Number.isNaN(leftNum) && !Number.isNaN(rightNum)) {
            return leftNum * rightNum;
        }

        FrameRuntime.unsupportedBinary("*", left, right);
    }

    static divide(left: any, right: any): any {
        const direct = FrameRuntime.invokeDunder(left, '__truediv__', right);
        if (direct !== FrameRuntime.NotImplemented) {
            return direct;
        }

        const reflected = FrameRuntime.invokeDunder(right, '__rtruediv__', left);
        if (reflected !== FrameRuntime.NotImplemented) {
            return reflected;
        }

        const leftNum = Number(left);
        const rightNum = Number(right);
        if (!Number.isNaN(leftNum) && !Number.isNaN(rightNum)) {
            return leftNum / rightNum;
        }

        FrameRuntime.unsupportedBinary("/", left, right);
    }

    static floorDivide(left: any, right: any): any {
        const direct = FrameRuntime.invokeDunder(left, '__floordiv__', right);
        if (direct !== FrameRuntime.NotImplemented) {
            return direct;
        }

        const reflected = FrameRuntime.invokeDunder(right, '__rfloordiv__', left);
        if (reflected !== FrameRuntime.NotImplemented) {
            return reflected;
        }

        const leftNum = Number(left);
        const rightNum = Number(right);
        if (!Number.isNaN(leftNum) && !Number.isNaN(rightNum)) {
            return Math.floor(leftNum / rightNum);
        }

        FrameRuntime.unsupportedBinary("//", left, right);
    }

    static modulo(left: any, right: any): any {
        const direct = FrameRuntime.invokeDunder(left, '__mod__', right);
        if (direct !== FrameRuntime.NotImplemented) {
            return direct;
        }

        const reflected = FrameRuntime.invokeDunder(right, '__rmod__', left);
        if (reflected !== FrameRuntime.NotImplemented) {
            return reflected;
        }

        const dividend = Number(left);
        const divisor = Number(right);
        if (!Number.isNaN(dividend) && !Number.isNaN(divisor)) {
            const remainder = dividend % divisor;
            if (Number.isNaN(remainder)) {
                return remainder;
            }
            return remainder >= 0 ? remainder : remainder + Math.abs(divisor);
        }

        FrameRuntime.unsupportedBinary("%", left, right);
    }

    static power(left: any, right: any): any {
        const direct = FrameRuntime.invokeDunder(left, '__pow__', right);
        if (direct !== FrameRuntime.NotImplemented) {
            return direct;
        }

        const reflected = FrameRuntime.invokeDunder(right, '__rpow__', left);
        if (reflected !== FrameRuntime.NotImplemented) {
            return reflected;
        }

        const leftNum = Number(left);
        const rightNum = Number(right);
        if (!Number.isNaN(leftNum) && !Number.isNaN(rightNum)) {
            return leftNum ** rightNum;
        }

        FrameRuntime.unsupportedBinary("**", left, right);
    }

    static is(left: any, right: any): boolean {
        return Object.is(left, right);
    }

    static isNot(left: any, right: any): boolean {
        return !FrameRuntime.is(left, right);
    }

    static bindAction(system: any, actionName: string): (...args: any[]) => any {
        const methodName = `_action_${actionName}`;
        const method = system?.[methodName];
        if (typeof method !== 'function') {
            throw new Error(`FrameRuntime.bindAction: action '${actionName}' not found on system`);
        }
        return method.bind(system);
    }

    static listen(target: any, port: any, host: any, system: any, actionName: string): void {
        const callback = FrameRuntime.bindAction(system, actionName);
        if (host === undefined || host === null) {
            target.listen(port, callback);
        } else {
            target.listen(port, host, callback);
        }
    }

    static addListener(target: any, event: string, system: any, actionName: string): void {
        target.on(event, FrameRuntime.bindAction(system, actionName));
    }

    static setTimeout(system: any, actionName: string, delay: number): any {
        const callback = FrameRuntime.bindAction(system, actionName);
        return globalThis.setTimeout(callback, delay);
    }

    static extractPort(address: any): number {
        if (address == null) {
            return 0;
        }
        if (typeof address === 'string') {
            const parts = address.split(':');
            const portString = parts[parts.length - 1];
            const parsed = Number(portString);
            return Number.isFinite(parsed) ? parsed : 0;
        }
        if (typeof address === 'object' && 'port' in address) {
            const value = (address as any).port;
            return typeof value === 'number' ? value : 0;
        }
        return 0;
    }

    /**
     * Deep equality comparison for Frame semantics
     * Handles Sets, Maps, Arrays, Objects with proper content comparison
     * Falls back to === for primitives
     */
    static equals(left: any, right: any): boolean {
        // Handle null/undefined cases
        if (left === null || left === undefined || right === null || right === undefined) {
            return left === right;
        }

        const direct = FrameRuntime.invokeDunder(left, '__eq__', right);
        if (direct !== FrameRuntime.NotImplemented) {
            return FrameRuntime.truthy(direct);
        }

        const reflected = FrameRuntime.invokeDunder(right, '__req__', left);
        if (reflected !== FrameRuntime.NotImplemented) {
            return FrameRuntime.truthy(reflected);
        }

        if (FrameRuntime.isComplexLike(left) || FrameRuntime.isComplexLike(right)) {
            const leftComplex = FrameRuntime.ensureComplex(left);
            const rightComplex = FrameRuntime.ensureComplex(right);
            return (
                FrameRuntime.normalizeNumber(leftComplex.real) === FrameRuntime.normalizeNumber(rightComplex.real) &&
                FrameRuntime.normalizeNumber(leftComplex.imag) === FrameRuntime.normalizeNumber(rightComplex.imag)
            );
        }

        if (typeof left !== 'object' || typeof right !== 'object') {
            return left === right;
        }

        if (left === right) {
            return true;
        }

        // Handle Set comparison
        if (left instanceof Set && right instanceof Set) {
            if (left.size !== right.size) return false;
            for (const item of Array.from(left.values())) {
                if (!right.has(item)) return false;
            }
            return true;
        }

        // Handle Map comparison  
        if (left instanceof Map && right instanceof Map) {
            if (left.size !== right.size) return false;
            for (const [key, value] of Array.from(left.entries())) {
                if (!right.has(key) || !this.equals(right.get(key), value)) {
                    return false;
                }
            }
            return true;
        }

        // Handle Array comparison
        if (Array.isArray(left) && Array.isArray(right)) {
            if (left.length !== right.length) return false;
            for (let i = 0; i < left.length; i++) {
                if (!this.equals(left[i], right[i])) return false;
            }
            return true;
        }

        // Handle Object comparison (plain objects)
        if (left.constructor === Object && right.constructor === Object) {
            const leftKeys = Object.keys(left);
            const rightKeys = Object.keys(right);
            if (leftKeys.length !== rightKeys.length) return false;
            
            for (const key of leftKeys) {
                if (!(key in right) || !this.equals(left[key], right[key])) {
                    return false;
                }
            }
            return true;
        }

        // For all other objects, fall back to reference equality
        return left === right;
    }

    /**
     * Inequality comparison - negation of equals
     */
    static notEquals(left: any, right: any): boolean {
        const direct = FrameRuntime.invokeDunder(left, '__ne__', right);
        if (direct !== FrameRuntime.NotImplemented) {
            return FrameRuntime.truthy(direct);
        }

        const reflected = FrameRuntime.invokeDunder(right, '__rne__', left);
        if (reflected !== FrameRuntime.NotImplemented) {
            return FrameRuntime.truthy(reflected);
        }

        return !this.equals(left, right);
    }

    /**
     * Create a Set from array items
     */
    static createSet(items: any[] = []): Set<any> {
        return new Set(items);
    }

    /**
     * Create a Map (dictionary) from key-value pairs
     */
    static createDict(pairs: [any, any][] = []): Map<any, any> {
        return new Map(pairs);
    }

    /**
     * Create an Array (list) from items
     */
    static createList(items: any[] = []): any[] {
        return [...items];
    }

    /**
     * Get type name of an object (Python-like type() function)
     */
    static getType(obj: any): string {
        if (obj === null) return 'NoneType';
        if (obj === undefined) return 'undefined';
        
        if (typeof obj === 'boolean') return 'bool';
        if (typeof obj === 'number') {
            return Number.isInteger(obj) ? 'int' : 'float';
        }
        if (typeof obj === 'string') return 'str';
        if (typeof obj === 'function') return 'function';
        if (FrameRuntime.isComplex(obj) || (obj && obj.__complex__ === true)) return 'complex';

        if (Array.isArray(obj)) return 'list';
        if (obj instanceof Set) return 'set';
        if (obj instanceof Map) return 'dict';
        if (obj instanceof Date) return 'datetime';
        
        // For classes, try to get constructor name
        if (obj.constructor && obj.constructor.name) {
            return obj.constructor.name;
        }
        
        return 'object';
    }

    /**
     * Check if object is instance of type (Python-like isinstance)
     */
    static isinstance(obj: any, type: string): boolean {
        return this.getType(obj) === type;
    }

    /**
     * Python-like range function with multiple signatures
     */
    static range(start: number, stop?: number, step?: number): number[] {
        // range(stop) - start from 0
        if (stop === undefined) {
            stop = start;
            start = 0;
        }
        
        // Default step
        if (step === undefined) {
            step = 1;
        }
        
        // Validate step
        if (step === 0) {
            throw new Error('range() step argument must not be zero');
        }
        
        const result: number[] = [];
        
        if (step > 0) {
            for (let i = start; i < stop; i += step) {
                result.push(i);
            }
        } else {
            for (let i = start; i > stop; i += step) {
                result.push(i);
            }
        }
        
        return result;
    }

    /**
     * Get length of collections (Python-like len() function)
     */
    static len(obj: any): number {
        if (obj === null || obj === undefined) {
            throw new Error("object of type 'NoneType' has no len()");
        }
        
        if (typeof obj === 'object' && typeof obj.__len__ === 'function') {
            return Number(obj.__len__());
        }
        
        if (typeof obj === 'string') return obj.length;
        if (Array.isArray(obj)) return obj.length;
        if (obj instanceof Set) return obj.size;
        if (obj instanceof Map) return obj.size;
        
        // Try .length property
        if ('length' in obj && typeof obj.length === 'number') {
            return obj.length;
        }
        
        // Try .size property
        if ('size' in obj && typeof obj.size === 'number') {
            return obj.size;
        }

        if (typeof obj === 'object') {
            return Object.keys(obj).length;
        }
        
        throw new Error(`object of type '${this.getType(obj)}' has no len()`);
    }

    /**
     * Convert iterable inputs to arrays for comprehension handling
     */
    static iterable(iterable: any): any[] {
        if (iterable === null || iterable === undefined) {
            return [];
        }

        if (Array.isArray(iterable)) {
            return iterable;
        }

        if (typeof iterable === 'string') {
            return Array.from(iterable);
        }

        if (iterable instanceof Set || iterable instanceof Map) {
            return Array.from(iterable);
        }

        if (typeof iterable[Symbol.iterator] === 'function') {
            return Array.from(iterable);
        }

        if (typeof iterable === 'object') {
            return Object.keys(iterable);
        }

        return [];
    }

    static jsonLoads(text: any): any {
        if (typeof text !== "string") {
            return text;
        }
        return JSON.parse(text);
    }

    static jsonDumps(value: any, replacer?: any, space?: any): string {
        return JSON.stringify(value, replacer, space);
    }

    static literalEval(text: any): any {
        if (typeof text !== "string") {
            return text;
        }

        let normalized = text.trim();
        // Replace Python-style literals with JSON equivalents
        normalized = normalized
            .replace(/\bTrue\b/g, "true")
            .replace(/\btrue\b/g, "true")
            .replace(/\bFalse\b/g, "false")
            .replace(/\bfalse\b/g, "false")
            .replace(/\bNone\b/g, "null");

        // Replace single quotes with double quotes for JSON parsing
        normalized = normalized.replace(/'/g, '"');

        // Convert simple tuple notation to arrays
        normalized = normalized.replace(/\(([^()]+)\)/g, '[$1]');

        try {
            return JSON.parse(normalized);
        } catch {
            throw new Error(`Failed to literal_eval: ${text}`);
        }
    }

    static sum(iterable: any, start: any = 0): any {
        let total = start;
        for (const value of FrameRuntime.iterable(iterable)) {
            total += value;
        }
        return total;
    }

    static any(iterable: any): boolean {
        for (const value of FrameRuntime.iterable(iterable)) {
            if (value) {
                return true;
            }
        }
        return false;
    }

    static all(iterable: any): boolean {
        for (const value of FrameRuntime.iterable(iterable)) {
            if (!value) {
                return false;
            }
        }
        return true;
    }
}

/**
 * Frame String Operations
 * Python-like string methods for TypeScript
 */
export class FrameString {
    private static patched = false;

    private static ensurePatched(): void {
        if (FrameString.patched) {
            return;
        }
        FrameString.patched = true;
        const proto = String.prototype as any;

        if (!proto.rfind) {
            proto.rfind = function (search: any, start?: any, end?: any) {
                return FrameString.rfind(String(this), search, start, end);
            };
        }
        if (!proto.upper) {
            proto.upper = function () {
                return FrameString.upper(String(this));
            };
        }
        if (!proto.lower) {
            proto.lower = function () {
                return FrameString.lower(String(this));
            };
        }
        if (!proto.find) {
            proto.find = function (search: any, start?: any, end?: any) {
                return FrameString.find(String(this), search, start, end);
            };
        }
        if (!proto.rindex) {
            proto.rindex = function (search: any, start?: any, end?: any) {
                const idx = FrameString.rfind(String(this), search, start, end);
                if (idx === -1) {
                    throw new Error("ValueError: substring not found");
                }
                return idx;
            };
        }
        if (!proto.index) {
            proto.index = function (search: any, start?: any, end?: any) {
                return FrameString.index(String(this), search, start, end);
            };
        }
        if (!proto.count) {
            proto.count = function (sub: any, start?: any, end?: any) {
                return FrameString.count(String(this), sub, start, end);
            };
        }
        if (!proto.startswith) {
            proto.startswith = function (prefix: any) {
                return FrameString.startswith(String(this), String(prefix));
            };
        }
        if (!proto.endswith) {
            proto.endswith = function (suffix: any) {
                return FrameString.endswith(String(this), String(suffix));
            };
        }
        if (!proto.splitlines) {
            proto.splitlines = function () {
                return FrameString.splitlines(String(this));
            };
        }
        if (!proto.partition) {
            proto.partition = function (sep: any) {
                return FrameString.partition(String(this), sep);
            };
        }
        if (!proto.rpartition) {
            proto.rpartition = function (sep: any) {
                return FrameString.rpartition(String(this), sep);
            };
        }
        if (!proto.rsplit) {
            proto.rsplit = function (sep?: any, maxsplit?: any) {
                return FrameString.rsplit(String(this), sep, maxsplit);
            };
        }
        if (!proto.center) {
            proto.center = function (width: any, fill?: any) {
                return FrameString.center(String(this), width, fill);
            };
        }
        if (!proto.ljust) {
            proto.ljust = function (width: any, fill?: any) {
                return FrameString.ljust(String(this), width, fill);
            };
        }
        if (!proto.rjust) {
            proto.rjust = function (width: any, fill?: any) {
                return FrameString.rjust(String(this), width, fill);
            };
        }
        if (!proto.zfill) {
            proto.zfill = function (width: any) {
                return FrameString.zfill(String(this), width);
            };
        }
        if (!proto.format) {
            proto.format = function (...values: any[]) {
                return FrameString.format(String(this), values);
            };
        }
        if (!proto.format_map) {
            proto.format_map = function (mapping: any) {
                return FrameString.formatMap(String(this), mapping);
            };
        }
        if (!proto.encode) {
            proto.encode = function (encoding?: any) {
                return FrameString.encode(String(this), encoding);
            };
        }
        if (!proto.expandtabs) {
            proto.expandtabs = function (tabsize?: any) {
                return FrameString.expandTabs(String(this), tabsize);
            };
        }
        if (!proto.strip) {
            proto.strip = function (chars?: any) {
                return FrameString.strip(String(this), chars);
            };
        }
        if (!proto.lstrip) {
            proto.lstrip = function (chars?: any) {
                return FrameString.lstrip(String(this), chars);
            };
        }
        if (!proto.rstrip) {
            proto.rstrip = function (chars?: any) {
                return FrameString.rstrip(String(this), chars);
            };
        }
        if (!proto.join) {
            proto.join = function (iterable: any) {
                return FrameString.join(String(this), iterable);
            };
        }
        if (!proto.title) {
            proto.title = function () {
                return FrameString.title(String(this));
            };
        }
        if (!proto.capitalize) {
            proto.capitalize = function () {
                return FrameString.capitalize(String(this));
            };
        }
        if (!proto.swapcase) {
            proto.swapcase = function () {
                return FrameString.swapcase(String(this));
            };
        }
        if (!proto.isdigit) {
            proto.isdigit = function () {
                return FrameString.isdigit(String(this));
            };
        }
        if (!proto.isalpha) {
            proto.isalpha = function () {
                return FrameString.isalpha(String(this));
            };
        }
        if (!proto.isalnum) {
            proto.isalnum = function () {
                return FrameString.isalnum(String(this));
            };
        }
        if (!proto.isspace) {
            proto.isspace = function () {
                return FrameString.isspace(String(this));
            };
        }
        if (!proto.islower) {
            proto.islower = function () {
                return FrameString.islower(String(this));
            };
        }
        if (!proto.isupper) {
            proto.isupper = function () {
                return FrameString.isupper(String(this));
            };
        }
        if (!proto.istitle) {
            proto.istitle = function () {
                return FrameString.istitle(String(this));
            };
        }
        if (!proto.isidentifier) {
            proto.isidentifier = function () {
                return FrameString.isidentifier(String(this));
            };
        }
    }

    static install(): void {
        FrameString.ensurePatched();
    }

    /**
     * String formatting (simplified version of Python .format())
     */
    static format(template: string, ...args: any[]): string {
        const values = args.length === 1 && Array.isArray(args[0]) ? args[0] : args;
        let result = template;
        for (const value of values) {
            result = result.replace(/\{[^{}]*\}/, String(value));
        }
        return result;
    }

    /**
     * Check if string starts with prefix
     */
    static startswith(str: string, prefix: string): boolean {
        return str.startsWith(prefix);
    }

    /**
     * Check if string ends with suffix
     */
    static endswith(str: string, suffix: string): boolean {
        return str.endsWith(suffix);
    }

    /**
     * Join array items with separator
     */
    static join(separator: string, items: any[]): string {
        return FrameRuntime.iterable(items).map(String).join(separator);
    }

    /**
     * Split string by separator
     */
    static split(str: string, separator?: string): string[] {
        if (separator === undefined) {
            // Python default: split on whitespace
            return str.trim().split(/\s+/).filter(s => s.length > 0);
        }
        return str.split(separator);
    }

    static rfind(str: string, search: string, start?: number, end?: number): number {
        let slice = str;
        if (start !== undefined || end !== undefined) {
            const s = start ?? 0;
            const e = end ?? str.length;
            slice = str.slice(s, e);
        }
        const index = slice.lastIndexOf(search);
        if (index === -1) {
            return -1;
        }
        return (start ?? 0) + index;
    }

    static find(str: string, search: string, start?: number, end?: number): number {
        let slice = str;
        if (start !== undefined || end !== undefined) {
            const s = start ?? 0;
            const e = end ?? str.length;
            slice = str.slice(s, e);
            const idx = slice.indexOf(search);
            if (idx === -1) {
                return -1;
            }
            return s + idx;
        }
        return str.indexOf(search);
    }

    static rindex(str: string, search: string, start?: number, end?: number): number {
        const idx = FrameString.rfind(str, search, start, end);
        if (idx === -1) {
            throw new Error("ValueError: substring not found");
        }
        return idx;
    }

    static index(str: string, search: string, start?: number, end?: number): number {
        let slice = str;
        if (start !== undefined || end !== undefined) {
            const s = start ?? 0;
            const e = end ?? str.length;
            slice = str.slice(s, e);
            const idx = slice.indexOf(search);
            if (idx === -1) {
                throw new Error("ValueError: substring not found");
            }
            return s + idx;
        }
        const idx = str.indexOf(search);
        if (idx === -1) {
            throw new Error("ValueError: substring not found");
        }
        return idx;
    }

    static count(str: string, sub: any, start?: number, end?: number): number {
        const subStr = String(sub);
        if (subStr.length === 0) {
            return 0;
        }
        let s = start ?? 0;
        let e = end ?? str.length;
        if (s < 0) {
            s = 0;
        }
        if (e > str.length) {
            e = str.length;
        }
        let count = 0;
        let pos = s;
        while (pos <= e - subStr.length) {
            const found = str.indexOf(subStr, pos);
            if (found === -1 || found >= e) {
                break;
            }
            count += 1;
            pos = found + subStr.length;
        }
        return count;
    }

    static splitlines(str: string): string[] {
        if (str.length === 0) {
            return [];
        }
        return str.split(/\r?\n|\r/);
    }

    static partition(str: string, sep: string): [string, string, string] {
        const idx = str.indexOf(sep);
        if (idx === -1) {
            return [str, '', ''];
        }
        return [str.slice(0, idx), sep, str.slice(idx + sep.length)];
    }

    static rpartition(str: string, sep: string): [string, string, string] {
        const idx = str.lastIndexOf(sep);
        if (idx === -1) {
            return ['', '', str];
        }
        return [str.slice(0, idx), sep, str.slice(idx + sep.length)];
    }

    static rsplit(str: string, sep?: string, maxsplit?: number): string[] {
        const splits = sep === undefined || sep === null
            ? str.trim().split(/\s+/)
            : str.split(sep);
        if (maxsplit === undefined || maxsplit <= 0) {
            return splits;
        }
        const result: string[] = [];
        let remaining = splits.slice();
        while (remaining.length > 0 && result.length < maxsplit) {
            result.unshift(remaining.pop() as string);
        }
        if (remaining.length > 0) {
            result.unshift(remaining.join(sep ?? ' '));
        }
        return result;
    }

    static center(str: string, width: number, fill: string = ' '): string {
        const pad = Math.max(0, width - str.length);
        const left = Math.floor(pad / 2);
        const right = pad - left;
        const filler = fill[0] ?? ' ';
        return filler.repeat(left) + str + filler.repeat(right);
    }

    static ljust(str: string, width: number, fill: string = ' '): string {
        const pad = Math.max(0, width - str.length);
        const filler = fill[0] ?? ' ';
        return str + filler.repeat(pad);
    }

    static rjust(str: string, width: number, fill: string = ' '): string {
        const pad = Math.max(0, width - str.length);
        const filler = fill[0] ?? ' ';
        return filler.repeat(pad) + str;
    }

    static zfill(str: string, width: number): string {
        const sign = str.startsWith('+') || str.startsWith('-') ? str[0] : '';
        const digits = sign ? str.slice(1) : str;
        const pad = Math.max(0, width - digits.length - (sign ? 1 : 0));
        return sign + '0'.repeat(pad) + digits;
    }

    static title(str: string): string {
        return str.replace(/([^\w]|^)([\w])/g, (_match, prefix, char) => prefix + String(char).toUpperCase())
                  .replace(/([^\w]|^)([\w]+)/g, (match) => {
                      const first = match.slice(0, 1);
                      return first.toUpperCase() + match.slice(1).toLowerCase();
                  });
    }

    static capitalize(str: string): string {
        if (str.length === 0) {
            return str;
        }
        return str[0].toUpperCase() + str.slice(1).toLowerCase();
    }

    static swapcase(str: string): string {
        return Array.from(str).map(ch => {
            if (ch >= 'a' && ch <= 'z') {
                return ch.toUpperCase();
            }
            if (ch >= 'A' && ch <= 'Z') {
                return ch.toLowerCase();
            }
            return ch;
        }).join('');
    }

    static isdigit(str: string): boolean {
        return str.length > 0 && /^[0-9]+$/.test(str);
    }

    static isalpha(str: string): boolean {
        return str.length > 0 && /^[A-Za-z]+$/.test(str);
    }

    static isalnum(str: string): boolean {
        return str.length > 0 && /^[A-Za-z0-9]+$/.test(str);
    }

    static isspace(str: string): boolean {
        return str.length > 0 && /^\s+$/.test(str);
    }

    static islower(str: string): boolean {
        const letters = str.match(/[A-Za-z]/g);
        if (!letters) {
            return false;
        }
        return letters.every(ch => ch === ch.toLowerCase());
    }

    static isupper(str: string): boolean {
        const letters = str.match(/[A-Za-z]/g);
        if (!letters) {
            return false;
        }
        return letters.every(ch => ch === ch.toUpperCase());
    }

    static istitle(str: string): boolean {
        if (str.length === 0) {
            return false;
        }
        const words = str.split(/\s+/);
        return words.every(word => word.length === 0 || (word[0] === word[0].toUpperCase() && word.slice(1) === word.slice(1).toLowerCase()));
    }

    static isidentifier(str: string): boolean {
        return /^[A-Za-z_][A-Za-z0-9_]*$/.test(str);
    }

    static formatMap(template: string, mapping: Record<string, any>): string {
        return template.replace(/\{([^{}]+)\}/g, (_match, key) => {
            if (mapping && Object.prototype.hasOwnProperty.call(mapping, key)) {
                return String(mapping[key]);
            }
            return `{${key}}`;
        });
    }

    static encode(str: string, encoding: string = 'utf-8'): any {
        if (typeof TextEncoder !== 'undefined' && encoding.toLowerCase() === 'utf-8') {
            return Array.from(new TextEncoder().encode(str));
        }
        // Fallback: return array of char codes
        return Array.from(str).map(ch => ch.charCodeAt(0));
    }

    static expandTabs(str: string, tabsize: number = 8): string {
        return str.replace(/\t/g, () => ' '.repeat(tabsize));
    }

    /**
     * Strip whitespace or specified characters
     */
    static strip(str: string, chars?: string): string {
        if (chars === undefined) {
            return str.trim();
        }

        // Escape special regex characters
        const escaped = chars.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
        const regex = new RegExp(`^[${escaped}]+|[${escaped}]+$`, 'g');
        return str.replace(regex, '');
    }

    static lstrip(str: string, chars?: string): string {
        if (chars === undefined) {
            return str.replace(/^\s+/, '');
        }
        const escaped = chars.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
        const regex = new RegExp(`^[${escaped}]+`, 'g');
        return str.replace(regex, '');
    }

    static rstrip(str: string, chars?: string): string {
        if (chars === undefined) {
            return str.replace(/\s+$/, '');
        }
        const escaped = chars.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
        const regex = new RegExp(`[${escaped}]+$`, 'g');
        return str.replace(regex, '');
    }

    /**
     * Convert to uppercase
     */
    static upper(str: string): string {
        return str.toUpperCase();
    }

    /**
     * Convert to lowercase
     */
    static lower(str: string): string {
        return str.toLowerCase();
    }

    /**
     * Multiply string (Python-like string * number)
     */
    static multiply(str: string, count: number): string {
        if (count <= 0) return '';
        return str.repeat(count);
    }
}

/**
 * Frame Collection Operations
 * Advanced collection methods for TypeScript
 */
export class FrameCollections {
    static defaultdict(factory: () => any): any {
        const resolvedFactory = factory ?? (() => undefined);
        const target: Record<string, any> = {};

        return new Proxy(target, {
            get: (storage, prop, receiver) => {
                if (prop === 'toJSON') {
                    return () => ({ ...storage });
                }
                if (prop === 'keys') {
                    return () => Object.keys(storage);
                }
                if (typeof prop === 'string') {
                    if (!Object.prototype.hasOwnProperty.call(storage, prop)) {
                        storage[prop] = resolvedFactory();
                    }
                    return storage[prop];
                }
                return Reflect.get(storage, prop, receiver);
            },
            set: (storage, prop, value) => {
                if (typeof prop === 'string') {
                    storage[prop] = value;
                    return true;
                }
                return false;
            },
            has: (storage, prop) => {
                if (typeof prop === 'string') {
                    return Object.prototype.hasOwnProperty.call(storage, prop);
                }
                return false;
            },
            ownKeys: (storage) => Reflect.ownKeys(storage),
            getOwnPropertyDescriptor: (storage, prop) => {
                if (typeof prop === 'string' && Object.prototype.hasOwnProperty.call(storage, prop)) {
                    return {
                        configurable: true,
                        enumerable: true,
                        value: storage[prop],
                        writable: true,
                    };
                }
                return undefined;
            }
        });
    }

    /**
     * Create dictionary from keys with default value
     */
    static dictFromKeys(keys: any[], defaultValue: any = null): Map<any, any> {
        const result = new Map();
        for (const key of keys) {
            result.set(key, defaultValue);
        }
        return result;
    }

    /**
     * Update dictionary with another dictionary
     */
    static dictUpdate(target: Map<any, any>, source: Map<any, any>): void {
        source.forEach((value, key) => {
            target.set(key, value);
        });
    }

    /**
     * Get value or set default if key doesn't exist
     */
    static dictSetDefault(dict: Map<any, any>, key: any, defaultValue: any): any {
        if (dict.has(key)) {
            return dict.get(key);
        }
        dict.set(key, defaultValue);
        return defaultValue;
    }

    /**
     * Set union operation
     */
    static setUnion(a: Set<any>, b: Set<any>): Set<any> {
        const result = new Set<any>();
        a.forEach(value => result.add(value));
        b.forEach(value => result.add(value));
        return result;
    }

    /**
     * Set intersection operation
     */
    static setIntersection(a: Set<any>, b: Set<any>): Set<any> {
        const result = new Set<any>();
        a.forEach(value => {
            if (b.has(value)) {
                result.add(value);
            }
        });
        return result;
    }

    /**
     * Set difference operation
     */
    static setDifference(a: Set<any>, b: Set<any>): Set<any> {
        const result = new Set<any>();
        a.forEach(value => {
            if (!b.has(value)) {
                result.add(value);
            }
        });
        return result;
    }

    /**
     * Extend array with another array (in-place)
     */
    static listExtend(target: any[], source: any): void {
        const items = FrameRuntime.iterable(source);
        target.push(...items);
    }

    /**
     * Insert item at specific index
     */
    static listInsert(list: any[], index: number, item: any): void {
        if (!Array.isArray(list)) {
            throw new Error("insert() requires a list");
        }
        const length = list.length;
        let position = Math.trunc(Number(index));
        if (!Number.isFinite(position)) {
            throw new Error("insert() index must be an integer");
        }
        if (position < 0) {
            position = Math.max(0, length + position);
        }
        if (position > length) {
            position = length;
        }
        list.splice(position, 0, item);
    }

    /**
     * Remove first occurrence of item
     */
    static listRemove(list: any[], item: any): boolean {
        if (!Array.isArray(list)) {
            throw new Error("remove() requires a list");
        }
        const index = list.findIndex(entry => FrameRuntime.equals(entry, item));
        if (index === -1) {
            throw new Error("ValueError: list.remove(x): x not in list");
        }
        list.splice(index, 1);
        return true;
    }

    static listClear(list: any[]): void {
        if (!Array.isArray(list)) {
            throw new Error("clear() requires a list");
        }
        list.splice(0, list.length);
    }

    static listPop(list: any[], index?: any): any {
        if (!Array.isArray(list)) {
            throw new Error("pop() requires a list");
        }
        if (list.length === 0) {
            throw new Error("IndexError: pop from empty list");
        }
        if (index === undefined) {
            return list.pop();
        }
        let position = Math.trunc(Number(index));
        if (!Number.isFinite(position)) {
            throw new Error("TypeError: slice indices must be integers or None");
        }
        if (position < 0) {
            position = list.length + position;
        }
        if (position < 0 || position >= list.length) {
            throw new Error("IndexError: pop index out of range");
        }
        const [value] = list.splice(position, 1);
        return value;
    }

    static listCount(list: any, item: any): number {
        if (typeof list === 'string') {
            return FrameString.count(list, item, 0, list.length);
        }
        const iterable = FrameRuntime.iterable(list);
        return iterable.reduce(
            (total: number, entry: any) =>
                FrameRuntime.equals(entry, item) ? total + 1 : total,
            0
        );
    }

    static listCopy(list: any[]): any[] {
        if (!Array.isArray(list)) {
            throw new Error("copy() requires a list");
        }
        return list.slice();
    }

    /**
     * Check if item is in collection (Python 'in' operator)
     */
    static contains(collection: any, item: any): boolean {
        if (typeof collection === 'string') {
            return collection.includes(item);
        }
        if (Array.isArray(collection)) {
            return collection.includes(item);
        }
        if (collection instanceof Set) {
            return collection.has(item);
        }
        if (collection instanceof Map) {
            return collection.has(item);
        }
        if (typeof collection === 'object' && collection !== null) {
            return item in collection;
        }
        return false;
    }
}

export class OrderedDict {
    constructor(initial?: any) {
        const data = { store: {} as Record<string, any>, order: [] as string[] };

        const ensureOrder = (key: string) => {
            if (!Object.prototype.hasOwnProperty.call(data.store, key)) {
                data.order.push(key);
            }
        };

        if (initial) {
            if (Array.isArray(initial)) {
                for (const [key, value] of initial) {
                    ensureOrder(key);
                    data.store[key] = value;
                }
            } else if (typeof initial === "object") {
                for (const key of Object.keys(initial)) {
                    ensureOrder(key);
                    data.store[key] = initial[key];
                }
            }
        }

        const proxy = new Proxy(data.store, {
            get: (target, prop, receiver) => {
                if (prop === "keys") {
                    return () => data.order.slice();
                }
                if (prop === "move_to_end") {
                    return (key: string, last: boolean = true) => {
                        const idx = data.order.indexOf(key);
                        if (idx === -1) {
                            return receiver;
                        }
                        data.order.splice(idx, 1);
                        if (last) {
                            data.order.push(key);
                        } else {
                            data.order.unshift(key);
                        }
                        return receiver;
                    };
                }
                if (prop === "toJSON") {
                    return () => {
                        const obj: Record<string, any> = {};
                        for (const key of data.order) {
                            obj[key] = target[key];
                        }
                        return obj;
                    };
                }
                if (typeof prop === "string") {
                    return target[prop];
                }
                return Reflect.get(target, prop, receiver);
            },
            set: (target, prop, value, receiver) => {
                if (typeof prop === "string") {
                    if (!Object.prototype.hasOwnProperty.call(target, prop)) {
                        data.order.push(prop);
                    }
                    target[prop] = value;
                    return true;
                }
                return Reflect.set(target, prop, value, receiver);
            },
            deleteProperty: (target, prop) => {
                if (typeof prop === "string") {
                    if (Object.prototype.hasOwnProperty.call(target, prop)) {
                        delete target[prop];
                        const idx = data.order.indexOf(prop);
                        if (idx >= 0) {
                            data.order.splice(idx, 1);
                        }
                    }
                    return true;
                }
                return false;
            },
            ownKeys: () => data.order.slice(),
            getOwnPropertyDescriptor: (target, prop) => {
                if (typeof prop === "string" && Object.prototype.hasOwnProperty.call(target, prop)) {
                    return {
                        configurable: true,
                        enumerable: true,
                        value: target[prop],
                        writable: true,
                    };
                }
                return undefined;
            }
        });

        ORDERED_DICT_STORE.set(proxy, data);
        return proxy as any;
    }
}

export class FrameCounter {
    constructor(iterable?: any) {
        const store = new Map<string, number>();

        const addValue = (value: any, amount: number = 1) => {
            const key = FrameDict.normalizeKey(value);
            store.set(key, (store.get(key) ?? 0) + amount);
        };

        if (iterable !== undefined) {
            for (const value of FrameRuntime.iterable(iterable)) {
                addValue(value);
            }
        }

        const proxy = new Proxy({}, {
            get: (_target, prop, receiver) => {
                if (prop === "__store__") {
                    return store;
                }
                if (prop === "most_common") {
                    return (n?: any) => {
                        const limit = n === undefined ? store.size : Number(n);
                        return Array.from(store.entries())
                            .sort((a, b) => b[1] - a[1])
                            .slice(0, limit)
                            .map(([key, value]) => [key, value]);
                    };
                }
                if (prop === "update") {
                    return (iterable: any) => {
                        for (const value of FrameRuntime.iterable(iterable)) {
                            addValue(value);
                        }
                        return receiver;
                    };
                }
                if (prop === "toJSON") {
                    return () => {
                        const obj: Record<string, number> = {};
                        store.forEach((value, key) => {
                            obj[key] = value;
                        });
                        return obj;
                    };
                }
                if (prop === "__add__") {
                    return (other: any) => FrameCounter.add(receiver, other);
                }
                if (prop === "__radd__") {
                    return (other: any) => FrameCounter.add(other, receiver);
                }
                if (prop === "__len__") {
                    return () => store.size;
                }
                if (typeof prop === "string") {
                    return store.get(prop) ?? 0;
                }
                return Reflect.get({}, prop, receiver);
            },
            set: (_target, prop, value) => {
                if (typeof prop === "string") {
                    store.set(prop, Number(value));
                    return true;
                }
                return false;
            },
            ownKeys: () => Array.from(store.keys()),
            getOwnPropertyDescriptor: (_target, prop) => {
                if (typeof prop === "string" && store.has(prop)) {
                    return {
                        configurable: true,
                        enumerable: true,
                        value: store.get(prop),
                        writable: true,
                    };
                }
                return undefined;
            }
        });

        COUNTER_STORE.set(proxy, store);
        return proxy as any;
    }

    static add(left: any, right: any): any {
        const result = new FrameCounter();
        const targetStore = COUNTER_STORE.get(result) as Map<string, number>;

        const apply = (source: any) => {
            const store = COUNTER_STORE.get(source);
            if (store instanceof Map) {
                store.forEach((value, key) => {
                    targetStore.set(key, (targetStore.get(key) ?? 0) + value);
                });
            } else if (source && typeof source === "object") {
                for (const key of Object.keys(source)) {
                    const numeric = Number((source as any)[key]);
                    targetStore.set(key, (targetStore.get(key) ?? 0) + numeric);
                }
            }
        };

        apply(left);
        apply(right);
        return result;
    }

    static update(counter: any, iterable: any): any {
        const store = COUNTER_STORE.get(counter);
        if (!(store instanceof Map)) {
            return counter;
        }
        for (const value of FrameRuntime.iterable(iterable)) {
            const key = FrameDict.normalizeKey(value);
            store.set(key, (store.get(key) ?? 0) + 1);
        }
        return counter;
    }

    static mostCommon(counter: any, n?: any): any[] {
        const store = COUNTER_STORE.get(counter);
        if (!(store instanceof Map)) {
            return [];
        }
        const limit = n === undefined ? store.size : Number(n);
        return Array.from(store.entries())
            .sort((a, b) => b[1] - a[1])
            .slice(0, limit)
            .map(([key, value]) => [key, value]);
    }
}

export class ChainMap {
    constructor(...maps: any[]) {
        const chain = maps.map((map) => (map ? map : {}));

        const proxy = new Proxy({}, {
            get: (_target, prop, receiver) => {
                if (prop === "maps") {
                    return chain;
                }
                if (prop === "new_child") {
                    return (map: any = {}) => new ChainMap(map, ...chain);
                }
                if (typeof prop === "string") {
                    for (const mapping of chain) {
                        if (Object.prototype.hasOwnProperty.call(mapping, prop)) {
                            return mapping[prop];
                        }
                    }
                    return undefined;
                }
                return Reflect.get({}, prop, receiver);
            },
            set: (_target, prop, value) => {
                if (typeof prop === "string") {
                    chain[0][prop] = value;
                    return true;
                }
                return false;
            },
            has: (_target, prop) => {
                if (typeof prop === "string") {
                    return chain.some(mapping => Object.prototype.hasOwnProperty.call(mapping, prop));
                }
                return false;
            },
            ownKeys: () => {
                const keys = new Set<string>();
                for (const mapping of chain) {
                    for (const key of Object.keys(mapping)) {
                        keys.add(key);
                    }
                }
                return Array.from(keys);
            },
            getOwnPropertyDescriptor: (_target, prop) => {
                if (typeof prop === "string") {
                    return {
                        configurable: true,
                        enumerable: true,
                        value: chain[0][prop],
                        writable: true,
                    };
                }
                return undefined;
            }
        });

        CHAINMAP_STORE.set(proxy, chain);
        return proxy as any;
    }
}

FrameString.install();

export class FrameMath {
    private static toArray(value: any): any[] {
        if (Array.isArray(value)) {
            return value;
        }
        if (value instanceof Set) {
            return Array.from(value);
        }
        if (value instanceof Map) {
            return Array.from(value.values());
        }
        if (value && typeof value[Symbol.iterator] === "function") {
            return Array.from(value as Iterable<any>);
        }
        return [value];
    }

    static get pi(): number {
        return Math.PI;
    }

    static round(value: any, ndigits?: any): number {
        const num = Number(value);
        if (!Number.isFinite(num)) {
            throw new Error("round() argument must be a finite number");
        }

        if (ndigits === undefined) {
            return Math.round(num);
        }

        const digits = Number(ndigits);
        if (!Number.isFinite(digits)) {
            throw new Error("round() precision must be a finite integer");
        }

        const factor = Math.pow(10, digits);
        return Math.round(num * factor + Number.EPSILON) / factor;
    }

    static min(first: any, ...rest: any[]): any {
        const values = rest.length === 0 ? this.toArray(first) : [first, ...rest];
        if (values.length === 0) {
            throw new Error("min() arg is an empty sequence");
        }
        return values.reduce((best, value) => (best <= value ? best : value));
    }

    static max(first: any, ...rest: any[]): any {
        const values = rest.length === 0 ? this.toArray(first) : [first, ...rest];
        if (values.length === 0) {
            throw new Error("max() arg is an empty sequence");
        }
        return values.reduce((best, value) => (best >= value ? best : value));
    }
}

export class FrameDict {
    static normalizeKey(key: any): string {
        if (key === null) {
            return "null";
        }
        if (key === undefined) {
            return "undefined";
        }
        if (typeof key === "object") {
            try {
                const custom = key.toString();
                if (typeof custom === "string" && custom !== "[object Object]") {
                    return custom;
                }
            } catch {
                // Fall through to String conversion
            }
        }
        return String(key);
    }

    private static assignEntries(target: any, entries: any): any {
        if (!entries) {
            return target;
        }

        if (entries instanceof Map) {
            entries.forEach((value, key) => {
                target[FrameDict.normalizeKey(key)] = value;
            });
            return FrameDict.ensureMethods(target);
        }

        if (Array.isArray(entries) || typeof entries[Symbol.iterator] === "function") {
            for (const entry of Array.from(entries as Iterable<any>)) {
                if (!Array.isArray(entry)) {
                    throw new Error("dict() expected iterable of key/value pairs");
                }
                const [key, value] = entry;
                target[FrameDict.normalizeKey(key)] = value;
            }
            return FrameDict.ensureMethods(target);
        }

        if (typeof entries === "object") {
            for (const [key, value] of Object.entries(entries)) {
                target[FrameDict.normalizeKey(key)] = value;
            }
            return FrameDict.ensureMethods(target);
        }

        throw new Error("Unsupported dictionary source");
    }

    private static ensureMethods(dict: any): any {
        if (dict && typeof dict === 'object') {
            if (typeof dict.keys !== 'function') {
                Object.defineProperty(dict, 'keys', {
                    value: () => Object.keys(dict),
                    enumerable: false,
                });
            }
            if (typeof dict.values !== 'function') {
                Object.defineProperty(dict, 'values', {
                    value: () => Object.keys(dict).map(key => dict[key]),
                    enumerable: false,
                });
            }
            if (typeof dict.items !== 'function') {
                Object.defineProperty(dict, 'items', {
                    value: () => Object.keys(dict).map(key => [key, dict[key]]),
                    enumerable: false,
                });
            }
        }
        return dict;
    }

    private static isDictLike(value: any): value is Record<string, any> {
        return (
            value !== null &&
            typeof value === "object" &&
            !Array.isArray(value) &&
            !(value instanceof Date) &&
            !(value instanceof Set) &&
            !(value instanceof Map)
        );
    }

    static get(dict: any, key: any, defaultValue: any = undefined): any {
        if (!dict) {
            return defaultValue;
        }
        const normalizedKey = FrameDict.normalizeKey(key);
        if (Object.prototype.hasOwnProperty.call(dict, normalizedKey)) {
            const value = dict[normalizedKey];
            return value === undefined ? defaultValue : value;
        }
        return defaultValue;
    }

    static setdefault(dict: any, key: any, defaultValue: any = null): any {
        if (!dict) {
            throw new Error("setdefault() requires a dictionary");
        }
        const normalizedKey = FrameDict.normalizeKey(key);
        if (!Object.prototype.hasOwnProperty.call(dict, normalizedKey)) {
            dict[normalizedKey] = defaultValue;
            return defaultValue;
        }
        return dict[normalizedKey];
    }

    static update(target: any, ...sources: any[]): any {
        if (!target) {
            return target;
        }
        for (const source of sources) {
            if (!source) {
                continue;
            }
            FrameDict.assignEntries(target, source);
        }
        return target;
    }

    static fromKeys(keys: any, value: any = null): any {
        const result: any = {};
        if (!keys) {
            return FrameDict.ensureMethods(result);
        }
        for (const key of FrameRuntime.iterable(keys)) {
            result[FrameDict.normalizeKey(key)] = value;
        }
        return FrameDict.ensureMethods(result);
    }

    static fromEntries(entries: any): any {
        const result: any = {};
        return FrameDict.assignEntries(result, entries);
    }

    static union(...dicts: any[]): any {
        const result: any = {};
        for (const dict of dicts) {
            FrameDict.update(result, dict);
        }
        return result;
    }

    static unionDynamic(left: any, right: any): any {
        if (typeof left === "number" && typeof right === "number") {
            return left | right;
        }

        if (typeof left === "bigint" && typeof right === "bigint") {
            return left | right;
        }

        if (left instanceof Map && right instanceof Map) {
            const result = new Map(left);
            right.forEach((value, key) => {
                result.set(key, value);
            });
            return result;
        }

        if (FrameDict.isDictLike(left) || FrameDict.isDictLike(right)) {
            const result: any = {};
            if (FrameDict.isDictLike(left)) {
                FrameDict.assignEntries(result, left);
            }
            if (FrameDict.isDictLike(right)) {
                FrameDict.assignEntries(result, right);
            }
            return result;
        }

        throw new Error("Unsupported operands for dictionary union");
    }

}

class FrameConfigParser {
    private sectionsData: Record<string, Record<string, string>> = {};
    private sectionPropertyNames: string[] = [];

    read(filenames: string | string[]): void {
        const files = Array.isArray(filenames) ? filenames : [filenames];

        for (const fileName of files) {
            if (typeof fileName !== 'string') {
                continue;
            }
            if (!FRAME_FS.existsSync(fileName)) {
                continue;
            }
            const content = FRAME_FS.readFileSync(fileName, 'utf8');
            this.parseContent(content);
        }

        this.syncSectionProperties();
    }

    private parseContent(content: string): void {
        let currentSectionName = '';
        let currentSection: Record<string, string> | null = null;

        const lines = content.split(/\r?\n/);
        for (const rawLine of lines) {
            const trimmed = rawLine.trim();
            if (!trimmed || trimmed.startsWith(';') || trimmed.startsWith('#')) {
                continue;
            }

            if (trimmed.startsWith('[') && trimmed.endsWith(']')) {
                currentSectionName = trimmed.slice(1, -1).trim();
                if (!currentSectionName) {
                    continue;
                }

                currentSection = this.sectionsData[currentSectionName] ?? {};
                this.sectionsData[currentSectionName] = currentSection;
                continue;
            }

            const separatorIndex = rawLine.indexOf('=');
            if (separatorIndex === -1) {
                continue;
            }

            if (!currentSection) {
                currentSectionName = 'DEFAULT';
                currentSection = this.sectionsData[currentSectionName] ?? {};
                this.sectionsData[currentSectionName] = currentSection;
            }

            const key = rawLine.slice(0, separatorIndex).trim();
            const value = rawLine.slice(separatorIndex + 1).trim();
            currentSection[key] = value;
        }
    }

    private syncSectionProperties(): void {
        for (const prop of this.sectionPropertyNames) {
            if (!(prop in this.sectionsData) && Object.prototype.hasOwnProperty.call(this, prop)) {
                delete (this as any)[prop];
            }
        }

        this.sectionPropertyNames = Object.keys(this.sectionsData);
        for (const section of this.sectionPropertyNames) {
            Object.defineProperty(this, section, {
                value: this.sectionsData[section],
                enumerable: true,
                writable: true,
                configurable: true,
            });
        }
    }

    sections(): string[] {
        return Object.keys(this.sectionsData);
    }

    get(section: string, option: string, defaultValue: any = undefined): any {
        const sectionData = this.sectionsData[section];
        if (!sectionData) {
            return defaultValue;
        }
        if (Object.prototype.hasOwnProperty.call(sectionData, option)) {
            return sectionData[option];
        }
        return defaultValue;
    }
}

const FrameRandom = {
    randint(min: number, max: number): number {
        const lower = Math.ceil(Number(min));
        const upper = Math.floor(Number(max));
        if (!Number.isFinite(lower) || !Number.isFinite(upper)) {
            throw new Error('randint() requires finite arguments');
        }
        if (upper < lower) {
            throw new Error('randint() upper bound less than lower bound');
        }
        return Math.floor(Math.random() * (upper - lower + 1)) + lower;
    },
    random(): number {
        return Math.random();
    },
};

const FrameTime = {
    sleep(seconds: number): void {
        FrameRuntime.sleep(seconds);
    },
    time(): number {
        return FrameRuntime.timeSeconds();
    },
};

const FrameSys = {
    exit(code?: number): never {
        const exitCode = Number.isInteger(code) ? Number(code) : 0;
        if (typeof process !== 'undefined' && typeof process.exit === 'function') {
            process.exit(exitCode);
        }
        throw new Error(`Frame sys.exit(${exitCode})`);
    },
};

const FrameSignal = {
    SIGINT: 'SIGINT',
    SIGTERM: 'SIGTERM',
    signal(signalName: any, handler: (signal: any, frame?: any) => void): (signal: any, frame?: any) => void {
        const normalized = String(signalName);
        FrameRuntime.registerSignal(normalized, handler);
        return handler;
    },
};

const FrameNumpy = {
    array(data: any): any {
        if (Array.isArray(data)) {
            return FrameNumpy.wrapArray(data);
        }
        throw new Error('numpy.array expects an array input');
    },
    wrapArray(data: any): any {
        if (Array.isArray(data)) {
            const clone = JSON.parse(JSON.stringify(data));
            FrameNumpy.attachHelpers(clone);
            return clone;
        }
        return data;
    },
    attachHelpers(value: any): void {
        if (value && typeof value === 'object' && !value.matmul) {
            Object.defineProperty(value, 'matmul', {
                enumerable: false,
                writable: true,
                configurable: true,
                value(other: any) {
                    return FrameNumpy.matmul(value, other);
                },
            });
        }
    },
    matmul(left: any, right: any): any {
        const leftIsArray = Array.isArray(left);
        const rightIsArray = Array.isArray(right);

        if (!leftIsArray || !rightIsArray) {
            throw new Error('matmul operands must be arrays');
        }

        const leftMatrix = FrameNumpy.asMatrix(left);
        const rightMatrix = FrameNumpy.asMatrix(right);

        if (leftMatrix[0].length !== rightMatrix.length) {
            throw new Error('matmul dimension mismatch');
        }

        const result: number[][] = [];
        for (let i = 0; i < leftMatrix.length; i++) {
            const row: number[] = [];
            for (let j = 0; j < rightMatrix[0].length; j++) {
                let sum = 0;
                for (let k = 0; k < leftMatrix[0].length; k++) {
                    sum += leftMatrix[i][k] * rightMatrix[k][j];
                }
                row.push(sum);
            }
            result.push(row);
        }

        if (FrameNumpy.isVector(left) && FrameNumpy.isVector(right)) {
            return result[0][0];
        }

        return FrameNumpy.wrapArray(result.length === 1 ? result[0] : result);
    },
    asMatrix(value: any): number[][] {
        const vector = FrameNumpy.isVector(value);
        if (vector) {
            const arr = value as number[];
            return [arr.map((item) => Number(item))];
        }
        return (value as any[]).map((row) => row.map((item: any) => Number(item)));
    },
    isVector(value: any): value is number[] {
        return Array.isArray(value) && (value.length === 0 || typeof value[0] !== 'object');
    },
};

export interface FrameEventParameters { [key: string]: any }

export class FrameEvent {
    constructor(public message: string, public parameters: FrameEventParameters | null) {}
}

export class FrameCompartment {
    constructor(
        public state: string,
        public enterArgs?: any,
        public exitArgs?: any,
        public stateArgs?: any,
        public stateVars?: any,
        public enterArgsCollection?: any,
        public exitArgsCollection?: any,
        public forwardEvent?: FrameEvent | null
    ) {
        this.forwardEvent = forwardEvent || null;
        this.stateArgs = stateArgs || {};
        this.stateVars = stateVars || {};
    }
}

export const os = FrameRuntime.os;
export const json = FrameRuntime.json;
export const random = FrameRandom;
export const time = FrameTime;
export const sys = FrameSys;
export const signal = FrameSignal;
export const numpy = FrameNumpy;
export const configparser = {
    ConfigParser: () => new FrameConfigParser(),
    FrameConfigParser,
};
export function open(pathValue: any, mode: any = 'r'): FrameFile {
    return FrameRuntime.open(pathValue, mode);
}

export class FrameSocketClient {
    private buffer: string = "";
    private lineQueue: string[] = [];
    private pendingReads: Array<{ resolve: (value: string) => void; reject: (reason: any) => void }> = [];
    private closed = false;
    private lastError: Error | null = null;

    private constructor(private socket: any) {
        this.socket.setEncoding('utf8');
        this.socket.on('data', (chunk: string) => this.handleData(chunk));
        this.socket.on('error', (err: Error) => this.handleError(err));
        this.socket.on('close', () => this.handleClose());
    }

    static async connect(host: string, port: number): Promise<FrameSocketClient> {
        return new Promise((resolve, reject) => {
            const socket = net.createConnection({ host, port });

            const onError = (err: Error) => {
                socket.destroy();
                reject(err);
            };

            socket.once('error', onError);
            socket.once('connect', () => {
                socket.removeListener('error', onError);
                resolve(new FrameSocketClient(socket));
            });
        });
    }

    async readLine(): Promise<string> {
        if (this.lineQueue.length > 0) {
            return Promise.resolve(this.lineQueue.shift()!);
        }

        if (this.lastError) {
            return Promise.reject(this.lastError);
        }

        if (this.closed) {
            return Promise.reject(new Error('Socket closed'));
        }

        return new Promise((resolve, reject) => {
            this.pendingReads.push({ resolve, reject });
        });
    }

    async writeLine(line: string): Promise<void> {
        if (!this.socket) {
            return Promise.reject(new Error('Socket closed'));
        }

        const payload = line.endsWith('\n') ? line : `${line}\n`;

        return new Promise((resolve, reject) => {
            const handleError = (err: Error) => {
                cleanup();
                reject(err);
            };

            const cleanup = () => {
                this.socket?.removeListener('error', handleError);
            };

            this.socket.on('error', handleError);
            this.socket.write(payload, 'utf8', () => {
                cleanup();
                resolve();
            });
        });
    }

    close(): void {
        if (this.socket) {
            try {
                this.socket.destroy();
            } catch (_err) {
                // ignore
            }
            this.socket = null;
        }
        this.handleClose();
    }

    private handleData(chunk: string): void {
        this.buffer += chunk;

        while (true) {
            const newlineIndex = this.buffer.indexOf('\n');
            if (newlineIndex === -1) {
                break;
            }

            let line = this.buffer.slice(0, newlineIndex);
            this.buffer = this.buffer.slice(newlineIndex + 1);

            if (line.endsWith('\r')) {
                line = line.slice(0, -1);
            }

            this.enqueueLine(line);
        }
    }

    private handleError(err: Error): void {
        this.lastError = err;
        this.rejectPending(err);
        this.lineQueue.length = 0;
    }

    private handleClose(): void {
        if (this.closed) {
            return;
        }
        this.closed = true;
        const reason = this.lastError ?? new Error('Socket closed');
        this.rejectPending(reason);
    }

    private enqueueLine(line: string): void {
        if (this.pendingReads.length > 0) {
            const { resolve } = this.pendingReads.shift()!;
            resolve(line);
        } else {
            this.lineQueue.push(line);
        }
    }

    private rejectPending(reason: Error): void {
        while (this.pendingReads.length > 0) {
            const { reject } = this.pendingReads.shift()!;
            reject(reason);
        }
    }
}
