# Generated by Frame Transpiler v0.66
# Multi-module Frame program

#Emitted from framec_v0.76.1

# Frame runtime classes
class FrameEvent:
    def __init__(self, message, parameters):
        self._message = message
        self._parameters = parameters

class FrameCompartment:
    def __init__(self, state, forward_event=None, exit_args=None, enter_args=None, parent_compartment=None, state_vars=None, state_args=None):
        self.state = state
        self.forward_event = forward_event
        self.exit_args = exit_args
        self.enter_args = enter_args
        self.parent_compartment = parent_compartment
        self.state_vars = state_vars or {}
        self.state_args = state_args or {}

# Module: /Users/marktruluck/projects/frame_transpiler/framec_tests/python/src/positive_tests/multifile/main_example/./test_multifile_utils.frm
#==================================================


class MathUtils:
    PI = 3.14159
    
    @staticmethod
    def add(a,b):
        return a + b
    
    @staticmethod
    def multiply(a,b):
        return a * b
    
    @staticmethod
    def circleArea(radius):
        return MathUtils.PI * radius * radius
    
    @staticmethod
    def isEven(number):
        return number % 2 == 0
    
    @staticmethod
    def factorial(n):
        if n <= 1:
            return 1
        return n * factorial(n - 1)
# Module: /Users/marktruluck/projects/frame_transpiler/framec_tests/python/src/positive_tests/multifile/main_example/test_multifile_calculator.frm
#==================================================

class Calculator:
    
    def __init__(self):
        # Create and initialize start state compartment
        self.__compartment = FrameCompartment('__calculator_state_Ready', None, None, None, None, {}, {})
        self.__next_compartment = None
        self.return_stack = [None]
        
        # Send system start event
        frame_event = FrameEvent("$>", None)
        self.__kernel(frame_event)
    # ==================== Interface Block ================== #
    
    def add(self,a,b):
        parameters = {}
        parameters["a"] = a
        parameters["b"] = b
        self.return_stack.append(None)
        __e = FrameEvent("add",parameters)
        self.__kernel(__e)
        return self.return_stack.pop(-1)
    
    def multiply(self,a,b):
        parameters = {}
        parameters["a"] = a
        parameters["b"] = b
        self.return_stack.append(None)
        __e = FrameEvent("multiply",parameters)
        self.__kernel(__e)
        return self.return_stack.pop(-1)
    
    def getCircleArea(self,r):
        parameters = {}
        parameters["r"] = r
        self.return_stack.append(None)
        __e = FrameEvent("getCircleArea",parameters)
        self.__kernel(__e)
        return self.return_stack.pop(-1)
    
    def checkEven(self,n):
        parameters = {}
        parameters["n"] = n
        self.return_stack.append(None)
        __e = FrameEvent("checkEven",parameters)
        self.__kernel(__e)
        return self.return_stack.pop(-1)
    
    # ===================== Machine Block =================== #
    
    def __handle_ready_add(self, __e, compartment):
        result = MathUtils.add(__e._parameters["a"],__e._parameters["b"])
        self.return_stack[-1] = str(result)
        return
    
    def __handle_ready_multiply(self, __e, compartment):
        result = MathUtils.multiply(__e._parameters["a"],__e._parameters["b"])
        self.return_stack[-1] = str(result)
        return
    
    def __handle_ready_getCircleArea(self, __e, compartment):
        area = MathUtils.circleArea(__e._parameters["r"])
        self.return_stack[-1] = str(area)
        return
    
    def __handle_ready_checkEven(self, __e, compartment):
        self.return_stack[-1] = MathUtils.isEven(__e._parameters["n"])
        return
    
    # ----------------------------------------
    # $Ready
    
    def __calculator_state_Ready(self, __e, compartment):
        if __e._message == "add":
            return self.__handle_ready_add(__e, compartment)
        elif __e._message == "multiply":
            return self.__handle_ready_multiply(__e, compartment)
        elif __e._message == "getCircleArea":
            return self.__handle_ready_getCircleArea(__e, compartment)
        elif __e._message == "checkEven":
            return self.__handle_ready_checkEven(__e, compartment)
        
    # ===================== State Dispatchers =================== #
    
    def _sReady(self, __e):
        return self.__calculator_state_Ready(__e, None)
    
    # ==================== System Runtime =================== #
    
    def __kernel(self, __e):
        # send event to current state
        self.__router(__e)
        
        # loop until no transitions occur
        while self.__next_compartment != None:
            next_compartment = self.__next_compartment
            self.__next_compartment = None
            
            # exit current state
            self.__router(FrameEvent("<$", self.__compartment.exit_args))
            # change state
            self.__compartment = next_compartment
            
            if next_compartment.forward_event is None:
                # send normal enter event
                self.__router(FrameEvent("$>", self.__compartment.enter_args))
            else:
                # forwarded event
                if next_compartment.forward_event._message == "$>":
                    self.__router(next_compartment.forward_event)
                else:
                    self.__router(FrameEvent("$>", self.__compartment.enter_args))
                    self.__router(next_compartment.forward_event)
                next_compartment.forward_event = None
    
    def __router(self, __e, compartment=None):
        target_compartment = compartment or self.__compartment
        if target_compartment.state == '__calculator_state_Ready':
            self.__calculator_state_Ready(__e, target_compartment)
    
    def __transition(self, next_compartment):
        self.__next_compartment = next_compartment
# End of multi-file Frame program

