# Generated by Frame Transpiler v0.66
# Multi-module Frame program

#Emitted from framec_v0.76.1

# Frame runtime classes
class FrameEvent:
    def __init__(self, message, parameters):
        self._message = message
        self._parameters = parameters

class FrameCompartment:
    def __init__(self, state, forward_event=None, exit_args=None, enter_args=None, parent_compartment=None, state_vars=None, state_args=None):
        self.state = state
        self.forward_event = forward_event
        self.exit_args = exit_args
        self.enter_args = enter_args
        self.parent_compartment = parent_compartment
        self.state_vars = state_vars or {}
        self.state_args = state_args or {}

# Module: /Users/marktruluck/projects/frame_transpiler/framec_tests/python/src/positive_tests/multifile/main_example/./test_perf_module5.frm
#==================================================


class Module5:
    @staticmethod
    def process(value):
        if value % 2 == 0:
            return value / 2
        else:
            return value * 3 + 1
    
    @staticmethod
    def helper5(base):
        result = 0
        temp = base
        while temp > 1:
            if temp % 2 == 0:
                temp = temp / 2
            else:
                temp = temp * 3 + 1
            result = result + 1
        return result
    
    @staticmethod
    def reverse_list(items):
        reversed = []
        for i in range(len(items) - 1,-1,-1):
            reversed.append(items[i])
        return reversed
# Module: /Users/marktruluck/projects/frame_transpiler/framec_tests/python/src/positive_tests/multifile/main_example/./test_perf_module2.frm
#==================================================


class Module2:
    @staticmethod
    def process(value):
        return value * 3 - 2
    
    @staticmethod
    def helper2(base):
        result = 1
        for i in range(1,base + 1):
            result = result * 2
        return result
    
    @staticmethod
    def find_max(numbers):
        if len(numbers) == 0:
            return 0
        maximum = numbers[0]
        for num in numbers:
            if num > maximum:
                maximum = num
        return maximum
# Module: /Users/marktruluck/projects/frame_transpiler/framec_tests/python/src/positive_tests/multifile/main_example/./test_perf_module4.frm
#==================================================


class Module4:
    @staticmethod
    def process(value):
        return value + 5 * 2
    
    @staticmethod
    def helper4(base):
        result = []
        for i in range(base):
            result.append(i + base)
        return len(result)
    
    @staticmethod
    def fibonacci(n):
        if n <= 1:
            return n
        return fibonacci(n - 1) + fibonacci(n - 2)
# Module: /Users/marktruluck/projects/frame_transpiler/framec_tests/python/src/positive_tests/multifile/main_example/./test_perf_module3.frm
#==================================================


class Module3:
    @staticmethod
    def process(value):
        return value ** 2 + value
    
    @staticmethod
    def helper3(base):
        result = 0
        for i in range(base):
            result = result + i * i
        return result
    
    @staticmethod
    def factorial(n):
        if n <= 1:
            return 1
        return n * factorial(n - 1)
# Module: /Users/marktruluck/projects/frame_transpiler/framec_tests/python/src/positive_tests/multifile/main_example/./test_perf_module1.frm
#==================================================


class Module1:
    @staticmethod
    def process(value):
        return value * 2 + 1
    
    @staticmethod
    def helper(base):
        result = 0
        for i in range(base):
            result = result + i * 2
        return result
    
    @staticmethod
    def compute_sum(numbers):
        total = 0
        for num in numbers:
            total = total + num
        return total
# Module: /Users/marktruluck/projects/frame_transpiler/framec_tests/python/src/positive_tests/multifile/main_example/test_multifile_large.frm
#==================================================

def process_all():
    total = 0
    for i in range(100):
        total = total + Module1.process(i)
        total = total + Module2.process(i)
        total = total + Module3.process(i)
        total = total + Module4.process(i)
        total = total + Module5.process(i)
    helper_sum = Module1.helper(10)
    helper_sum = helper_sum + Module2.helper2(10)
    helper_sum = helper_sum + Module3.helper3(10)
    helper_sum = helper_sum + Module4.helper4(10)
    helper_sum = helper_sum + Module5.helper5(10)
    return total + helper_sum

def complex_calculation(n):
    results = []
    for i in range(n):
        temp = 0
        if i % 5 == 0:
            temp = Module5.process(i)
        elif i % 4 == 0:
            temp = Module4.process(i)
        elif i % 3 == 0:
            temp = Module3.process(i)
        elif i % 2 == 0:
            temp = Module2.process(i)
        else:
            temp = Module1.process(i)
        results.append(temp)
    return results

def benchmark_large_compilation():
    print("Starting large compilation benchmark...")
    result = process_all()
    print("Process all result: " + str(result))
    complex_result = complex_calculation(20)
    print("Complex calculation count: " + str(len(complex_result)))
    print("Benchmark complete!")
    return

def main():
    benchmark_large_compilation()
    return

if __name__ == '__main__':
    main()
# Module initialization


# End of multi-file Frame program

