# Generated by Frame Transpiler v0.66
# Multi-module Frame program

#Emitted from framec_v0.76.1

# Frame runtime classes
class FrameEvent:
    def __init__(self, message, parameters):
        self._message = message
        self._parameters = parameters

class FrameCompartment:
    def __init__(self, state, forward_event=None, exit_args=None, enter_args=None, parent_compartment=None, state_vars=None, state_args=None):
        self.state = state
        self.forward_event = forward_event
        self.exit_args = exit_args
        self.enter_args = enter_args
        self.parent_compartment = parent_compartment
        self.state_vars = state_vars or {}
        self.state_args = state_args or {}

# Module: /Users/marktruluck/projects/frame_transpiler/framec_tests/python/src/positive_tests/multifile/performance/./test_perf_module2.frm
#==================================================


class Module2:
    @staticmethod
    def process(value):
        return value * 3 - 2
    
    @staticmethod
    def benchmark():
        result = 0
        for i in range(1000):
            result = result + process(i)
        return result
# Module: /Users/marktruluck/projects/frame_transpiler/framec_tests/python/src/positive_tests/multifile/performance/./test_perf_module1.frm
#==================================================


class Module1:
    @staticmethod
    def process(value):
        return value * 2 + 1
    
    @staticmethod
    def benchmark():
        result = 0
        for i in range(1000):
            result = result + process(i)
        return result
# Module: /Users/marktruluck/projects/frame_transpiler/framec_tests/python/src/positive_tests/multifile/performance/./test_perf_module5.frm
#==================================================


class Module5:
    @staticmethod
    def process(value):
        if value % 2 == 0:
            return value / 2
        else:
            return value * 3 + 1
    
    @staticmethod
    def benchmark():
        result = 0
        for i in range(1000):
            result = result + process(i)
        return result
# Module: /Users/marktruluck/projects/frame_transpiler/framec_tests/python/src/positive_tests/multifile/performance/./test_perf_module4.frm
#==================================================


class Module4:
    @staticmethod
    def process(value):
        return value + 5 * 2
    
    @staticmethod
    def benchmark():
        result = 0
        for i in range(1000):
            result = result + process(i)
        return result
# Module: /Users/marktruluck/projects/frame_transpiler/framec_tests/python/src/positive_tests/multifile/performance/./test_perf_module3.frm
#==================================================


class Module3:
    @staticmethod
    def process(value):
        return value ** 2 + value
    
    @staticmethod
    def benchmark():
        result = 0
        for i in range(1000):
            result = result + process(i)
        return result
# Module: /Users/marktruluck/projects/frame_transpiler/framec_tests/python/src/positive_tests/multifile/performance/test_multifile_performance.frm
#==================================================

def main():
    results = []
    results.append(Module1.process(1))
    results.append(Module2.process(2))
    results.append(Module3.process(3))
    results.append(Module4.process(4))
    results.append(Module5.process(5))
    for r in results:
        print("Result: " + str(r))
    print("Performance test completed with " + str(len(results)) + " modules")
    return

if __name__ == '__main__':
    main()
# Module initialization


# End of multi-file Frame program

