name: Frame tests

on : push

jobs:
  test_javascript:
    name: Test Javascript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: ls
      

    

