// Rust Visitor for Frame Language Transpiler
// Generated by visitor_generator from template
// Based on Python and TypeScript visitor patterns

use super::*;
use crate::frame_c::ast::*;
use crate::frame_c::code_builder::CodeBuilder;
use crate::frame_c::symbol_table::{SymbolConfig, Arcanum};
use std::collections::HashSet;

pub struct RustVisitor {
    pub builder: CodeBuilder,
    system_name: String,
    
    // Symbol table and config
    symbol_config: SymbolConfig,
    arcanum: Vec<Arcanum>,
    
    // Context tracking
    current_state_name: Option<String>,
    current_class_name_opt: Option<String>,
    domain_variables: HashSet<String>,
    current_handler_params: HashSet<String>,
    current_state_params: HashSet<String>,
    current_state_vars: HashSet<String>,
    current_local_vars: HashSet<String>,
    action_names: HashSet<String>,
    operation_names: HashSet<String>,
    interface_methods: Vec<String>,
    
    // Rust-specific tracking
    needs_std_collections: bool,
    needs_async_runtime: bool,
}

impl RustVisitor {
    pub fn new(
        arcanum: Vec<Arcanum>,
        symbol_config: SymbolConfig,
    ) -> Self {
        Self {
            builder: CodeBuilder::new("    "), // 4 spaces for Rust
            system_name: String::new(),
            symbol_config,
            arcanum,
            current_state_name: None,
            current_class_name_opt: None,
            domain_variables: HashSet::new(),
            current_handler_params: HashSet::new(),
            current_state_params: HashSet::new(),
            current_state_vars: HashSet::new(),
            current_local_vars: HashSet::new(),
            action_names: HashSet::new(),
            operation_names: HashSet::new(),
            interface_methods: Vec::new(),
            needs_std_collections: false,
            needs_async_runtime: false,
        }
    }
    
    pub fn get_generated_code(&self) -> String {
        let mut output = String::new();
        
        // Add Rust imports and runtime
        output.push_str(&self.generate_imports());
        output.push_str("\n");
        output.push_str(&self.generate_runtime_classes());
        output.push_str("\n");
        
        // Add transpiled system code
        output.push_str(&self.builder.get_code());
        
        // Add main function for standalone execution
        output.push_str(&self.generate_main_function());
        
        output
    }
    
    fn generate_imports(&self) -> String {
        let mut imports = String::new();
        
        imports.push_str("// Generated Rust Frame System\n");
        imports.push_str("// Transpiled from Frame Language\n\n");
        
        if self.needs_std_collections {
            imports.push_str("use std::collections::HashMap;\n");
        }
        
        if self.needs_async_runtime {
            imports.push_str("use std::future::Future;\n");
            imports.push_str("use std::pin::Pin;\n");
        }
        
        imports.push_str("use std::fmt;\n\n");
        
        imports
    }
    
    fn generate_runtime_classes(&self) -> String {
        format!(
r#"// Frame Runtime for Rust
#[derive(Debug, Clone)]
pub struct FrameEvent {{
    pub message: String,
    pub parameters: Option<HashMap<String, String>>,
}}

impl FrameEvent {{
    pub fn new(message: &str, parameters: Option<HashMap<String, String>>) -> Self {{
        Self {{
            message: message.to_string(),
            parameters,
        }}
    }}
}}

#[derive(Debug, Clone)]
pub struct FrameCompartment {{
    pub state: String,
    pub enter_args: Option<HashMap<String, String>>,
    pub exit_args: Option<HashMap<String, String>>,
    pub state_args: Option<HashMap<String, String>>,
    pub state_vars: Option<HashMap<String, String>>,
    pub forward_event: Option<FrameEvent>,
}}

impl FrameCompartment {{
    pub fn new(state: &str) -> Self {{
        Self {{
            state: state.to_string(),
            enter_args: None,
            exit_args: None,
            state_args: None,
            state_vars: None,
            forward_event: None,
        }}
    }}
}}
"#)
    }
    
    fn generate_main_function(&self) -> String {
        if !self.system_name.is_empty() {
            format!(
r#"
fn main() {{
    // Create and test the Frame system
    let mut system = {}::new();
    
    // TODO: Add test calls based on interface methods
    println!("Rust Frame System '{}' initialized successfully");
}}
"#, self.system_name, self.system_name)
        } else {
            "\nfn main() {\n    println!(\"Rust Frame System ready\");\n}\n".to_string()
        }
    }
    
    fn rust_type_from_frame(&self, frame_type: &str) -> &str {
        match frame_type {
            "string" | "str" => "String",
            "int" => "i32",
            "float" => "f64", 
            "bool" => "bool",
            _ => "String", // Default to String for unknown types
        }
    }
    
    fn generate_struct_for_system(&mut self, system_name: &str) {
        self.builder.add_line(&format!("pub struct {} {{", system_name));
        self.builder.indent();
        
        // Add Frame runtime fields
        self.builder.add_line("compartment: FrameCompartment,");
        self.builder.add_line("next_compartment: Option<FrameCompartment>,");
        self.builder.add_line("return_stack: Vec<String>,");
        
        // Add domain variables if any
        for var in &self.domain_variables {
            self.builder.add_line(&format!("{}: String,", var));
        }
        
        self.builder.dedent();
        self.builder.add_line("}");
        self.builder.add_blank_line();
    }
    
    fn generate_impl_for_system(&mut self, system_name: &str) {
        self.builder.add_line(&format!("impl {} {{", system_name));
        self.builder.indent();
        
        // Constructor
        self.builder.add_line("pub fn new() -> Self {");
        self.builder.indent();
        self.builder.add_line("Self {");
        self.builder.indent();
        self.builder.add_line(&format!("compartment: FrameCompartment::new(\"__{}_state_Start\"),", system_name.to_lowercase()));
        self.builder.add_line("next_compartment: None,");
        self.builder.add_line("return_stack: vec![\"None\".to_string()],");
        
        // Initialize domain variables
        for var in &self.domain_variables {
            self.builder.add_line(&format!("{}: String::new(),", var));
        }
        
        self.builder.dedent();
        self.builder.add_line("}");
        self.builder.dedent();
        self.builder.add_line("}");
        self.builder.add_blank_line();
        
        // Add interface methods
        for method in &self.interface_methods.clone() {
            self.generate_interface_method(method);
        }
        
        self.builder.dedent();
        self.builder.add_line("}");
    }
    
    fn generate_interface_method(&mut self, method_signature: &str) {
        // Parse method signature (simplified)
        let parts: Vec<&str> = method_signature.split('(').collect();
        if parts.len() >= 2 {
            let method_name = parts[0].trim();
            
            self.builder.add_line(&format!("pub fn {}(&mut self) -> String {{", method_name));
            self.builder.indent();
            self.builder.add_line("self.return_stack.push(\"None\".to_string());");
            self.builder.add_line(&format!("// TODO: Implement {} event dispatch", method_name));
            self.builder.add_line("self.return_stack.pop().unwrap_or_else(|| \"None\".to_string())");
            self.builder.dedent();
            self.builder.add_line("}");
            self.builder.add_blank_line();
        }
    }
}

impl AstVisitor for RustVisitor {
    fn visit_system_node(&mut self, node: &SystemNode) {
        self.system_name = node.name.clone();
        self.builder.add_line(&format!("// System: {}", node.name));
        self.builder.add_blank_line();
        
        // Will generate struct and impl after visiting all components
    }
    
    fn visit_interface_method_node(&mut self, node: &InterfaceMethodNode) {
        // Collect interface methods for later generation
        let mut signature = node.name.clone();
        signature.push('(');
        
        if let Some(params) = &node.params {
            let param_strs: Vec<String> = params.iter()
                .map(|p| format!("{}: {}", p.name, self.rust_type_from_frame(&p.param_type)))
                .collect();
            signature.push_str(&param_strs.join(", "));
        }
        
        signature.push(')');
        
        if let Some(return_type) = &node.return_type {
            signature.push_str(" -> ");
            signature.push_str(self.rust_type_from_frame(return_type));
        }
        
        self.interface_methods.push(signature);
        self.builder.add_line(&format!("// Interface method: {}", node.name));
    }
    
    fn visit_state_node(&mut self, node: &StateNode) {
        self.current_state_name = Some(node.name.clone());
        self.builder.add_line(&format!("// State: {}", node.name));
        
        // TODO: Generate Rust state handler methods
    }
    
    fn visit_event_handler_node(&mut self, node: &EventHandlerNode) {
        self.builder.add_line(&format!("// Event handler: {}", node.msg));
        
        // TODO: Generate Rust event handler implementation
    }
    
    fn visit_action_node(&mut self, node: &ActionNode) {
        self.action_names.insert(node.name.clone());
        self.builder.add_line(&format!("// Action: {}", node.name));
        
        // TODO: Generate Rust action method
    }
    
    fn visit_domain_variable_decl_node(&mut self, node: &VariableDeclNode) {
        self.domain_variables.insert(node.name.clone());
        self.builder.add_line(&format!("// Domain variable: {}", node.name));
    }
    
    // TODO: Implement remaining visitor methods based on Phase 1 requirements
    // Focus on: literal expressions, return statements, string concatenation, arithmetic
    
    fn visit_literal_expression_node_to_string(&mut self, node: &LiteralExprNode, output: &mut String) {
        match &node.value {
            crate::frame_c::scanner::TokenType::StringLiteral => {
                output.push_str(&format!("\"{}\".to_string()", node.value.to_string().trim_matches('"')));
            },
            crate::frame_c::scanner::TokenType::NumberLiteral => {
                output.push_str(&node.value.to_string());
            },
            _ => {
                output.push_str(&node.value.to_string());
            }
        }
    }
}